import postgres from 'npm:postgres@3.4.7';
const dbUrl=Deno.env.get('SUPABASE_DB_URL');if(!dbUrl)throw new Error('SUPABASE_DB_URL is required');
const sql=postgres(dbUrl,{prepare:false,max:2,idle_timeout:20,connect_timeout:10});
const SUPA=Deno.env.get('SUPABASE_URL')||'https://sjpvhgxacsiorrtijqua.supabase.co';
const ORIGINS=new Set(['https://flipgazine.pages.dev']);const BASE={'content-type':'application/json; charset=utf-8','cache-control':'no-store, private, max-age=0','pragma':'no-cache','x-content-type-options':'nosniff'};
type Claims={sub:string;session_id:string};
function b64u(s:string){return atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4))}
function claims(req:Request):Claims|null{const m=(req.headers.get('authorization')||'').match(/^Bearer\s+([^\s]+)$/i);if(!m)return null;const p=m[1].split('.');if(p.length!==3)return null;try{const c=JSON.parse(b64u(p[1]));return typeof c?.sub==='string'&&typeof c?.session_id==='string'?{sub:c.sub,session_id:c.session_id}:null}catch{return null}}
function cors(req:Request){const o=req.headers.get('origin')||'';return ORIGINS.has(o)?{'access-control-allow-origin':o,'access-control-allow-headers':'authorization, apikey, content-type, x-client-info','access-control-allow-methods':'POST, OPTIONS','access-control-max-age':'600','vary':'Origin'}:{}}
function out(req:Request,b:unknown,s=200){return new Response(JSON.stringify(b),{status:s,headers:{...BASE,...cors(req)}})}
async function admin(c:Claims){return await sql.begin(async tx=>{const a=await tx`select exists(select 1 from auth.users u join auth.sessions s on s.user_id=u.id where u.id=${c.sub}::uuid and s.id=${c.session_id}::uuid and u.deleted_at is null and (u.banned_until is null or u.banned_until<=pg_catalog.now()) and (s.not_after is null or s.not_after>pg_catalog.now())) as ok`;if(!a?.[0]?.ok)return'unauthorized';await tx`select pg_catalog.set_config('request.jwt.claim.sub',${c.sub},true)`;const z=await tx`select public.is_fg_admin() as ok`;return z?.[0]?.ok?'ok':'forbidden'})}
async function loadUnit(start:number){const rows=await sql`select s.id,s.source_ordinal,s.question_or_scenario,s.domain,s.intended_focus,s.care_case,d.raw_thai,d.raw_sha256,
  strpos(d.raw_thai,E'\\\\n')>0 as raw_has_literal_escape,
  length(d.raw_thai)-length(replace(d.raw_thai,chr(10),'')) as raw_lf_count,
  exists(select 1 from private.batch2_ai_audits a where a.source_id=s.id and a.stage='pre_human' and a.auditor='chatgpt_self') as self_audit_done,
  cardinality(private.batch2_qwen_reasons(s.id,'pre_human'))>0 as qwen_required,
  exists(select 1 from private.batch2_ai_audits a where a.source_id=s.id and a.stage='pre_human' and a.auditor='qwen_external') as qwen_done,
  h.decision,h.final_thai,h.final_sha256,h.reviewed_at,
  case when h.source_id is null then null else (select coalesce(jsonb_agg(jsonb_build_object('auditor',a.auditor,'auditor_model',a.auditor_model,'intent',a.intent,'thai_pragmatics',a.thai_pragmatics,'bff_voice',a.bff_voice,'lexical_social_fit',a.lexical_social_fit,'stance',a.stance,'composition',a.composition,'audit_index',a.audit_index,'verdict',a.verdict,'severity',a.severity,'flags',a.flags,'rationale',a.rationale,'confidence',a.confidence,'created_at',a.created_at) order by a.id),'[]'::jsonb) from private.batch2_ai_audits a where a.source_id=s.id and a.stage='pre_human') end as machine_audits
from private.batch2_sources s join private.batch2_raw_drafts d on d.source_id=s.id left join private.batch2_human_reviews h on h.source_id=s.id where s.source_ordinal between ${start} and ${start+19} order by s.source_ordinal`;
const total=await sql`select (select count(*) from private.batch2_raw_drafts) generated,(select count(*) from private.batch2_human_reviews) reviewed,(select count(*) from private.batch2_answer_map) promoted`;
return{status:'ok',start,end:start+19,metric_eligible:rows.length===20&&rows.every((r:any)=>!r.raw_has_literal_escape),rows:rows.map((r:any)=>({...r,source_ordinal:Number(r.source_ordinal),raw_lf_count:Number(r.raw_lf_count),human_review:r.decision?{decision:r.decision,final_thai:r.final_thai,final_sha256:r.final_sha256,reviewed_at:r.reviewed_at}:null,review_ready:!!r.self_audit_done&&(!r.qwen_required||r.qwen_done)&&!r.raw_has_literal_escape})),progress:{generated:Number(total[0].generated),reviewed:Number(total[0].reviewed),promoted:Number(total[0].promoted)}}}
async function runQwen(req:Request,sourceId:string){const row=await sql`select strpos(d.raw_thai,E'\\\\n')=0 as metric_ok, cardinality(private.batch2_qwen_reasons(s.id,'pre_human'))>0 as required from private.batch2_sources s join private.batch2_raw_drafts d on d.source_id=s.id where s.id=${sourceId}`;if(!row.length)return{code:404,body:{error:'source_not_found'}};if(!row[0].metric_ok)return{code:409,body:{error:'non_metric_raw_draft'}};if(!row[0].required)return{code:200,body:{status:'not_required'}};const apiKey=req.headers.get('apikey')||'';if(!apiKey)return{code:401,body:{error:'api_key_missing'}};const r=await fetch(`${SUPA}/functions/v1/batch2-qwen-audit`,{method:'POST',headers:{authorization:req.headers.get('authorization')||'',apikey:apiKey,'content-type':'application/json'},body:JSON.stringify({source_id:sourceId,stage:'pre_human'})});let data:any={};try{data=await r.json()}catch{};if(!r.ok&&r.status!==409)return{code:r.status,body:data};return{code:200,body:{status:data.status||'done',source_id:sourceId,sealed_before_human:true}}}
async function saveReview(c:Claims,body:any){const sourceId=String(body?.source_id||'').trim(),decision=String(body?.decision||'').toUpperCase(),finalThai=typeof body?.final_thai==='string'?body.final_thai:'';if(!/^B2-\d{4}$/.test(sourceId)||!['ACCEPT','EDIT','REWRITE'].includes(decision))return{code:422,body:{error:'invalid_review_input'}};const rows=await sql`select d.raw_thai,strpos(d.raw_thai,E'\\\\n')>0 as bad,exists(select 1 from private.batch2_ai_audits a where a.source_id=s.id and a.stage='pre_human' and a.auditor='chatgpt_self') as self_done,cardinality(private.batch2_qwen_reasons(s.id,'pre_human'))>0 as qwen_required,exists(select 1 from private.batch2_ai_audits a where a.source_id=s.id and a.stage='pre_human' and a.auditor='qwen_external') as qwen_done,exists(select 1 from private.batch2_human_reviews h where h.source_id=s.id) as reviewed from private.batch2_sources s join private.batch2_raw_drafts d on d.source_id=s.id where s.id=${sourceId}`;if(!rows.length)return{code:404,body:{error:'source_not_found'}};const r=rows[0];if(r.bad)return{code:409,body:{error:'non_metric_raw_draft'}};if(r.reviewed)return{code:409,body:{error:'decision_already_saved'}};if(!r.self_done||r.qwen_required&&!r.qwen_done)return{code:409,body:{error:'machine_evidence_not_sealed'}};if(finalThai.includes('\\n'))return{code:422,body:{error:'literal_escape_forbidden'}};if(decision==='ACCEPT'&&finalThai!==r.raw_thai)return{code:422,body:{error:'accept_must_preserve_draft'}};if(decision!=='ACCEPT'&&(!finalThai.trim()||finalThai===r.raw_thai))return{code:422,body:{error:'edited_text_required'}};const x=await sql`select private.batch2_record_human_review(${sourceId},${decision},'{}'::text[],${finalThai},clock_timestamp()) as result`;return{code:200,body:{status:'saved',review:x[0].result}}}
Deno.serve(async req=>{if(req.method==='OPTIONS'){const o=req.headers.get('origin')||'';return ORIGINS.has(o)?new Response(null,{status:204,headers:{...BASE,...cors(req)}}):new Response(null,{status:403,headers:BASE})}if(req.method!=='POST')return out(req,{error:'method_not_allowed'},405);const o=req.headers.get('origin');if(o&&!ORIGINS.has(o))return out(req,{error:'forbidden'},403);const c=claims(req);if(!c)return out(req,{error:'unauthorized'},401);const a=await admin(c);if(a==='unauthorized')return out(req,{error:'unauthorized'},401);if(a==='forbidden')return out(req,{error:'forbidden'},403);let body:any;try{body=await req.json()}catch{return out(req,{error:'invalid_json'},400)}try{if(body?.action==='load_unit'){const start=Number(body?.start||21);if(!Number.isInteger(start)||start<1||start>981)return out(req,{error:'invalid_start'},422);return out(req,await loadUnit(start))}if(body?.action==='run_qwen'){const id=String(body?.source_id||'');const z=await runQwen(req,id);return out(req,z.body,z.code)}if(body?.action==='save_review'){const z=await saveReview(c,body);return out(req,z.body,z.code)}return out(req,{error:'unknown_action'},422)}catch(e){console.error('batch2-production-review-service',e instanceof Error?e.message:'unknown');return out(req,{error:'service_unavailable'},503)}});