import postgres from 'npm:postgres@3.4.7';
import {buildSystemPrompt,validateDiagnosis,detectCare,DIMS,TCJ_CORE_VERSION,TCJ_CORE_BLOB_SHA,type Diagnosis} from './canonical-contract.ts';

const DB=Deno.env.get('SUPABASE_DB_URL');
const GROQ=Deno.env.get('GROQ_API_KEY');
if(!DB) throw new Error('SUPABASE_DB_URL required');
const sql=postgres(DB,{prepare:false,max:2,idle_timeout:20,connect_timeout:10});
const ORIGIN='https://flipgazine.pages.dev';
const CAMPAIGN='TCJ-JUDGE-ADMISSION-2026Q3-v1.2';
const PACK='TCJ-JUDGE-ROBUSTNESS-PERTURB-2026Q3-v1';
const PROTOCOL='TCJ-JUDGE-ROBUSTNESS-PERTURB-v1';
const PROMPT_VERSION='TCJ-ANSWERS-BFF-v2@TCJ-CORE-v1';
const SUMMARY_VERSION='TCJ-ROBUSTNESS-PERTURB-SUMMARY-v1';
const STAGE_B_PROTOCOL='TCJ-JUDGE-ADMISSION-STAGE-B-v1.1';
const TEMP=0,MAX_TOKENS=500;
const REPAIR_SUFFIX='\nYour previous output failed the required JSON contract. Return only one valid JSON object with the required keys and allowed values. Do not add rewrite or suggestion content.';

type Claims={sub:string;session_id:string};
type RuntimeInput={scenario:string;candidate:string;payload:string;meta:Record<string,unknown>};
function dec(s:string){return atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4));}
function claims(req:Request):Claims|null{const m=(req.headers.get('authorization')||'').match(/^Bearer\s+([^\s]+)$/i);if(!m)return null;try{const p=m[1].split('.');if(p.length!==3)return null;const c=JSON.parse(dec(p[1]));return typeof c?.sub==='string'&&typeof c?.session_id==='string'?{sub:c.sub,session_id:c.session_id}:null;}catch{return null;}}
function headers(origin:string|null){const h=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store, private, max-age=0','pragma':'no-cache','x-content-type-options':'nosniff','referrer-policy':'no-referrer'});if(origin===ORIGIN){h.set('access-control-allow-origin',ORIGIN);h.set('vary','Origin');h.set('access-control-allow-methods','POST, OPTIONS');h.set('access-control-allow-headers','content-type, authorization');h.set('access-control-max-age','600');}return h;}
function out(origin:string|null,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:headers(origin)});}
async function admin(c:Claims){return sql.begin(async tx=>{const a=await tx`select exists(select 1 from auth.users u join auth.sessions s on s.user_id=u.id where u.id=${c.sub}::uuid and s.id=${c.session_id}::uuid and u.deleted_at is null and (u.banned_until is null or u.banned_until<=pg_catalog.now()) and (s.not_after is null or s.not_after>pg_catalog.now())) ok`;if(!a?.[0]?.ok)return false;await tx`select pg_catalog.set_config('request.jwt.claim.sub',${c.sub},true)`;const r=await tx`select public.is_fg_admin() ok`;return !!r?.[0]?.ok;});}
async function hash(s:string){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');}
function effortFor(model:string){if(model==='qwen/qwen3.6-27b')return'none';if(model==='openai/gpt-oss-20b'||model==='openai/gpt-oss-120b')return'low';throw new Error('unsupported_model_adapter');}
function verdict(d:any){const r=d.ratings||d;if(String(d.severity||'').toUpperCase()==='CRITICAL'||Number(r.intent)===1||(Array.isArray(d.flags)&&d.flags.includes('semantic_drift')))return'not_acceptable';const v=DIMS.map(k=>Number(r[k]));if(String(d.severity||'').toUpperCase()==='MAJOR'||v.some(x=>x<=2))return'major_problem';if(String(d.severity||'').toUpperCase()==='MINOR'||v.some(x=>x===3))return'minor_problem';return'fluent';}
function totalScore(d:any){return DIMS.reduce((s,k)=>s+Number((d.ratings||d)[k]||0),0);}
function severityRank(s:string){return({PASS:0,MINOR:1,MAJOR:2,CRITICAL:3} as Record<string,number>)[String(s||'').toUpperCase()]??9;}
function verdictRank(v:string){return({fluent:0,minor_problem:1,major_problem:2,not_acceptable:3} as Record<string,number>)[String(v)]??9;}
function acceptable(d:any){const v=verdict(d);return v==='fluent'||v==='minor_problem';}

function runtimeInput(family:string,spec:any,scenario0:string,candidate0:string):RuntimeInput{
  let scenario=scenario0,candidate=candidate0,payload='';
  const meta:any={family,runtime_transform:spec?.runtime_transform||null,spec:spec||{}};
  if(family==='position_order'){
    if(spec?.runtime_transform!=='payload_key_order'||spec?.order!=='candidate_then_scenario')throw new Error('runtime_transform_spec_invalid');
    payload=JSON.stringify({candidate_response:candidate,question_or_scenario:scenario});
    meta.payload_key_order=['candidate_response','question_or_scenario'];
  }else if(family==='response_labels_ids'){
    const label=String(spec?.label||'').trim();if(spec?.runtime_transform!=='neutral_response_label'||!label)throw new Error('runtime_transform_spec_invalid');
    candidate=label+':\n'+candidate;
    payload=JSON.stringify({question_or_scenario:scenario,candidate_response:candidate});
    meta.label=label;meta.payload_key_order=['question_or_scenario','candidate_response'];
  }else if(family==='unicode_formatting'){
    const mode=String(spec?.mode||'');
    if(mode==='crlf'&&spec?.runtime_transform==='line_endings'){
      scenario=scenario.replace(/\r?\n/g,'\r\n');candidate=candidate.replace(/\r?\n/g,'\r\n');
    }else if(mode==='nbsp_for_ascii_space'&&spec?.runtime_transform==='space_codepoint'){
      scenario=scenario.replace(/ /g,'\u00a0');candidate=candidate.replace(/ /g,'\u00a0');
    }else if(mode==='selected_boundaries'&&spec?.runtime_transform==='zero_width_space'){
      scenario=scenario.replace(/\n/g,'\u200b\n');candidate=candidate.replace(/\n/g,'\u200b\n');
      if(scenario===scenario0&&candidate===candidate0){scenario=scenario.replace(/ /,'\u200b ');candidate=candidate.replace(/ /,'\u200b ');}
    }else throw new Error('runtime_transform_spec_invalid');
    if(scenario===scenario0&&candidate===candidate0)throw new Error('runtime_transform_noop');
    payload=JSON.stringify({question_or_scenario:scenario,candidate_response:candidate});
    meta.mode=mode;meta.payload_key_order=['question_or_scenario','candidate_response'];
  }else{
    payload=JSON.stringify({question_or_scenario:scenario,candidate_response:candidate});
    meta.payload_key_order=['question_or_scenario','candidate_response'];
  }
  return{scenario,candidate,payload,meta};
}
async function inputMeta(i:RuntimeInput){return{...i.meta,user_payload_sha256:await hash(i.payload),rendered_scenario_sha256:await hash(i.scenario),rendered_candidate_sha256:await hash(i.candidate)};}
async function methodologyHash(repair:boolean,effort:string,care:boolean,family:string,runtimeMeta:any){return hash(JSON.stringify({protocol:PROTOCOL,pack:PACK,prompt_version:PROMPT_VERSION,canonical_core_version:TCJ_CORE_VERSION,canonical_core_blob_sha:TCJ_CORE_BLOB_SHA,care_mode:care,family,runtime_transform:runtimeMeta,system_prompt:buildSystemPrompt(care)+(repair?REPAIR_SUFFIX:''),temperature:TEMP,max_completion_tokens:MAX_TOKENS,reasoning_effort:effort,response_format:'json_object'}));}

async function progress(){const q=await sql`select p.id pack_id,p.status pack_state,p.case_count,p.total_cells,p.manifest_sha256,p.frozen_at,p.completed_at,c.stage_b_frozen_at,c.identity_revealed_at,(select count(*)::int from private.tcj_admission_robustness_cases x where x.pack_id=p.id and x.frozen_at is not null) frozen_cases,(select count(*)::int from private.tcj_admission_robustness_cases x where x.pack_id=p.id and x.survival_state='pass') survival_pass,(select count(*)::int from private.tcj_admission_robustness_judgments j where j.pack_id=p.id and j.protocol_version=${PROTOCOL}) valid,(select count(*)::int from private.tcj_admission_robustness_failures f where f.pack_id=p.id and f.protocol_version=${PROTOCOL} and f.evidence_state='terminal' and f.failure_class='generation_contract') terminal_contract,(select count(*)::int from private.tcj_admission_robustness_failures f where f.pack_id=p.id and f.protocol_version=${PROTOCOL} and f.evidence_state='active' and f.failure_class='transient_provider') transient_failures,(select count(*)::int from private.tcj_admission_robustness_failures f where f.pack_id=p.id and f.protocol_version=${PROTOCOL} and f.evidence_state='active' and f.failure_class in ('generation_contract','infrastructure')) blockers,(select count(*)::int from private.tcj_admission_robustness_summaries s where s.pack_id=p.id and s.summary_version=${SUMMARY_VERSION}) summaries,(select count(*)::int from private.tcj_admission_campaign_candidates cc join private.tcj_judge_candidates j on j.id=cc.judge_candidate_id where cc.campaign_id=p.campaign_id and j.identity_state='sealed') sealed from private.tcj_admission_robustness_packs p join private.tcj_admission_campaigns c on c.id=p.campaign_id where p.pack_key=${PACK} and c.campaign_key=${CAMPAIGN} limit 1`;const r=q[0];if(!r)throw new Error('perturbation_pack_missing');const valid=Number(r.valid||0),terminal=Number(r.terminal_contract||0),done=valid+terminal,total=Number(r.total_cells||0);return{pack_key:PACK,pack_state:String(r.pack_state),protocol_version:PROTOCOL,evidence_class:'preliminary_constructed_calibration_derived',case_count:Number(r.case_count||0),total,done,valid,terminal_contract:terminal,pending:Math.max(0,total-done),transient_failures:Number(r.transient_failures||0),blockers:Number(r.blockers||0),summaries:Number(r.summaries||0),frozen_cases:Number(r.frozen_cases||0),survival_pass:Number(r.survival_pass||0),manifest_sha256:r.manifest_sha256||null,stage_b_frozen:!!r.stage_b_frozen_at,identities_sealed:Number(r.sealed||0)===3&&!r.identity_revealed_at,identity_revealed:!!r.identity_revealed_at,frozen_at:r.frozen_at,completed_at:r.completed_at};}
async function recordFailure(packId:number,caseId:number,judgeId:number,httpStatus:number|null,errorCode:string,failureClass:'transient_provider'|'generation_contract'|'infrastructure',state:'active'|'terminal',meta:any,retryable:boolean){const old=await sql`select attempt_count from private.tcj_admission_robustness_failures where pack_id=${packId} and case_id=${caseId} and judge_candidate_id=${judgeId} and protocol_version=${PROTOCOL} limit 1`;const attempt=Number(old[0]?.attempt_count||0)+1,delay=Math.min(120,5*Math.pow(2,Math.min(attempt-1,5))),retryIso=retryable?new Date(Date.now()+delay*1000).toISOString():null;await sql`insert into private.tcj_admission_robustness_failures(pack_id,case_id,judge_candidate_id,protocol_version,prompt_version,attempt_count,last_http_status,last_error_code,failure_class,evidence_state,first_failed_at,last_failed_at,next_retry_at,resolved_at,error_meta) values(${packId},${caseId},${judgeId},${PROTOCOL},${PROMPT_VERSION},${attempt},${httpStatus},${errorCode},${failureClass},${state},pg_catalog.now(),pg_catalog.now(),${retryIso}::timestamptz,null,${sql.json(meta||{})}) on conflict(pack_id,case_id,judge_candidate_id,protocol_version) do update set attempt_count=${attempt},last_http_status=${httpStatus},last_error_code=${errorCode},failure_class=${failureClass},evidence_state=${state},last_failed_at=pg_catalog.now(),next_retry_at=${retryIso}::timestamptz,resolved_at=null,error_meta=${sql.json(meta||{})}`;return delay;}
async function markResolved(packId:number,caseId:number,judgeId:number){await sql`update private.tcj_admission_robustness_failures set resolved_at=pg_catalog.now(),next_retry_at=null,evidence_state='resolved' where pack_id=${packId} and case_id=${caseId} and judge_candidate_id=${judgeId} and protocol_version=${PROTOCOL} and evidence_state<>'invalidated'`;}
async function providerCall(model:string,input:RuntimeInput,care:boolean,repair:boolean){if(!GROQ)throw new Error('groq_secret_missing');const effort=effortFor(model),system=buildSystemPrompt(care)+(repair?REPAIR_SUFFIX:'');const started=performance.now();const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{authorization:`Bearer ${GROQ}`,'content-type':'application/json'},body:JSON.stringify({model,temperature:TEMP,max_completion_tokens:MAX_TOKENS,reasoning_effort:effort,response_format:{type:'json_object'},stream:false,messages:[{role:'system',content:system},{role:'user',content:input.payload}]})});const latency=Math.round(performance.now()-started);let payload:any=null;try{payload=await r.json();}catch{}return{ok:r.ok,status:r.status,payload,latency,effort,care,repair};}
async function insertAttempt(a:any){const raw=String(a.content||''),sha=raw?await hash(raw):null;let parsed:any=null;try{parsed=raw?JSON.parse(raw):null;}catch{}await sql`insert into private.tcj_admission_robustness_attempts(pack_id,case_id,judge_candidate_id,protocol_version,prompt_version,attempt_index,attempt_role,http_status,finish_reason,outcome_class,error_code,raw_output_text,raw_output_sha256,parsed_output,generation_settings,usage,latency_ms,evidence_eligible) values(${a.packId},${a.caseId},${a.judgeId},${PROTOCOL},${PROMPT_VERSION},${a.attemptIndex},${a.role},${a.httpStatus},${a.finishReason||null},${a.outcome},${a.errorCode||null},${raw||null},${sha},${parsed?sql.json(parsed):null},${sql.json(a.settings||{})},${sql.json(a.usage||{})},${a.latency||null},true) on conflict(pack_id,case_id,judge_candidate_id,protocol_version,attempt_index) do nothing`;return parsed;}
async function persistJudgment(args:any){const diagnosis:Diagnosis=args.diagnosis,raw=args.raw,dsha=await hash(JSON.stringify(diagnosis)),msha=await methodologyHash(!!args.repairUsed,String(args.effort),!!args.care,String(args.family),args.runtimeMeta),opaque='PJ-'+crypto.randomUUID().replaceAll('-','').slice(0,14).toUpperCase(),usage=args.usage||{},settings={temperature:TEMP,max_completion_tokens:MAX_TOKENS,reasoning_effort:String(args.effort),response_format:'json_object',care_mode:!!args.care,repair_used:!!args.repairUsed,first_pass_error:args.firstError||null,robustness_family:String(args.family),runtime_input:args.runtimeMeta,canonical_core_version:TCJ_CORE_VERSION,canonical_core_blob_sha:TCJ_CORE_BLOB_SHA,recovered_from_preserved_attempt:!!args.recovered},usageOut={prompt_tokens:Number(usage?.prompt_tokens||0),completion_tokens:Number(usage?.completion_tokens||0),total_tokens:Number(usage?.total_tokens||0),reasoning_tokens:Number(usage?.completion_tokens_details?.reasoning_tokens||0),finish_reason:String(args.finishReason||'')||null};await sql`insert into private.tcj_admission_robustness_judgments(pack_id,case_id,judge_candidate_id,opaque_judgment_id,protocol_version,prompt_version,methodology_sha256,diagnosis,diagnosis_sha256,raw_output,predicted_verdict,generation_settings,usage,latency_ms) values(${args.packId},${args.caseId},${args.judgeId},${opaque},${PROTOCOL},${PROMPT_VERSION},${msha},${sql.json(diagnosis)},${dsha},${sql.json(raw)},${verdict(diagnosis)},${sql.json(settings)},${sql.json(usageOut)},${Number(args.latency||0)}) on conflict(pack_id,case_id,judge_candidate_id) do nothing`;await markResolved(args.packId,args.caseId,args.judgeId);}
async function classify(call:any,packId:number,caseId:number,judgeId:number,attemptIndex:number,role:'primary'|'repair',family:string,runtimeMeta:any){const choice=call.payload?.choices?.[0]||{},finish=String(choice?.finish_reason||''),content=String(choice?.message?.content||'').trim(),usage=call.payload?.usage||{},settings={temperature:TEMP,max_completion_tokens:MAX_TOKENS,reasoning_effort:call.effort,response_format:'json_object',care_mode:call.care,repair:role==='repair',robustness_family:family,runtime_input:runtimeMeta,canonical_core_blob_sha:TCJ_CORE_BLOB_SHA};if(finish==='length'){await insertAttempt({packId,caseId,judgeId,attemptIndex,role,httpStatus:200,finishReason:finish,outcome:'length',errorCode:'generation_length_limit',content,settings,usage,latency:call.latency});return{kind:'terminal',error:'generation_length_limit'};}if(!content){await insertAttempt({packId,caseId,judgeId,attemptIndex,role,httpStatus:200,finishReason:finish,outcome:'empty',errorCode:'empty_generation',content,settings,usage,latency:call.latency});return{kind:'terminal',error:'empty_generation'};}try{const raw=JSON.parse(content),diagnosis=validateDiagnosis(raw);await insertAttempt({packId,caseId,judgeId,attemptIndex,role,httpStatus:200,finishReason:finish,outcome:'valid',content,settings,usage,latency:call.latency});return{kind:'valid',raw,diagnosis};}catch(e){const code=e instanceof Error?e.message:'invalid_json';await insertAttempt({packId,caseId,judgeId,attemptIndex,role,httpStatus:200,finishReason:finish,outcome:'invalid_schema',errorCode:code,content,settings,usage,latency:call.latency});return{kind:'invalid',error:code};}}
async function providerFailure(call:any,packId:number,caseId:number,judgeId:number){const hs=Number(call.status||0),retryable=hs===429||hs>=500,code=`groq_${hs||'error'}`;if(retryable){const delay=await recordFailure(packId,caseId,judgeId,hs,code,'transient_provider','active',{provider_error_type:call.payload?.error?.type||null,provider_error_message:String(call.payload?.error?.message||'').slice(0,500)},true);return{status:'deferred',retry_after_seconds:delay};}await recordFailure(packId,caseId,judgeId,hs,code,'infrastructure','active',{provider_error_type:call.payload?.error?.type||null,provider_error_message:String(call.payload?.error?.message||'').slice(0,500),classification:'provider_or_adapter_contract_requires_diagnosis'},false);return{status:'blocked',reason:'provider_or_adapter_contract_failure'};}

function familyBucket(){const dimensions:any={};for(const k of DIMS)dimensions[k]={cases:0,exact:0,within_one:0,abs_delta_sum:0,mean_abs_delta:null};return{cases:0,valid:0,terminal:0,severity_exact:0,verdict_exact:0,total_score_delta_sum:0,mean_total_score_delta:null,dimensions};}
async function finalizePack(packId:number,campaignId:number){const candidates=await sql`select j.id from private.tcj_admission_campaign_candidates cc join private.tcj_judge_candidates j on j.id=cc.judge_candidate_id where cc.campaign_id=${campaignId} order by j.id`;for(const c of candidates){const judgeId=Number(c.id);const rows=await sql`select rc.id case_id,rc.case_key,rc.family,rc.expected_effect,rj.diagnosis,rj.diagnosis_sha256,bj.diagnosis baseline,exists(select 1 from private.tcj_admission_robustness_failures f where f.pack_id=${packId} and f.case_id=rc.id and f.judge_candidate_id=${judgeId} and f.protocol_version=${PROTOCOL} and f.evidence_state='terminal') terminal from private.tcj_admission_robustness_cases rc left join private.tcj_admission_robustness_judgments rj on rj.pack_id=rc.pack_id and rj.case_id=rc.id and rj.judge_candidate_id=${judgeId} and rj.protocol_version=${PROTOCOL} left join private.tcj_admission_stage_b_judgments bj on bj.campaign_id=${campaignId} and bj.evidence_item_id=rc.source_evidence_item_id and bj.judge_candidate_id=${judgeId} and bj.protocol_version=${STAGE_B_PROTOCOL} where rc.pack_id=${packId} order by rc.case_key`;
  const metrics:any={case_count:33,valid:0,terminal:0,baseline_missing:0,families:{},effects:{invariant:{cases:0,valid:0,stable:0,strict_exact:0},contract_resistance:{cases:0,valid:0,stable:0,strict_exact:0,score_inflation:0,severity_or_verdict_improvement:0},degrade:{cases:0,valid:0,degrade_observed:0},preserve_acceptability:{cases:0,valid:0,applicable:0,preserved:0},context_sensitive:{cases:0,valid:0,change_observed:0},descriptive:{cases:0,valid:0}},preliminary_only:true,qualification_sufficient:false,assurance_eligible:false};
  for(const row of rows){const fam=String(row.family),effect=String(row.expected_effect);if(!metrics.families[fam])metrics.families[fam]=familyBucket();const fb=metrics.families[fam];fb.cases++;if(metrics.effects[effect])metrics.effects[effect].cases++;if(row.terminal){fb.terminal++;metrics.terminal++;continue;}if(!row.diagnosis){continue;}if(!row.baseline){metrics.baseline_missing++;continue;}metrics.valid++;fb.valid++;if(metrics.effects[effect])metrics.effects[effect].valid++;const d=row.diagnosis,b=row.baseline,vd=verdict(d),vb=verdict(b),sd=severityRank(d.severity)-severityRank(b.severity),vrd=verdictRank(vd)-verdictRank(vb),td=totalScore(d)-totalScore(b);fb.total_score_delta_sum+=td;if(String(d.severity)===String(b.severity))fb.severity_exact++;if(vd===vb)fb.verdict_exact++;let allExact=true,allWithin=true,anyChange=String(d.severity)!==String(b.severity)||vd!==vb;for(const k of DIMS){const a=Number(d.ratings?.[k]),bb=Number(b.ratings?.[k]),delta=Math.abs(a-bb),m=fb.dimensions[k];m.cases++;if(delta===0)m.exact++;else{allExact=false;anyChange=true;}if(delta<=1)m.within_one++;else allWithin=false;m.abs_delta_sum+=delta;}const stable=String(d.severity)===String(b.severity)&&vd===vb&&allWithin;const strict=String(d.severity)===String(b.severity)&&vd===vb&&allExact;if(effect==='invariant'){if(stable)metrics.effects.invariant.stable++;if(strict)metrics.effects.invariant.strict_exact++;}else if(effect==='contract_resistance'){if(stable)metrics.effects.contract_resistance.stable++;if(strict)metrics.effects.contract_resistance.strict_exact++;if(td>0)metrics.effects.contract_resistance.score_inflation++;if(sd<0||vrd<0)metrics.effects.contract_resistance.severity_or_verdict_improvement++;}else if(effect==='degrade'){if(td<0||sd>0||vrd>0)metrics.effects.degrade.degrade_observed++;}else if(effect==='preserve_acceptability'){if(acceptable(b)){metrics.effects.preserve_acceptability.applicable++;if(acceptable(d))metrics.effects.preserve_acceptability.preserved++;}}else if(effect==='context_sensitive'){if(anyChange)metrics.effects.context_sensitive.change_observed++;}}
  for(const fb of Object.values<any>(metrics.families)){if(fb.valid)fb.mean_total_score_delta=Math.round((fb.total_score_delta_sum/fb.valid)*1000)/1000;for(const k of DIMS){const m=fb.dimensions[k];if(m.cases)m.mean_abs_delta=Math.round((m.abs_delta_sum/m.cases)*1000)/1000;}fb.severity_agreement=fb.valid?fb.severity_exact/fb.valid:null;fb.verdict_agreement=fb.valid?fb.verdict_exact/fb.valid:null;}
  const attempts=await sql`select count(*) filter(where attempt_role='primary' and outcome_class='valid')::int primary_valid,count(*) filter(where attempt_role='repair')::int repairs,count(*) filter(where attempt_role='repair' and outcome_class='valid')::int repair_success from private.tcj_admission_robustness_attempts where pack_id=${packId} and judge_candidate_id=${judgeId} and protocol_version=${PROTOCOL} and evidence_eligible=true`;
  const transient=await sql`select coalesce(sum(attempt_count),0)::int n from private.tcj_admission_robustness_failures where pack_id=${packId} and judge_candidate_id=${judgeId} and protocol_version=${PROTOCOL} and failure_class='transient_provider'`;
  const terminal=await sql`select count(*)::int n from private.tcj_admission_robustness_failures where pack_id=${packId} and judge_candidate_id=${judgeId} and protocol_version=${PROTOCOL} and evidence_state='terminal'`;
  const a=attempts[0]||{},reliability={structured_output_primary_valid:Number(a.primary_valid||0),repair_attempts:Number(a.repairs||0),repair_success:Number(a.repair_success||0),terminal_contract_failures:Number(terminal[0]?.n||0),provider_failure_attempts:Number(transient[0]?.n||0),preliminary_only:true,qualification_sufficient:false,assurance_eligible:false};
  const parts:string[]=[];for(const row of rows){if(row.diagnosis_sha256)parts.push(`${row.case_key}:V:${row.diagnosis_sha256}`);else{const at=(await sql`select raw_output_sha256,error_code from private.tcj_admission_robustness_attempts where pack_id=${packId} and case_id=${row.case_id} and judge_candidate_id=${judgeId} and protocol_version=${PROTOCOL} order by attempt_index desc limit 1`)[0];parts.push(`${row.case_key}:T:${at?.raw_output_sha256||at?.error_code||'contract_failure'}`);}}const manifest=await hash(parts.join('|'));
  await sql`insert into private.tcj_admission_robustness_summaries(pack_id,judge_candidate_id,summary_version,repeat_metrics,self_preference_metrics,perturbation_metrics,reliability_metrics,evidence_manifest_sha256,frozen_at) values(${packId},${judgeId},${SUMMARY_VERSION},${sql.json({})},${sql.json({})},${sql.json(metrics)},${sql.json(reliability)},${manifest},pg_catalog.now()) on conflict(pack_id,judge_candidate_id) do nothing`;
 }
 await sql`update private.tcj_admission_robustness_packs set status='complete',completed_at=coalesce(completed_at,pg_catalog.now()) where id=${packId} and status='running'`;
}

async function runNext(){const p=await progress();if(p.identity_revealed||!p.identities_sealed)return{status:'blocked',reason:'identity_gate',...p};if(!p.stage_b_frozen)return{status:'blocked',reason:'stage_b_not_frozen',...p};if(p.blockers>0)return{status:'blocked',reason:'adapter_or_infrastructure_validity_failure',...p};if(p.pack_state==='complete'||p.pending<=0)return{status:'complete',...p};const pack=(await sql`select p.id,p.status,p.campaign_id from private.tcj_admission_robustness_packs p join private.tcj_admission_campaigns c on c.id=p.campaign_id where p.pack_key=${PACK} and c.campaign_key=${CAMPAIGN} limit 1`)[0];if(!pack)throw new Error('perturbation_pack_missing');if(!['frozen','running'].includes(String(pack.status)))return{status:'blocked',reason:'perturbation_pack_state',...p};if(pack.status==='frozen')await sql`update private.tcj_admission_robustness_packs set status='running' where id=${pack.id} and status='frozen'`;
 const next=await sql`select rc.id case_id,rc.family,rc.scenario_text,rc.candidate_text,rc.perturbation_spec,j.id judge_candidate_id,j.provider,j.model_name from private.tcj_admission_robustness_cases rc join private.tcj_admission_robustness_packs p on p.id=rc.pack_id join private.tcj_admission_campaign_candidates cc on cc.campaign_id=p.campaign_id join private.tcj_judge_candidates j on j.id=cc.judge_candidate_id left join private.tcj_admission_robustness_failures f on f.pack_id=p.id and f.case_id=rc.id and f.judge_candidate_id=j.id and f.protocol_version=${PROTOCOL} where p.id=${pack.id} and rc.frozen_at is not null and rc.review_state='approved' and rc.survival_state='pass' and j.identity_state='sealed' and not exists(select 1 from private.tcj_admission_robustness_judgments x where x.pack_id=p.id and x.case_id=rc.id and x.judge_candidate_id=j.id) and not exists(select 1 from private.tcj_admission_robustness_failures t where t.pack_id=p.id and t.case_id=rc.id and t.judge_candidate_id=j.id and t.protocol_version=${PROTOCOL} and t.evidence_state='terminal') and (f.id is null or f.evidence_state='resolved' or (f.failure_class='transient_provider' and f.evidence_state='active' and f.next_retry_at<=pg_catalog.now())) order by rc.case_key,j.id limit 1`;
 if(!next.length){const now=await progress();if(now.blockers>0)return{status:'blocked',reason:'adapter_or_infrastructure_validity_failure',...now};if(now.pending<=0){await finalizePack(Number(pack.id),Number(pack.campaign_id));return{status:'complete',...(await progress())};}const w=await sql`select greatest(1,ceil(extract(epoch from (min(next_retry_at)-pg_catalog.now()))))::int seconds from private.tcj_admission_robustness_failures where pack_id=${pack.id} and protocol_version=${PROTOCOL} and evidence_state='active' and failure_class='transient_provider' and next_retry_at>pg_catalog.now()`;return{status:'waiting_retry',retry_after_seconds:Number(w[0]?.seconds||5),...now};}
 const x:any=next[0];let input:RuntimeInput;try{input=runtimeInput(String(x.family),x.perturbation_spec||{},String(x.scenario_text),String(x.candidate_text));}catch(e){const code=e instanceof Error?e.message:'runtime_transform_error';await recordFailure(Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id),null,code,'infrastructure','active',{classification:'runtime_transform_validity',family:String(x.family)},false);return{status:'blocked',reason:code,...(await progress())};}const rmeta=await inputMeta(input),care=detectCare(String(x.scenario_text));if(x.provider!=='groq'){await recordFailure(Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id),null,'unsupported_provider','infrastructure','active',{classification:'adapter_validity'},false);return{status:'blocked',reason:'unsupported_provider',...(await progress())};}
 const prior=await sql`select attempt_index,attempt_role,outcome_class,error_code,parsed_output,generation_settings,usage,latency_ms,finish_reason from private.tcj_admission_robustness_attempts where pack_id=${pack.id} and case_id=${x.case_id} and judge_candidate_id=${x.judge_candidate_id} and protocol_version=${PROTOCOL} and evidence_eligible=true order by attempt_index`;let firstError:string|null=null;const validPrior=prior.find((a:any)=>a.outcome_class==='valid');if(validPrior?.parsed_output){const raw=validPrior.parsed_output,diagnosis=validateDiagnosis(raw),gs=validPrior.generation_settings||{},repair=String(validPrior.attempt_role)==='repair';await persistJudgment({packId:Number(pack.id),caseId:Number(x.case_id),judgeId:Number(x.judge_candidate_id),diagnosis,raw,effort:String(gs.reasoning_effort||effortFor(String(x.model_name))),care:!!gs.care_mode,repairUsed:repair,firstError:repair?String(prior[0]?.error_code||prior[0]?.outcome_class||'invalid_schema'):null,family:String(x.family),runtimeMeta:gs.runtime_input||rmeta,usage:validPrior.usage||{},finishReason:validPrior.finish_reason||'recovered',latency:Number(validPrior.latency_ms||0),recovered:true});const after=await progress();if(after.pending<=0){await finalizePack(Number(pack.id),Number(pack.campaign_id));return{status:'complete',...(await progress())};}return{status:'ok',...after};}
 if(prior.length&&prior[0].outcome_class!=='valid')firstError=String(prior[0].error_code||prior[0].outcome_class);
 if(!prior.length){const call=await providerCall(String(x.model_name),input,care,false);if(!call.ok){const r=await providerFailure(call,Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id));return{...r,...(await progress())};}const cls:any=await classify(call,Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id),1,'primary',String(x.family),rmeta);if(cls.kind==='valid'){await persistJudgment({packId:Number(pack.id),caseId:Number(x.case_id),judgeId:Number(x.judge_candidate_id),diagnosis:cls.diagnosis,raw:cls.raw,effort:call.effort,care,repairUsed:false,firstError:null,family:String(x.family),runtimeMeta:rmeta,usage:call.payload?.usage||{},finishReason:call.payload?.choices?.[0]?.finish_reason||'',latency:call.latency,recovered:false});const after=await progress();if(after.pending<=0){await finalizePack(Number(pack.id),Number(pack.campaign_id));return{status:'complete',...(await progress())};}return{status:'ok',...after};}if(cls.kind==='terminal'){await recordFailure(Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id),200,cls.error,'generation_contract','terminal',{stage:'primary',care_mode:care,policy:'terminal_no_resample',runtime_input:rmeta},false);return{status:'cell_terminal',...(await progress())};}firstError=cls.error;}
 const repairPrior=prior.find((a:any)=>Number(a.attempt_index)===2);if(repairPrior){if(repairPrior.outcome_class==='valid'&&repairPrior.parsed_output){const raw=repairPrior.parsed_output,diagnosis=validateDiagnosis(raw),gs=repairPrior.generation_settings||{};await persistJudgment({packId:Number(pack.id),caseId:Number(x.case_id),judgeId:Number(x.judge_candidate_id),diagnosis,raw,effort:String(gs.reasoning_effort||effortFor(String(x.model_name))),care:!!gs.care_mode,repairUsed:true,firstError,family:String(x.family),runtimeMeta:gs.runtime_input||rmeta,usage:repairPrior.usage||{},finishReason:repairPrior.finish_reason||'recovered',latency:Number(repairPrior.latency_ms||0),recovered:true});return{status:'ok',...(await progress())};}await recordFailure(Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id),200,String(repairPrior.error_code||'repair_invalid'),'generation_contract','terminal',{stage:'repair',first_pass_error:firstError,policy:'one_repair_then_terminal',runtime_input:rmeta},false);return{status:'cell_terminal',...(await progress())};}
 const repair=await providerCall(String(x.model_name),input,care,true);if(!repair.ok){const r=await providerFailure(repair,Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id));return{...r,...(await progress())};}const rc:any=await classify(repair,Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id),2,'repair',String(x.family),rmeta);if(rc.kind==='valid'){await persistJudgment({packId:Number(pack.id),caseId:Number(x.case_id),judgeId:Number(x.judge_candidate_id),diagnosis:rc.diagnosis,raw:rc.raw,effort:repair.effort,care,repairUsed:true,firstError,family:String(x.family),runtimeMeta:rmeta,usage:repair.payload?.usage||{},finishReason:repair.payload?.choices?.[0]?.finish_reason||'',latency:repair.latency,recovered:false});const after=await progress();if(after.pending<=0){await finalizePack(Number(pack.id),Number(pack.campaign_id));return{status:'complete',...(await progress())};}return{status:'ok',...after};}await recordFailure(Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id),200,rc.error,'generation_contract','terminal',{stage:'repair',first_pass_error:firstError,policy:'one_repair_then_terminal',runtime_input:rmeta},false);return{status:'cell_terminal',...(await progress())};}

Deno.serve(async(req:Request)=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return origin===ORIGIN?new Response(null,{status:204,headers:headers(origin)}):out(origin,{error:'forbidden'},403);if(origin!==ORIGIN)return out(origin,{error:'forbidden'},403);if(req.method!=='POST')return out(origin,{error:'method_not_allowed'},405);const c=claims(req);if(!c)return out(origin,{error:'unauthorized'},401);if(!(await admin(c)))return out(origin,{error:'forbidden'},403);let body:any={};try{body=await req.json();}catch{return out(origin,{error:'invalid_json'},400);}try{if(body?.action==='status')return out(origin,{status:'ok',...(await progress())});if(body?.action==='run_next')return out(origin,await runNext());return out(origin,{error:'invalid_action'},422);}catch(e){console.error('tcj-admission-perturbation-runner-v1',e);return out(origin,{error:e instanceof Error?e.message:'service_unavailable'},503);}});
