import postgres from 'npm:postgres@3.4.7';

const DB=Deno.env.get('SUPABASE_DB_URL');
if(!DB) throw new Error('SUPABASE_DB_URL required');
const sql=postgres(DB,{prepare:false,max:2,idle_timeout:20,connect_timeout:10});
const ORIGIN='https://flipgazine.pages.dev';
const CAMPAIGN='TCJ-JUDGE-ADMISSION-2026Q3-v1.2';
const DOSSIER_VERSION='TCJ-JUDGE-PASSPORT-DOSSIER-v1';
const PROTOCOL='TCJ-JUDGE-META-REVIEW-v1';
const OPENAI_KEY=Deno.env.get('OPENAI_API_KEY')||'';
const XAI_KEY=Deno.env.get('XAI_API_KEY')||'';
const CHATGPT_MODEL=Deno.env.get('TCJ_META_CHATGPT_MODEL')||'gpt-5.6-sol';
const GROK_MODEL=Deno.env.get('TCJ_META_GROK_MODEL')||'grok-4.6';
const DIMS=['intent','thai_pragmatics','bff_voice','lexical_social_fit','stance','composition'] as const;
const STATES=new Set(['qualified','partially_qualified','research_only','rejected']);
const CONF=new Set(['high','medium','low']);
const SYSTEM=`You are an independent blind meta-reviewer for the Thai Conversation Judge (TCJ) Judge Admission protocol.
You receive one anonymous, frozen Judge Passport dossier. Treat it as the complete evidence available for this review. Do not infer, guess, name, or speculate about the candidate model, provider, family, organization, or identity. Do not use outside knowledge about likely model behavior.
Assess each TCJ dimension independently. Respect every evidence boundary in the dossier: exposed Calibration evidence is not clean Qualification evidence, constructed robustness is not Assurance evidence, and the absence of a hidden Qualification Bank limits the strength of any recommendation.
Return exactly one JSON object, no markdown and no extra text, with exactly these keys:
- dimension_recommendations
- overall_recommendation
- overall_confidence
- strengths
- failure_clusters
- evidence_limitations
- rationale
The dimension_recommendations object must contain exactly these six keys: intent, thai_pragmatics, bff_voice, lexical_social_fit, stance, composition.
Each dimension value must be an object with exactly: state, confidence, rationale.
state must be one of: qualified, partially_qualified, research_only, rejected.
confidence must be one of: high, medium, low.
overall_recommendation must use the same four-state set. overall_confidence must use the same confidence set.
strengths, failure_clusters, and evidence_limitations must be arrays of short strings. rationale must be a concise synthesis.
A recommendation of qualified does not mean Assurance-ready and must not erase the dossier's stated limitations.`;
const REPAIR=`Your previous response failed only the required output contract. Reformat the same substantive decisions into the exact JSON schema. Do not strengthen, weaken, reconsider, or change any recommendation, confidence, rationale, strength, failure cluster, or limitation except as necessary to fit the required keys and allowed values. Return JSON only.`;

type Claims={sub:string;session_id:string};
function dec(s:string){return atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4));}
function claims(req:Request):Claims|null{const m=(req.headers.get('authorization')||'').match(/^Bearer\s+([^\s]+)$/i);if(!m)return null;try{const p=m[1].split('.');if(p.length!==3)return null;const c=JSON.parse(dec(p[1]));return typeof c?.sub==='string'&&typeof c?.session_id==='string'?{sub:c.sub,session_id:c.session_id}:null;}catch{return null;}}
function headers(origin:string|null){const h=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store, private, max-age=0','pragma':'no-cache','x-content-type-options':'nosniff','referrer-policy':'no-referrer'});if(origin===ORIGIN){h.set('access-control-allow-origin',ORIGIN);h.set('vary','Origin');h.set('access-control-allow-methods','POST, OPTIONS');h.set('access-control-allow-headers','content-type, authorization');h.set('access-control-max-age','600');}return h;}
function out(origin:string|null,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:headers(origin)});}
async function admin(c:Claims){return sql.begin(async tx=>{const a=await tx`select exists(select 1 from auth.users u join auth.sessions s on s.user_id=u.id where u.id=${c.sub}::uuid and s.id=${c.session_id}::uuid and u.deleted_at is null and (u.banned_until is null or u.banned_until<=pg_catalog.now()) and (s.not_after is null or s.not_after>pg_catalog.now())) ok`;if(!a?.[0]?.ok)return false;await tx`select pg_catalog.set_config('request.jwt.claim.sub',${c.sub},true)`;const r=await tx`select public.is_fg_admin() ok`;return !!r?.[0]?.ok;});}
async function hash(s:string){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');}
function arrStrings(v:any){return Array.isArray(v)&&v.length<=16&&v.every(x=>typeof x==='string'&&x.length>0&&x.length<=500);}
function validate(v:any){if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('output_not_object');const top=['dimension_recommendations','overall_recommendation','overall_confidence','strengths','failure_clusters','evidence_limitations','rationale'];if(Object.keys(v).length!==top.length||Object.keys(v).some(k=>!top.includes(k)))throw new Error('output_keys');const dr=v.dimension_recommendations;if(!dr||typeof dr!=='object'||Array.isArray(dr)||Object.keys(dr).length!==DIMS.length||Object.keys(dr).some(k=>!DIMS.includes(k as any)))throw new Error('dimension_keys');for(const d of DIMS){const x=dr[d];if(!x||typeof x!=='object'||Array.isArray(x)||Object.keys(x).length!==3||!('state'in x)||!('confidence'in x)||!('rationale'in x))throw new Error('dimension_shape');if(!STATES.has(String(x.state)))throw new Error('dimension_state');if(!CONF.has(String(x.confidence)))throw new Error('dimension_confidence');if(typeof x.rationale!=='string'||x.rationale.length<5||x.rationale.length>1800)throw new Error('dimension_rationale');}if(!STATES.has(String(v.overall_recommendation)))throw new Error('overall_state');if(!CONF.has(String(v.overall_confidence)))throw new Error('overall_confidence');if(!arrStrings(v.strengths)||!arrStrings(v.failure_clusters)||!arrStrings(v.evidence_limitations))throw new Error('arrays');if(typeof v.rationale!=='string'||v.rationale.length<10||v.rationale.length>3000)throw new Error('rationale');return v;}
function extractText(p:any){if(typeof p?.output_text==='string'&&p.output_text.trim())return p.output_text.trim();if(Array.isArray(p?.output)){for(const item of p.output){if(Array.isArray(item?.content)){for(const c of item.content){if(typeof c?.text==='string'&&c.text.trim())return c.text.trim();}}}}return '';}
function provider(slot:string){if(slot==='chatgpt')return{key:OPENAI_KEY,model:CHATGPT_MODEL,url:'https://api.openai.com/v1/responses',name:'openai'};return{key:XAI_KEY,model:GROK_MODEL,url:'https://api.x.ai/v1/responses',name:'xai'};}
async function callProvider(slot:string,dossier:any,repairRaw:string|null){const p=provider(slot);if(!p.key)throw new Error(slot+'_credential_missing');const prompt=SYSTEM+'\n\nANONYMOUS FROZEN DOSSIER:\n'+JSON.stringify(dossier)+(repairRaw?'\n\nPREVIOUS RESPONSE TO REFORMAT:\n'+repairRaw+'\n\n'+REPAIR:'');const started=performance.now();const r=await fetch(p.url,{method:'POST',headers:{authorization:`Bearer ${p.key}`,'content-type':'application/json'},body:JSON.stringify({model:p.model,input:prompt,max_output_tokens:5000})});const latency=Math.round(performance.now()-started);let payload:any=null;try{payload=await r.json();}catch{}return{ok:r.ok,status:r.status,payload,latency,text:extractText(payload),provider:p.name,model:p.model};}
async function status(){const q=await sql`select c.id campaign_id,c.status,c.meta_reviews_frozen_at,c.identity_revealed_at,(select count(*)::int from private.tcj_admission_passport_dossiers d where d.campaign_id=c.id and d.dossier_version=${DOSSIER_VERSION}) dossiers,(select count(*)::int from private.tcj_admission_meta_reviews m where m.campaign_id=c.id and m.review_protocol_version=${PROTOCOL}) total,(select count(*)::int from private.tcj_admission_meta_reviews m where m.campaign_id=c.id and m.review_protocol_version=${PROTOCOL} and m.review_state='valid' and m.frozen_at is not null) valid,(select count(*)::int from private.tcj_admission_meta_reviews m where m.campaign_id=c.id and m.review_protocol_version=${PROTOCOL} and m.review_state='pending') pending,(select count(*)::int from private.tcj_admission_meta_reviews m where m.campaign_id=c.id and m.review_protocol_version=${PROTOCOL} and m.review_state='contract_failure') contract_failures,(select count(*)::int from private.tcj_admission_meta_reviews m where m.campaign_id=c.id and m.review_protocol_version=${PROTOCOL} and m.review_state='infrastructure_failure') infrastructure_failures,(select count(*)::int from private.tcj_admission_meta_review_attempts a join private.tcj_admission_meta_reviews m on m.id=a.meta_review_id where m.campaign_id=c.id and m.review_protocol_version=${PROTOCOL}) attempts,(select count(*)::int from private.tcj_admission_campaign_candidates cc join private.tcj_judge_candidates j on j.id=cc.judge_candidate_id where cc.campaign_id=c.id and j.identity_state='sealed') sealed from private.tcj_admission_campaigns c where c.campaign_key=${CAMPAIGN} limit 1`;const r=q[0];if(!r)throw new Error('campaign_missing');return{campaign_state:String(r.status),protocol_version:PROTOCOL,dossiers:Number(r.dossiers||0),total:Number(r.total||0),valid:Number(r.valid||0),pending:Number(r.pending||0),contract_failures:Number(r.contract_failures||0),infrastructure_failures:Number(r.infrastructure_failures||0),attempts:Number(r.attempts||0),meta_reviews_frozen:!!r.meta_reviews_frozen_at,identity_revealed:!!r.identity_revealed_at,identities_sealed:Number(r.sealed||0)===3&&!r.identity_revealed_at,chatgpt_configured:!!OPENAI_KEY,grok_configured:!!XAI_KEY,chatgpt_model:CHATGPT_MODEL,grok_model:GROK_MODEL};}
async function saveAttempt(reviewId:number,index:number,role:string,slot:string,c:any,outcome:string,error:string|null){const sha=c.text?await hash(c.text):null;let parsed:any=null;try{parsed=c.text?JSON.parse(c.text):null;}catch{}await sql`insert into private.tcj_admission_meta_review_attempts(meta_review_id,attempt_index,attempt_role,reviewer_slot,reviewer_provider,reviewer_model,http_status,outcome_class,error_code,raw_output_text,raw_output_sha256,parsed_output,usage,latency_ms) values(${reviewId},${index},${role},${slot},${c.provider},${c.model},${c.status},${outcome},${error},${c.text||null},${sha},${parsed?sql.json(parsed):null},${sql.json(c.payload?.usage||{})},${c.latency}) on conflict(meta_review_id,attempt_index) do nothing`;return parsed;}
async function finalize(review:any,attempt:any){const parsed=validate(attempt.parsed_output);const raw=String(attempt.raw_output_text);const rawSha=await hash(raw);const parsedSha=(await sql`select encode(extensions.digest(${sql.json(parsed)}::jsonb::text,'sha256'),'hex') h`)[0]?.h;await sql`update private.tcj_admission_meta_reviews set reviewer_provider=${attempt.reviewer_provider},reviewer_model=${attempt.reviewer_model},review_state='valid',raw_output_text=${raw},raw_output_sha256=${rawSha},parsed_review=${sql.json(parsed)},parsed_review_sha256=${parsedSha},failure_code=null,failure_meta='{}'::jsonb,frozen_at=pg_catalog.now() where id=${review.id} and review_state='pending' and frozen_at is null`;await sql`select private.tcj_try_freeze_meta_reviews(${review.campaign_id},${PROTOCOL})`;}
async function transportFailure(review:any,c:any){const retryable=c.status===429||c.status>=500;const old=review.failure_meta||{};const n=Number(old.transport_attempts||0)+1;if(retryable&&n<=3){const wait=Math.min(60,Math.pow(2,n)*2);await sql`update private.tcj_admission_meta_reviews set failure_meta=${sql.json({transport_attempts:n,last_http_status:c.status,last_provider_error:c.payload?.error?.message||null,next_retry_seconds:wait})} where id=${review.id} and review_state='pending'`;return{status:'deferred',retry_after_seconds:wait};}await sql`update private.tcj_admission_meta_reviews set review_state='infrastructure_failure',failure_code=${'provider_http_'+c.status},failure_meta=${sql.json({transport_attempts:n,last_http_status:c.status,last_provider_error:c.payload?.error?.message||null})} where id=${review.id} and review_state='pending'`;return{status:'blocked',reason:'provider_or_credential_failure'};}
async function runNext(){const st=await status();if(st.identity_revealed||!st.identities_sealed)return{status:'blocked',reason:'identity_gate',...st};if(st.meta_reviews_frozen)return{status:'complete',...st};if(!st.chatgpt_configured||!st.grok_configured)return{status:'blocked',reason:'reviewer_credentials_missing',...st};if(st.contract_failures>0||st.infrastructure_failures>0)return{status:'blocked',reason:'meta_review_validity_failure',...st};const review:any=(await sql`select m.*,d.dossier,d.dossier_sha256 frozen_dossier_sha from private.tcj_admission_meta_reviews m join private.tcj_admission_passport_dossiers d on d.id=m.dossier_id join private.tcj_admission_campaigns c on c.id=m.campaign_id where c.campaign_key=${CAMPAIGN} and m.review_protocol_version=${PROTOCOL} and m.review_state='pending' and m.frozen_at is null and d.dossier_version=${DOSSIER_VERSION} order by d.opaque_dossier_id,m.reviewer_slot limit 1`)[0];if(!review){await sql`select private.tcj_try_freeze_meta_reviews((select id from private.tcj_admission_campaigns where campaign_key=${CAMPAIGN}),${PROTOCOL})`;return{status:'complete',...(await status())};}if(review.dossier_sha256!==review.frozen_dossier_sha)throw new Error('dossier_hash_link_mismatch');const attempts:any[]=await sql`select * from private.tcj_admission_meta_review_attempts where meta_review_id=${review.id} order by attempt_index`;
 const valid=attempts.find(a=>a.outcome_class==='valid'&&a.parsed_output);if(valid){await finalize(review,valid);return{status:'ok',...(await status())};}
 if(!attempts.length){const c=await callProvider(String(review.reviewer_slot),review.dossier,null);if(!c.ok){const r=await transportFailure(review,c);return{...r,...(await status())};}if(!c.text){await saveAttempt(Number(review.id),1,'primary',String(review.reviewer_slot),c,'empty','empty_response');await sql`update private.tcj_admission_meta_reviews set review_state='contract_failure',failure_code='empty_response',frozen_at=pg_catalog.now() where id=${review.id} and review_state='pending'`;return{status:'blocked',reason:'meta_review_contract_failure',...(await status())};}try{const parsed=JSON.parse(c.text);validate(parsed);await saveAttempt(Number(review.id),1,'primary',String(review.reviewer_slot),c,'valid',null);const a:any=(await sql`select * from private.tcj_admission_meta_review_attempts where meta_review_id=${review.id} and attempt_index=1`)[0];await finalize(review,a);return{status:'ok',...(await status())};}catch(e){await saveAttempt(Number(review.id),1,'primary',String(review.reviewer_slot),c,c.text?'invalid_schema':'invalid_json',e instanceof Error?e.message:'invalid_output');return{status:'needs_repair',...(await status())};}}
 const primary=attempts.find(a=>a.attempt_index===1);const repair=attempts.find(a=>a.attempt_index===2);if(primary&&!repair){const c=await callProvider(String(review.reviewer_slot),review.dossier,String(primary.raw_output_text||''));if(!c.ok){const r=await transportFailure(review,c);return{...r,...(await status())};}try{const parsed=JSON.parse(c.text);validate(parsed);await saveAttempt(Number(review.id),2,'repair',String(review.reviewer_slot),c,'valid',null);const a:any=(await sql`select * from private.tcj_admission_meta_review_attempts where meta_review_id=${review.id} and attempt_index=2`)[0];await finalize(review,a);return{status:'ok',...(await status())};}catch(e){await saveAttempt(Number(review.id),2,'repair',String(review.reviewer_slot),c,c.text?'invalid_schema':'invalid_json',e instanceof Error?e.message:'invalid_output');await sql`update private.tcj_admission_meta_reviews set review_state='contract_failure',failure_code=${e instanceof Error?e.message:'invalid_output'},frozen_at=pg_catalog.now() where id=${review.id} and review_state='pending'`;return{status:'blocked',reason:'meta_review_contract_failure',...(await status())};}}
 return{status:'blocked',reason:'meta_review_recovery_state',...(await status())};}

Deno.serve(async(req:Request)=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return origin===ORIGIN?new Response(null,{status:204,headers:headers(origin)}):out(origin,{error:'forbidden'},403);if(origin!==ORIGIN)return out(origin,{error:'forbidden'},403);if(req.method!=='POST')return out(origin,{error:'method_not_allowed'},405);const c=claims(req);if(!c)return out(origin,{error:'unauthorized'},401);if(!(await admin(c)))return out(origin,{error:'forbidden'},403);let body:any={};try{body=await req.json();}catch{return out(origin,{error:'invalid_json'},400);}try{if(body?.action==='status')return out(origin,{status:'ok',...(await status())});if(body?.action==='run_next')return out(origin,await runNext());return out(origin,{error:'invalid_action'},422);}catch(e){console.error('tcj-admission-meta-review-v1',e);return out(origin,{error:e instanceof Error?e.message:'service_unavailable'},503);}});
