import postgres from 'npm:postgres@3.4.7';

const DB=Deno.env.get('SUPABASE_DB_URL');
const GROQ=Deno.env.get('GROQ_API_KEY');
if(!DB) throw new Error('SUPABASE_DB_URL required');
const sql=postgres(DB,{prepare:false,max:2,idle_timeout:20,connect_timeout:10});
const ORIGIN='https://flipgazine.pages.dev';
const MODEL='qwen/qwen3.6-27b';
const PROFILE='answers-bff-v3-shadow';
const PURPOSE='calibration_shadow_v3';
const CORE='TCJ-CORE-v1';
const GUARDS='TCJ-GUARDS-v1';
const DIMS=['intent','thai_pragmatics','bff_voice','lexical_social_fit','stance','composition'] as const;
const WEIGHTS:Record<string,number>={intent:.20,thai_pragmatics:.25,bff_voice:.20,lexical_social_fit:.15,stance:.10,composition:.10};
const FLAGS=new Set(['over_explained','too_complete','advisor_like','translation_shaped','weak_stance','excessive_hedging','semantic_drift','unnatural_lexical_choice','inappropriate_code_mixing','particle_stance_problem','register_mismatch','generic_cliche','culturally_implausible','forced_humor','forced_camp','overly_slangy','weak_social_grounding','weak_composition','grammatical_not_designed_breaks','weak_final_landing']);

type Claims={sub:string;session_id:string};
function decode64(s:string){return atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4));}
function claims(req:Request):Claims|null{const m=(req.headers.get('authorization')||'').match(/^Bearer\s+([^\s]+)$/i);if(!m)return null;try{const p=m[1].split('.');if(p.length!==3)return null;const c=JSON.parse(decode64(p[1]));return typeof c?.sub==='string'&&typeof c?.session_id==='string'?{sub:c.sub,session_id:c.session_id}:null;}catch{return null;}}
function headers(origin:string|null){const h=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store, private, max-age=0','pragma':'no-cache','x-content-type-options':'nosniff','referrer-policy':'no-referrer'});if(origin===ORIGIN){h.set('access-control-allow-origin',ORIGIN);h.set('vary','Origin');h.set('access-control-allow-methods','POST, OPTIONS');h.set('access-control-allow-headers','content-type, authorization');h.set('access-control-max-age','600');}return h;}
function out(origin:string|null,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:headers(origin)});}
async function admin(c:Claims){return sql.begin(async tx=>{const a=await tx`select exists(select 1 from auth.users u join auth.sessions s on s.user_id=u.id where u.id=${c.sub}::uuid and s.id=${c.session_id}::uuid and u.deleted_at is null and (u.banned_until is null or u.banned_until<=pg_catalog.now()) and (s.not_after is null or s.not_after>pg_catalog.now())) ok`;if(!a?.[0]?.ok)return false;await tx`select pg_catalog.set_config('request.jwt.claim.sub',${c.sub},true)`;const r=await tx`select public.is_fg_admin() ok`;return !!r?.[0]?.ok;});}
function carePrompt(){return `You are the research-only Thai Conversation Judge shadow profile ${PROFILE}. Return exactly one JSON object with keys intent, thai_pragmatics, bff_voice, lexical_social_fit, stance, composition, severity, flags, rationale, confidence. Ratings are integers 1-4. severity is PASS, MINOR, MAJOR, or CRITICAL. flags is an array of allowed diagnostic names. confidence is high, medium, or low. Diagnose only; never rewrite or suggest replacement wording.\n\nThis is a CARE/safety-sensitive case. Safety, clarity and grounded directness override playful house voice. A concise supportive Thai response can still be editor-ready; do not penalize line breaks or brevity merely for being brief. Rating 4 means the exact wording is ready to publish without a meaningful native-editor change. Rating 3 means a meaningful tightening would still be made. Do not invent defects to force intervention.\n\nRate: intent, Thai pragmatic naturalness, appropriate BFF/humane voice, lexical/social fit, stance, composition/delivery. Use semantic_drift only for genuine meaning failure.`;}
function normalPrompt(){return `You are the research-only Thai Conversation Judge shadow profile ${PROFILE}. Return exactly one JSON object with keys intent, thai_pragmatics, bff_voice, lexical_social_fit, stance, composition, severity, flags, rationale, confidence. Ratings are integers 1-4. severity is PASS, MINOR, MAJOR, or CRITICAL. flags may contain only: ${[...FLAGS].join(', ')}. confidence is high, medium, or low. Diagnose only. Never rewrite, correct, continue, regenerate, suggest replacement wording, or propose line breaks.\n\nCRITICAL EDITOR-READY RULE: evaluate the exact Thai wording, not whether you can defend its intended meaning. A 4 means a native editor for this Answers house voice would publish that exact wording unchanged on that dimension. A 3 means it is mostly right but the native editor would still make a meaningful lexical, pragmatic, rhythm, or landing change. Understandable/grammatical is not enough for 4.\n\nANTI-RATIONALIZATION RULE: do not rescue awkward wording by inventing a pun, idiom, joke, cultural convention, deadpan intention, or metaphor that is not actually supported by the text. Never claim a pun exists unless the actual words create it. Short lines, fragments, visible English, ค่ะ, deadpan delivery, and compression earn no points by themselves.\n\nHOUSE-VOICE RULE: semantically correct but generic safe advice can still be weak on bff_voice or composition. Measure whether the response has a sharp, socially legible editorial decision/landing rather than generic assistant wording. Tautology, filler logic, flat endings, or merely competent advice should not receive automatic 4s.\n\nNATIVE-NATURALNESS RULE: if a Thai reader can recover the meaning but a phrase is awkward, tautological, non-idiomatic, or would naturally be tightened, rate the affected dimension 3 or below.\n\nFIGURATIVE/CODE-SWITCH RULE: before flagging semantic_drift, translation_shaped, or inappropriate_code_mixing, actively test plausible Thai ellipsis, metaphor, personification, and ordinary Thai-English borrowing. Nonhuman subjects can be used figuratively; English nouns/phrases can be socially native inside Thai. Penalize only when the intended social meaning genuinely fails, not because a literal reading sounds odd.\n\nRate six dimensions: intent/cause, Thai pragmatic naturalness, BFF conversational/editorial voice, lexical/social fit, stance/decision strength, composition/delivery. Severity: PASS=no meaningful intervention; MINOR=small but real weakness; MAJOR=important criteria substantially missed; CRITICAL=fundamental semantic/safety failure. Rationale must be 2-4 short diagnostic sentences with no replacement wording.`;}
function validate(v:any){if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('output_not_object');const keys=new Set([...DIMS,'severity','flags','rationale','confidence']);if(Object.keys(v).length!==keys.size||Object.keys(v).some(k=>!keys.has(k)))throw new Error('output_keys');const ratings:any={};for(const k of DIMS){if(!Number.isInteger(v[k])||v[k]<1||v[k]>4)throw new Error('bad_'+k);ratings[k]=v[k];}const severity=String(v.severity||'').toUpperCase();if(!['PASS','MINOR','MAJOR','CRITICAL'].includes(severity))throw new Error('bad_severity');if(!Array.isArray(v.flags)||v.flags.some((f:any)=>typeof f!=='string'||!FLAGS.has(f)))throw new Error('bad_flags');const rationale=String(v.rationale||'');if(rationale.length<5||rationale.length>1000)throw new Error('bad_rationale');const confidence=String(v.confidence||'').toLowerCase();if(!['high','medium','low'].includes(confidence))throw new Error('bad_confidence');return{ratings,severity,flags:[...new Set(v.flags)],rationale,confidence};}
async function hash(s:string){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');}
function score(d:any){let t=0;for(const k of DIMS)t+=(((Number(d.ratings[k])-1)/3)*100)*WEIGHTS[k];return Math.round(t*100)/100;}
function verdict(d:any){if(d.severity==='CRITICAL'||d.ratings.intent===1||d.flags.includes('semantic_drift'))return'not_acceptable';const vals=DIMS.map(k=>Number(d.ratings[k]));if(d.severity==='MAJOR'||vals.some(v=>v<=2))return'major_problem';if(d.severity==='MINOR'||vals.some(v=>v===3))return'minor_problem';return'fluent';}
async function judge(question:string,candidate:string,care:boolean){if(!GROQ)throw new Error('groq_secret_missing');const system=care?carePrompt():normalPrompt();const started=performance.now();const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{authorization:`Bearer ${GROQ}`,'content-type':'application/json'},body:JSON.stringify({model:MODEL,temperature:0,max_completion_tokens:600,reasoning_effort:'none',response_format:{type:'json_object'},messages:[{role:'system',content:system},{role:'user',content:JSON.stringify({question_or_scenario:question,candidate_response:candidate})}]})});const elapsed=Math.round(performance.now()-started);let p:any=null;try{p=await r.json();}catch{}if(!r.ok)throw new Error('groq_'+r.status);const content=p?.choices?.[0]?.message?.content;if(typeof content!=='string')throw new Error('missing_content');const raw=JSON.parse(content);const diagnosis=validate(raw);return{diagnosis,raw,usage:p?.usage||null,elapsed,system};}
async function progress(){const rows=await sql`select count(*)::int done from private.batch2_tcj_links where source_id between 'B2-0021' and 'B2-0040' and stage='pre_human' and purpose=${PURPOSE}`;const done=Number(rows[0]?.done||0);return{done,pending:20-done,total:20,status:done>=20?'complete':'ready'};}
async function runNext(){const next=await sql`select s.id,s.question_or_scenario,s.scenario_sha256,s.care_case,d.raw_thai,d.raw_sha256 from private.batch2_sources s join private.batch2_raw_drafts d on d.source_id=s.id join private.batch2_human_reviews h on h.source_id=s.id where s.id between 'B2-0021' and 'B2-0040' and not exists(select 1 from private.batch2_tcj_links l where l.source_id=s.id and l.stage='pre_human' and l.purpose=${PURPOSE}) order by s.id limit 1`;if(!next.length)return{status:'complete',...(await progress())};const x:any=next[0];const j=await judge(String(x.question_or_scenario),String(x.raw_thai),!!x.care_case);const idx=score(j.diagnosis);const v=verdict(j.diagnosis);const method=await hash(JSON.stringify({profile:PROFILE,model:MODEL,temperature:0,weights:WEIGHTS,prompt:j.system}));const rawHash=await hash(JSON.stringify(j.diagnosis));const rows=await sql`insert into private.tcj_evaluation_runs(context_type,context_id,stage,core_version,profile_id,profile_version,care_mode,model_provider,model_name,model_snapshot,temperature,scenario_sha256,candidate_sha256,methodology_sha256,raw_diagnosis,raw_output,raw_diagnosis_sha256,calibrated_diagnosis,calibrated_diagnosis_sha256,calibration_status,audit_index,verdict,guard_set_version,prompt_tokens,completion_tokens,latency_ms,purpose) values('batch2',${x.id},'pre_human',${CORE},'answers-bff','v3-shadow',${!!x.care_case},'groq',${MODEL},null,0,${x.scenario_sha256},${x.raw_sha256},${method},${JSON.stringify(j.diagnosis)}::jsonb,${JSON.stringify(j.raw)}::jsonb,${rawHash},${JSON.stringify(j.diagnosis)}::jsonb,${rawHash},'shadow_prompt_v3',${idx},${v},${GUARDS},${j.usage?.prompt_tokens??null},${j.usage?.completion_tokens??null},${j.elapsed},${PURPOSE}) returning id`;const runId=Number(rows[0].id);await sql`insert into private.batch2_tcj_links(source_id,stage,tcj_run_id,purpose) values(${x.id},'pre_human',${runId},${PURPOSE})`;return{status:'ok',source_id:x.id,tcj_run_id:runId,verdict:v,audit_index:idx,...(await progress())};}

Deno.serve(async(req:Request)=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return origin===ORIGIN?new Response(null,{status:204,headers:headers(origin)}):out(origin,{error:'forbidden'},403);if(origin!==ORIGIN)return out(origin,{error:'forbidden'},403);if(req.method!=='POST')return out(origin,{error:'method_not_allowed'},405);const c=claims(req);if(!c)return out(origin,{error:'unauthorized'},401);if(!(await admin(c)))return out(origin,{error:'forbidden'},403);let body:any={};try{body=await req.json();}catch{return out(origin,{error:'invalid_json'},400);}try{if(body?.action==='status')return out(origin,{profile:PROFILE,...(await progress())});if(body?.action==='run_next')return out(origin,{profile:PROFILE,...(await runNext())});return out(origin,{error:'invalid_action'},422);}catch(e){console.error('tcj shadow',e);return out(origin,{error:e instanceof Error?e.message:'service_unavailable'},503);}});
