import postgres from 'npm:postgres@3.4.7';

const DB=Deno.env.get('SUPABASE_DB_URL');
if(!DB) throw new Error('SUPABASE_DB_URL required');
const sql=postgres(DB,{prepare:false,max:2,idle_timeout:20,connect_timeout:10});
const ORIGIN='https://flipgazine.pages.dev';
const CAMPAIGN='TCJ-JUDGE-ADMISSION-2026Q3-v1.2';
const PACK='TCJ-JUDGE-ROBUSTNESS-PERTURB-2026Q3-v1';
const PREV_PACK='TCJ-JUDGE-ROBUSTNESS-2026Q3-v1';
const EFFECTS=new Set(['descriptive','invariant','degrade','preserve_acceptability','contract_resistance','context_sensitive']);

type Claims={sub:string;session_id:string};
function dec(s:string){return atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4));}
function claims(req:Request):Claims|null{const m=(req.headers.get('authorization')||'').match(/^Bearer\s+([^\s]+)$/i);if(!m)return null;try{const p=m[1].split('.');if(p.length!==3)return null;const c=JSON.parse(dec(p[1]));return typeof c?.sub==='string'&&typeof c?.session_id==='string'?{sub:c.sub,session_id:c.session_id}:null;}catch{return null;}}
function headers(origin:string|null){const h=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store, private, max-age=0','pragma':'no-cache','x-content-type-options':'nosniff','referrer-policy':'no-referrer'});if(origin===ORIGIN){h.set('access-control-allow-origin',ORIGIN);h.set('vary','Origin');h.set('access-control-allow-methods','POST, OPTIONS');h.set('access-control-allow-headers','content-type, authorization');h.set('access-control-max-age','600');}return h;}
function out(origin:string|null,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:headers(origin)});}
async function admin(c:Claims){return sql.begin(async tx=>{const a=await tx`select exists(select 1 from auth.users u join auth.sessions s on s.user_id=u.id where u.id=${c.sub}::uuid and s.id=${c.session_id}::uuid and u.deleted_at is null and (u.banned_until is null or u.banned_until<=pg_catalog.now()) and (s.not_after is null or s.not_after>pg_catalog.now())) ok`;if(!a?.[0]?.ok)return false;await tx`select pg_catalog.set_config('request.jwt.claim.sub',${c.sub},true)`;const r=await tx`select public.is_fg_admin() ok`;return !!r?.[0]?.ok;});}
async function hash(s:string){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');}

async function packRow(){const q=await sql`select p.id,p.status,p.case_count,p.total_cells,p.manifest_sha256,p.frozen_at,p.completed_at,p.campaign_id,c.identity_revealed_at,
  exists(select 1 from private.tcj_admission_robustness_packs x where x.campaign_id=p.campaign_id and x.pack_key=${PREV_PACK} and x.status='complete') prev_complete,
  (select count(*)::int from private.tcj_admission_campaign_candidates cc join private.tcj_judge_candidates j on j.id=cc.judge_candidate_id where cc.campaign_id=p.campaign_id and j.identity_state='sealed') sealed
  from private.tcj_admission_robustness_packs p join private.tcj_admission_campaigns c on c.id=p.campaign_id where p.pack_key=${PACK} and c.campaign_key=${CAMPAIGN} limit 1`;if(!q[0])throw new Error('perturbation_pack_missing');return q[0];}
async function status(){const p:any=await packRow();const c=await sql`select count(*)::int total,
 count(*) filter(where review_state='needs_review')::int needs_review,
 count(*) filter(where review_state='approved')::int approved,
 count(*) filter(where review_state='rejected')::int rejected,
 count(*) filter(where survival_state='pass')::int survival_pass,
 count(*) filter(where survival_state='fail')::int survival_fail,
 count(*) filter(where frozen_at is not null)::int frozen_cases
 from private.tcj_admission_robustness_cases where pack_id=${p.id}`;
 const fam=await sql`select family,count(*)::int n,count(*) filter(where review_state='approved')::int approved,count(*) filter(where survival_state='pass')::int survival_pass from private.tcj_admission_robustness_cases where pack_id=${p.id} group by family order by family`;
 const x:any=c[0]||{};return{pack_key:PACK,state:String(p.status),case_count:Number(x.total||0),total_cells:Number(p.total_cells||0),needs_review:Number(x.needs_review||0),approved:Number(x.approved||0),rejected:Number(x.rejected||0),survival_pass:Number(x.survival_pass||0),survival_fail:Number(x.survival_fail||0),frozen_cases:Number(x.frozen_cases||0),freeze_ready:String(p.status)==='draft'&&Number(x.total||0)===33&&Number(x.approved||0)===33&&Number(x.rejected||0)===0&&Number(x.survival_pass||0)===33&&Number(x.survival_fail||0)===0,manifest_sha256:p.manifest_sha256||null,frozen_at:p.frozen_at||null,previous_robustness_complete:!!p.prev_complete,identities_sealed:Number(p.sealed||0)===3&&!p.identity_revealed_at,families:fam.map((r:any)=>({family:String(r.family),cases:Number(r.n||0),approved:Number(r.approved||0),survival_pass:Number(r.survival_pass||0)}))};}
async function nextCase(){const p:any=await packRow();if(String(p.status)!=='draft')return{status:'not_reviewable',...(await status())};const q=await sql`select c.id,c.case_key,c.family,c.scenario_text,c.candidate_text,c.expected_effect,c.perturbation_spec,c.review_state,c.survival_state,c.survival_note,c.pair_key,c.variant_role,
 b.item_key baseline_item_key,b.scenario_text baseline_scenario,b.candidate_text baseline_candidate
 from private.tcj_admission_robustness_cases c join private.tcj_evidence_items b on b.id=c.source_evidence_item_id
 where c.pack_id=${p.id} and c.review_state<>'approved'
 order by case c.family
   when 'position_order' then 1 when 'response_labels_ids' then 2 when 'verbosity_superficial' then 3 when 'politeness_artifact' then 4
   when 'prompt_complexity' then 5 when 'thai_english_script' then 6 when 'unicode_formatting' then 7 when 'candidate_prompt_injection' then 8
   when 'metaphor_personification' then 9 when 'particles_omission' then 10 when 'relationship_register' then 11 else 99 end,c.case_key limit 1`;
 if(!q[0])return{status:'all_reviewed',...(await status())};const r:any=q[0];const prog=await status();return{status:'case',case:{id:Number(r.id),case_key:String(r.case_key),family:String(r.family),baseline_item_key:String(r.baseline_item_key),baseline_scenario:String(r.baseline_scenario),baseline_candidate:String(r.baseline_candidate),scenario_text:String(r.scenario_text),candidate_text:String(r.candidate_text),expected_effect:String(r.expected_effect),perturbation_spec:r.perturbation_spec||{},review_state:String(r.review_state),survival_state:String(r.survival_state||'unchecked'),survival_note:r.survival_note||null,pair_key:r.pair_key||null,variant_role:String(r.variant_role)},progress:prog};}
async function saveApprove(c:Claims,body:any){const p:any=await packRow();if(String(p.status)!=='draft')throw new Error('pack_not_draft');if(p.identity_revealed_at)throw new Error('identity_already_revealed');const caseId=Number(body?.case_id);if(!Number.isInteger(caseId)||caseId<=0)throw new Error('bad_case_id');const scenario=String(body?.scenario_text??'').trim();const candidate=String(body?.candidate_text??'').trim();const effect=String(body?.expected_effect??'');const note=String(body?.note??'').trim().slice(0,1200);if(!scenario||!candidate||scenario.length>6000||candidate.length>6000)throw new Error('bad_text');if(!EFFECTS.has(effect))throw new Error('bad_expected_effect');const row:any=(await sql`select id,scenario_text,candidate_text,expected_effect,perturbation_spec,review_state from private.tcj_admission_robustness_cases where id=${caseId} and pack_id=${p.id} limit 1`)[0];if(!row)throw new Error('case_not_found');const gate:any=(await sql`select private.tcj_perturbation_survival_eval(${caseId},${scenario},${candidate},${effect},${sql.json(row.perturbation_spec||{})}) v`)[0]?.v||{};if(!gate.ok){const reasons=Array.isArray(gate.reasons)?gate.reasons.join(', '):'unknown';throw new Error('perturbation_survival_failed:'+reasons);}const rev=Number((await sql`select coalesce(max(revision_no),0)+1 n from private.tcj_admission_robustness_case_reviews where case_id=${caseId}`)[0]?.n||1);const decision=(row.scenario_text===scenario&&row.candidate_text===candidate&&row.expected_effect===effect)?'approve':'edit_approve';const sh=await hash(scenario),ch=await hash(candidate);await sql.begin(async tx=>{await tx`insert into private.tcj_admission_robustness_case_reviews(pack_id,case_id,revision_no,decision,scenario_before,candidate_before,scenario_after,candidate_after,expected_effect_before,expected_effect_after,perturbation_spec_before,perturbation_spec_after,note,reviewed_by,actor_kind) values(${p.id},${caseId},${rev},${decision},${String(row.scenario_text)},${String(row.candidate_text)},${scenario},${candidate},${String(row.expected_effect)},${effect},${sql.json(row.perturbation_spec||{})},${sql.json(row.perturbation_spec||{})},${note||null},${c.sub}::uuid,'human')`;await tx`update private.tcj_admission_robustness_cases set scenario_text=${scenario},candidate_text=${candidate},scenario_sha256=${sh},candidate_sha256=${ch},expected_effect=${effect},review_state='approved',reviewed_at=pg_catalog.now(),reviewed_by=${c.sub}::uuid where id=${caseId} and pack_id=${p.id}`;});return await nextCase();}
async function freeze(c:Claims){const p:any=await packRow();if(String(p.status)==='frozen')return{status:'already_frozen',...(await status())};if(String(p.status)!=='draft')throw new Error('pack_not_draft');if(p.identity_revealed_at||Number(p.sealed||0)!==3)throw new Error('identity_gate');const st:any=await status();if(!st.freeze_ready)throw new Error('native_review_or_survival_incomplete');const rows=await sql`select case_key,family,scenario_text,candidate_text,expected_effect,perturbation_spec,survival_state from private.tcj_admission_robustness_cases where pack_id=${p.id} order by case_key`;if(rows.some((r:any)=>String(r.survival_state)!=='pass'))throw new Error('survival_gate_failed');const parts:string[]=[];for(const r of rows){const sh=await hash(String(r.scenario_text)),ch=await hash(String(r.candidate_text)),ph=await hash(JSON.stringify(r.perturbation_spec||{}));parts.push(`${r.case_key}:${sh}:${ch}:${r.family}:${r.expected_effect}:${ph}`);}const manifest=await hash(parts.join('|'));await sql.begin(async tx=>{await tx`update private.tcj_admission_robustness_cases set scenario_sha256=encode(digest(scenario_text,'sha256'),'hex'),candidate_sha256=encode(digest(candidate_text,'sha256'),'hex'),frozen_at=coalesce(frozen_at,pg_catalog.now()) where pack_id=${p.id} and review_state='approved' and survival_state='pass'`;await tx`update private.tcj_admission_robustness_packs set status='frozen',manifest_sha256=${manifest},frozen_at=coalesce(frozen_at,pg_catalog.now()),case_count=33,total_cells=99 where id=${p.id} and status='draft'`;});return{status:'frozen',...(await status())};}

Deno.serve(async(req:Request)=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return origin===ORIGIN?new Response(null,{status:204,headers:headers(origin)}):out(origin,{error:'forbidden'},403);if(origin!==ORIGIN)return out(origin,{error:'forbidden'},403);if(req.method!=='POST')return out(origin,{error:'method_not_allowed'},405);const c=claims(req);if(!c)return out(origin,{error:'unauthorized'},401);if(!(await admin(c)))return out(origin,{error:'forbidden'},403);let body:any={};try{body=await req.json();}catch{return out(origin,{error:'invalid_json'},400);}try{if(body?.action==='status')return out(origin,{status:'ok',...(await status())});if(body?.action==='next_case')return out(origin,await nextCase());if(body?.action==='approve')return out(origin,await saveApprove(c,body));if(body?.action==='freeze')return out(origin,await freeze(c));return out(origin,{error:'invalid_action'},422);}catch(e){console.error('tcj-admission-perturbation-review-v2',e);const m=e instanceof Error?e.message:'service_unavailable';const code=m.startsWith('perturbation_survival_failed:')?422:503;return out(origin,{error:m},code);}});
