import postgres from 'npm:postgres@3.4.7';
import {buildSystemPrompt,validateDiagnosis,detectCare,DIMS,TCJ_CORE_VERSION,TCJ_CORE_BLOB_SHA,type Diagnosis} from './canonical-contract.ts';

const DB=Deno.env.get('SUPABASE_DB_URL');const GROQ=Deno.env.get('GROQ_API_KEY');if(!DB)throw new Error('SUPABASE_DB_URL required');
const sql=postgres(DB,{prepare:false,max:2,idle_timeout:20,connect_timeout:10});
const ORIGIN='https://flipgazine.pages.dev';
const CAMPAIGN='TCJ-JUDGE-ADMISSION-2026Q3-v1.2';
const PACK='TCJ-JUDGE-ROBUSTNESS-2026Q3-v1';
const PROTOCOL='TCJ-JUDGE-ROBUSTNESS-v1';
const PROMPT_VERSION='TCJ-ANSWERS-BFF-v2@TCJ-CORE-v1';
const SUMMARY_VERSION='TCJ-ROBUSTNESS-SUMMARY-v1';
const STAGE_B_PROTOCOL='TCJ-JUDGE-ADMISSION-STAGE-B-v1.1';
const TEMP=0,MAX_TOKENS=500;
const REPAIR_SUFFIX='\nYour previous output failed the required JSON contract. Return only one valid JSON object with the required keys and allowed values. Do not add rewrite or suggestion content.';

type Claims={sub:string;session_id:string};
function dec(s:string){return atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4));}
function claims(req:Request):Claims|null{const m=(req.headers.get('authorization')||'').match(/^Bearer\s+([^\s]+)$/i);if(!m)return null;try{const p=m[1].split('.');if(p.length!==3)return null;const c=JSON.parse(dec(p[1]));return typeof c?.sub==='string'&&typeof c?.session_id==='string'?{sub:c.sub,session_id:c.session_id}:null;}catch{return null;}}
function headers(origin:string|null){const h=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store, private, max-age=0','pragma':'no-cache','x-content-type-options':'nosniff','referrer-policy':'no-referrer'});if(origin===ORIGIN){h.set('access-control-allow-origin',ORIGIN);h.set('vary','Origin');h.set('access-control-allow-methods','POST, OPTIONS');h.set('access-control-allow-headers','content-type, authorization');h.set('access-control-max-age','600');}return h;}
function out(origin:string|null,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:headers(origin)});}
async function admin(c:Claims){return sql.begin(async tx=>{const a=await tx`select exists(select 1 from auth.users u join auth.sessions s on s.user_id=u.id where u.id=${c.sub}::uuid and s.id=${c.session_id}::uuid and u.deleted_at is null and (u.banned_until is null or u.banned_until<=pg_catalog.now()) and (s.not_after is null or s.not_after>pg_catalog.now())) ok`;if(!a?.[0]?.ok)return false;await tx`select pg_catalog.set_config('request.jwt.claim.sub',${c.sub},true)`;const r=await tx`select public.is_fg_admin() ok`;return !!r?.[0]?.ok;});}
async function hash(s:string){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');}
function effortFor(model:string){if(model==='qwen/qwen3.6-27b')return'none';if(model==='openai/gpt-oss-20b'||model==='openai/gpt-oss-120b')return'low';throw new Error('unsupported_model_adapter');}
function verdict(d:any){const r=d.ratings||d;if(String(d.severity||'').toUpperCase()==='CRITICAL'||Number(r.intent)===1||(Array.isArray(d.flags)&&d.flags.includes('semantic_drift')))return'not_acceptable';const v=DIMS.map(k=>Number(r[k]));if(String(d.severity||'').toUpperCase()==='MAJOR'||v.some(x=>x<=2))return'major_problem';if(String(d.severity||'').toUpperCase()==='MINOR'||v.some(x=>x===3))return'minor_problem';return'fluent';}
async function methodologyHash(repair:boolean,effort:string,care:boolean,family:string){return hash(JSON.stringify({protocol:PROTOCOL,pack:PACK,prompt_version:PROMPT_VERSION,canonical_core_version:TCJ_CORE_VERSION,canonical_core_blob_sha:TCJ_CORE_BLOB_SHA,care_mode:care,family,system_prompt:buildSystemPrompt(care)+(repair?REPAIR_SUFFIX:''),temperature:TEMP,max_completion_tokens:MAX_TOKENS,reasoning_effort:effort,response_format:'json_object',user_payload_keys:['question_or_scenario','candidate_response']}));}

async function progress(){const q=await sql`select p.id pack_id,p.status pack_status,p.case_count,p.total_cells,p.frozen_at,p.completed_at,c.status campaign_state,c.stage_b_frozen_at,c.identity_revealed_at,(select count(*)::int from private.tcj_admission_robustness_cases x where x.pack_id=p.id and x.family='repeat_identical') repeat_cases,(select count(*)::int from private.tcj_admission_robustness_cases x where x.pack_id=p.id and x.family='self_preference') self_cases,(select count(*)::int from private.tcj_admission_robustness_judgments j where j.pack_id=p.id and j.protocol_version=${PROTOCOL}) valid,(select count(*)::int from private.tcj_admission_robustness_failures f where f.pack_id=p.id and f.protocol_version=${PROTOCOL} and f.evidence_state='terminal' and f.failure_class='generation_contract') terminal_contract,(select count(*)::int from private.tcj_admission_robustness_failures f where f.pack_id=p.id and f.protocol_version=${PROTOCOL} and f.evidence_state='active' and f.failure_class='transient_provider') transient_failures,(select count(*)::int from private.tcj_admission_robustness_failures f where f.pack_id=p.id and f.protocol_version=${PROTOCOL} and f.evidence_state='active' and f.failure_class in ('generation_contract','infrastructure')) blockers,(select count(*)::int from private.tcj_admission_robustness_summaries s where s.pack_id=p.id and s.summary_version=${SUMMARY_VERSION}) summaries from private.tcj_admission_robustness_packs p join private.tcj_admission_campaigns c on c.id=p.campaign_id where p.pack_key=${PACK} and c.campaign_key=${CAMPAIGN} limit 1`;const r=q[0];if(!r)throw new Error('robustness_pack_missing');const valid=Number(r.valid||0),terminal=Number(r.terminal_contract||0),done=valid+terminal,total=Number(r.total_cells||0);return{pack_key:PACK,pack_state:String(r.pack_status),campaign_state:String(r.campaign_state),protocol_version:PROTOCOL,stage_b_frozen:!!r.stage_b_frozen_at,identity_revealed:!!r.identity_revealed_at,evidence_class:'preliminary_calibration_derived',case_count:Number(r.case_count||0),repeat_cases:Number(r.repeat_cases||0),self_preference_cases:Number(r.self_cases||0),total,done,valid,terminal_contract:terminal,pending:Math.max(0,total-done),transient_failures:Number(r.transient_failures||0),blockers:Number(r.blockers||0),summaries:Number(r.summaries||0),frozen_at:r.frozen_at,completed_at:r.completed_at};}

async function recordFailure(packId:number,caseId:number,judgeId:number,httpStatus:number|null,errorCode:string,failureClass:'transient_provider'|'generation_contract'|'infrastructure',state:'active'|'terminal',meta:any,retryable:boolean){const old=await sql`select attempt_count from private.tcj_admission_robustness_failures where pack_id=${packId} and case_id=${caseId} and judge_candidate_id=${judgeId} and protocol_version=${PROTOCOL} limit 1`;const attempt=Number(old[0]?.attempt_count||0)+1,delay=Math.min(120,5*Math.pow(2,Math.min(attempt-1,5))),retryIso=retryable?new Date(Date.now()+delay*1000).toISOString():null;await sql`insert into private.tcj_admission_robustness_failures(pack_id,case_id,judge_candidate_id,protocol_version,prompt_version,attempt_count,last_http_status,last_error_code,failure_class,evidence_state,first_failed_at,last_failed_at,next_retry_at,resolved_at,error_meta) values(${packId},${caseId},${judgeId},${PROTOCOL},${PROMPT_VERSION},${attempt},${httpStatus},${errorCode},${failureClass},${state},pg_catalog.now(),pg_catalog.now(),${retryIso}::timestamptz,null,${sql.json(meta||{})}) on conflict(pack_id,case_id,judge_candidate_id,protocol_version) do update set attempt_count=${attempt},last_http_status=${httpStatus},last_error_code=${errorCode},failure_class=${failureClass},evidence_state=${state},last_failed_at=pg_catalog.now(),next_retry_at=${retryIso}::timestamptz,resolved_at=null,error_meta=${sql.json(meta||{})}`;return delay;}
async function markResolved(packId:number,caseId:number,judgeId:number){await sql`update private.tcj_admission_robustness_failures set resolved_at=pg_catalog.now(),next_retry_at=null,evidence_state='resolved' where pack_id=${packId} and case_id=${caseId} and judge_candidate_id=${judgeId} and protocol_version=${PROTOCOL} and evidence_state<>'invalidated'`;}
async function providerCall(model:string,scenario:string,candidate:string,care:boolean,repair:boolean){if(!GROQ)throw new Error('groq_secret_missing');const effort=effortFor(model),system=buildSystemPrompt(care)+(repair?REPAIR_SUFFIX:'');const started=performance.now();const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{authorization:`Bearer ${GROQ}`,'content-type':'application/json'},body:JSON.stringify({model,temperature:TEMP,max_completion_tokens:MAX_TOKENS,reasoning_effort:effort,response_format:{type:'json_object'},stream:false,messages:[{role:'system',content:system},{role:'user',content:JSON.stringify({question_or_scenario:scenario,candidate_response:candidate})}]})});const latency=Math.round(performance.now()-started);let payload:any=null;try{payload=await r.json();}catch{}return{ok:r.ok,status:r.status,payload,latency,effort,care,repair};}
async function insertAttempt(a:any){const raw=String(a.content||''),sha=raw?await hash(raw):null;let parsed:any=null;try{parsed=raw?JSON.parse(raw):null;}catch{}await sql`insert into private.tcj_admission_robustness_attempts(pack_id,case_id,judge_candidate_id,protocol_version,prompt_version,attempt_index,attempt_role,http_status,finish_reason,outcome_class,error_code,raw_output_text,raw_output_sha256,parsed_output,generation_settings,usage,latency_ms,evidence_eligible) values(${a.packId},${a.caseId},${a.judgeId},${PROTOCOL},${PROMPT_VERSION},${a.attemptIndex},${a.role},${a.httpStatus},${a.finishReason||null},${a.outcome},${a.errorCode||null},${raw||null},${sha},${parsed?sql.json(parsed):null},${sql.json(a.settings||{})},${sql.json(a.usage||{})},${a.latency||null},true) on conflict(pack_id,case_id,judge_candidate_id,protocol_version,attempt_index) do nothing`;return parsed;}
async function persistJudgment(args:any){const diagnosis:Diagnosis=args.diagnosis,raw=args.raw,dsha=await hash(JSON.stringify(diagnosis)),msha=await methodologyHash(!!args.repairUsed,String(args.effort),!!args.care,String(args.family)),opaque='RJ-'+crypto.randomUUID().replaceAll('-','').slice(0,14).toUpperCase(),usage=args.usage||{},settings={temperature:TEMP,max_completion_tokens:MAX_TOKENS,reasoning_effort:String(args.effort),response_format:'json_object',care_mode:!!args.care,repair_used:!!args.repairUsed,first_pass_error:args.firstError||null,robustness_family:String(args.family),canonical_core_version:TCJ_CORE_VERSION,canonical_core_blob_sha:TCJ_CORE_BLOB_SHA,recovered_from_preserved_attempt:!!args.recovered},usageOut={prompt_tokens:Number(usage?.prompt_tokens||0),completion_tokens:Number(usage?.completion_tokens||0),total_tokens:Number(usage?.total_tokens||0),reasoning_tokens:Number(usage?.completion_tokens_details?.reasoning_tokens||0),finish_reason:String(args.finishReason||'')||null};await sql`insert into private.tcj_admission_robustness_judgments(pack_id,case_id,judge_candidate_id,opaque_judgment_id,protocol_version,prompt_version,methodology_sha256,diagnosis,diagnosis_sha256,raw_output,predicted_verdict,generation_settings,usage,latency_ms) values(${args.packId},${args.caseId},${args.judgeId},${opaque},${PROTOCOL},${PROMPT_VERSION},${msha},${sql.json(diagnosis)},${dsha},${sql.json(raw)},${verdict(diagnosis)},${sql.json(settings)},${sql.json(usageOut)},${Number(args.latency||0)}) on conflict(pack_id,case_id,judge_candidate_id) do nothing`;await markResolved(args.packId,args.caseId,args.judgeId);}
async function classify(call:any,packId:number,caseId:number,judgeId:number,attemptIndex:number,role:'primary'|'repair',family:string){const choice=call.payload?.choices?.[0]||{},finish=String(choice?.finish_reason||''),content=String(choice?.message?.content||'').trim(),usage=call.payload?.usage||{},settings={temperature:TEMP,max_completion_tokens:MAX_TOKENS,reasoning_effort:call.effort,response_format:'json_object',care_mode:call.care,repair:role==='repair',robustness_family:family,canonical_core_blob_sha:TCJ_CORE_BLOB_SHA};if(finish==='length'){await insertAttempt({packId,caseId,judgeId,attemptIndex,role,httpStatus:200,finishReason:finish,outcome:'length',errorCode:'generation_length_limit',content,settings,usage,latency:call.latency});return{kind:'terminal',error:'generation_length_limit'};}if(!content){await insertAttempt({packId,caseId,judgeId,attemptIndex,role,httpStatus:200,finishReason:finish,outcome:'empty',errorCode:'empty_generation',content,settings,usage,latency:call.latency});return{kind:'terminal',error:'empty_generation'};}try{const raw=JSON.parse(content),diagnosis=validateDiagnosis(raw);await insertAttempt({packId,caseId,judgeId,attemptIndex,role,httpStatus:200,finishReason:finish,outcome:'valid',content,settings,usage,latency:call.latency});return{kind:'valid',raw,diagnosis};}catch(e){const code=e instanceof Error?e.message:'invalid_json';await insertAttempt({packId,caseId,judgeId,attemptIndex,role,httpStatus:200,finishReason:finish,outcome:'invalid_schema',errorCode:code,content,settings,usage,latency:call.latency});return{kind:'invalid',error:code};}}
async function providerFailure(call:any,packId:number,caseId:number,judgeId:number){const hs=Number(call.status||0),retryable=hs===429||hs>=500,code=`groq_${hs||'error'}`;if(retryable){const delay=await recordFailure(packId,caseId,judgeId,hs,code,'transient_provider','active',{provider_error_type:call.payload?.error?.type||null,provider_error_message:String(call.payload?.error?.message||'').slice(0,500)},true);return{status:'deferred',retry_after_seconds:delay};}await recordFailure(packId,caseId,judgeId,hs,code,'infrastructure','active',{provider_error_type:call.payload?.error?.type||null,provider_error_message:String(call.payload?.error?.message||'').slice(0,500),classification:'provider_or_adapter_contract_requires_diagnosis'},false);return{status:'blocked',reason:'provider_or_adapter_contract_failure'};}

function totalScore(d:any){return DIMS.reduce((s,k)=>s+Number((d.ratings||d)[k]||0),0);}
async function finalizePack(packId:number,campaignId:number){const candidates=await sql`select j.id from private.tcj_admission_campaign_candidates cc join private.tcj_judge_candidates j on j.id=cc.judge_candidate_id where cc.campaign_id=${campaignId} order by j.id`;for(const c of candidates){const judgeId=Number(c.id);
  const repeats=await sql`select rc.case_key,rc.source_evidence_item_id,rj.diagnosis,rj.diagnosis_sha256,bj.diagnosis baseline from private.tcj_admission_robustness_cases rc left join private.tcj_admission_robustness_judgments rj on rj.pack_id=rc.pack_id and rj.case_id=rc.id and rj.judge_candidate_id=${judgeId} and rj.protocol_version=${PROTOCOL} left join private.tcj_admission_stage_b_judgments bj on bj.campaign_id=${campaignId} and bj.evidence_item_id=rc.source_evidence_item_id and bj.judge_candidate_id=${judgeId} and bj.protocol_version=${STAGE_B_PROTOCOL} where rc.pack_id=${packId} and rc.family='repeat_identical' order by rc.case_key`;
  const repeatTerminal=await sql`select count(*)::int n from private.tcj_admission_robustness_failures f join private.tcj_admission_robustness_cases rc on rc.id=f.case_id where f.pack_id=${packId} and f.judge_candidate_id=${judgeId} and f.protocol_version=${PROTOCOL} and f.evidence_state='terminal' and rc.family='repeat_identical'`;
  const rm:any={case_count:36,valid:0,terminal:Number(repeatTerminal[0]?.n||0),severity_exact:0,verdict_exact:0,dimensions:{}};for(const k of DIMS)rm.dimensions[k]={cases:0,exact:0,within_one:0,abs_delta_sum:0,mean_abs_delta:null};for(const row of repeats){if(!row.diagnosis||!row.baseline)continue;rm.valid++;if(String(row.diagnosis.severity)===String(row.baseline.severity))rm.severity_exact++;if(verdict(row.diagnosis)===verdict(row.baseline))rm.verdict_exact++;for(const k of DIMS){const a=Number(row.diagnosis.ratings?.[k]),b=Number(row.baseline.ratings?.[k]),m=rm.dimensions[k],d=Math.abs(a-b);m.cases++;if(a===b)m.exact++;if(d<=1)m.within_one++;m.abs_delta_sum+=d;}}for(const k of DIMS){const m=rm.dimensions[k];if(m.cases)m.mean_abs_delta=Math.round((m.abs_delta_sum/m.cases)*1000)/1000;}rm.severity_agreement=rm.valid?rm.severity_exact/rm.valid:null;rm.verdict_agreement=rm.valid?rm.verdict_exact/rm.valid:null;

  const selfs=await sql`select rc.case_key,rc.source_generator_judge_id,rc.source_meta,rj.diagnosis,rj.diagnosis_sha256 from private.tcj_admission_robustness_cases rc left join private.tcj_admission_robustness_judgments rj on rj.pack_id=rc.pack_id and rj.case_id=rc.id and rj.judge_candidate_id=${judgeId} and rj.protocol_version=${PROTOCOL} where rc.pack_id=${packId} and rc.family='self_preference' order by rc.case_key`;
  const selfTerminal=await sql`select count(*)::int n from private.tcj_admission_robustness_failures f join private.tcj_admission_robustness_cases rc on rc.id=f.case_id where f.pack_id=${packId} and f.judge_candidate_id=${judgeId} and f.protocol_version=${PROTOCOL} and f.evidence_state='terminal' and rc.family='self_preference'`;
  const sm:any={case_count:30,valid:0,terminal:Number(selfTerminal[0]?.n||0),relation:{self:{cases:0,total_score_sum:0,mean_total_score:null,verdicts:{}},other:{cases:0,total_score_sum:0,mean_total_score:null,verdicts:{}}},by_human_decision:{},descriptive_only:true};for(const row of selfs){if(!row.diagnosis)continue;sm.valid++;const relation=Number(row.source_generator_judge_id)===judgeId?'self':'other',decision=String(row.source_meta?.human_decision||'UNKNOWN'),score=totalScore(row.diagnosis),v=verdict(row.diagnosis),bucket=sm.relation[relation];bucket.cases++;bucket.total_score_sum+=score;bucket.verdicts[v]=(bucket.verdicts[v]||0)+1;if(!sm.by_human_decision[decision])sm.by_human_decision[decision]={self:{cases:0,total_score_sum:0,mean_total_score:null},other:{cases:0,total_score_sum:0,mean_total_score:null}};const db=sm.by_human_decision[decision][relation];db.cases++;db.total_score_sum+=score;}for(const rel of ['self','other']){const b=sm.relation[rel];if(b.cases)b.mean_total_score=Math.round((b.total_score_sum/b.cases)*1000)/1000;}sm.bias_by_human_decision={};for(const [decision,x] of Object.entries<any>(sm.by_human_decision)){for(const rel of ['self','other']){const b=x[rel];if(b.cases)b.mean_total_score=Math.round((b.total_score_sum/b.cases)*1000)/1000;}sm.bias_by_human_decision[decision]=(x.self.cases&&x.other.cases)?Math.round((x.self.mean_total_score-x.other.mean_total_score)*1000)/1000:null;}

  const attempts=await sql`select count(*) filter(where attempt_role='primary' and outcome_class='valid')::int primary_valid,count(*) filter(where attempt_role='repair')::int repairs,count(*) filter(where attempt_role='repair' and outcome_class='valid')::int repair_success,count(*) filter(where outcome_class='valid' and jsonb_typeof(parsed_output->'rationale')<>'string')::int rationale_shape_normalized from private.tcj_admission_robustness_attempts where pack_id=${packId} and judge_candidate_id=${judgeId} and protocol_version=${PROTOCOL} and evidence_eligible=true`;
  const transient=await sql`select coalesce(sum(attempt_count),0)::int n from private.tcj_admission_robustness_failures where pack_id=${packId} and judge_candidate_id=${judgeId} and protocol_version=${PROTOCOL} and failure_class='transient_provider'`;
  const terminal=await sql`select count(*)::int n from private.tcj_admission_robustness_failures where pack_id=${packId} and judge_candidate_id=${judgeId} and protocol_version=${PROTOCOL} and evidence_state='terminal'`;
  const a=attempts[0]||{},reliability={structured_output_primary_valid:Number(a.primary_valid||0),repair_attempts:Number(a.repairs||0),repair_success:Number(a.repair_success||0),terminal_contract_failures:Number(terminal[0]?.n||0),provider_failure_attempts:Number(transient[0]?.n||0),rationale_shape_normalized:Number(a.rationale_shape_normalized||0),preliminary_only:true,qualification_sufficient:false,assurance_eligible:false};
  const cases=await sql`select rc.case_key,rj.diagnosis_sha256 from private.tcj_admission_robustness_cases rc left join private.tcj_admission_robustness_judgments rj on rj.pack_id=rc.pack_id and rj.case_id=rc.id and rj.judge_candidate_id=${judgeId} and rj.protocol_version=${PROTOCOL} where rc.pack_id=${packId} order by rc.case_key`;const parts:string[]=[];for(const row of cases){if(row.diagnosis_sha256)parts.push(`${row.case_key}:V:${row.diagnosis_sha256}`);else{const at=(await sql`select raw_output_sha256,error_code from private.tcj_admission_robustness_attempts where pack_id=${packId} and case_id=(select id from private.tcj_admission_robustness_cases where pack_id=${packId} and case_key=${row.case_key}) and judge_candidate_id=${judgeId} and protocol_version=${PROTOCOL} order by attempt_index desc limit 1`)[0];parts.push(`${row.case_key}:T:${at?.raw_output_sha256||at?.error_code||'contract_failure'}`);}}const manifest=await hash(parts.join('|'));await sql`insert into private.tcj_admission_robustness_summaries(pack_id,judge_candidate_id,summary_version,repeat_metrics,self_preference_metrics,reliability_metrics,evidence_manifest_sha256,frozen_at) values(${packId},${judgeId},${SUMMARY_VERSION},${sql.json(rm)},${sql.json(sm)},${sql.json(reliability)},${manifest},pg_catalog.now()) on conflict(pack_id,judge_candidate_id) do nothing`;
 }
 await sql`update private.tcj_admission_robustness_packs set status='complete',completed_at=coalesce(completed_at,pg_catalog.now()) where id=${packId}`;
}

async function runNext(){const p=await progress();if(p.identity_revealed)return{status:'blocked',reason:'identity_already_revealed',...p};if(!p.stage_b_frozen)return{status:'blocked',reason:'stage_b_not_frozen',...p};if(p.blockers>0)return{status:'blocked',reason:'adapter_or_infrastructure_validity_failure',...p};if(p.pack_state==='complete'||p.pending<=0)return{status:'complete',...p};const pack=(await sql`select p.id,p.status,p.campaign_id from private.tcj_admission_robustness_packs p join private.tcj_admission_campaigns c on c.id=p.campaign_id where p.pack_key=${PACK} and c.campaign_key=${CAMPAIGN} limit 1`)[0];if(!pack)throw new Error('robustness_pack_missing');if(!['frozen','running'].includes(String(pack.status)))return{status:'blocked',reason:'robustness_pack_state',...p};if(pack.status==='frozen')await sql`update private.tcj_admission_robustness_packs set status='running' where id=${pack.id} and status='frozen'`;
 const next=await sql`select rc.id case_id,rc.family,rc.scenario_text,rc.candidate_text,j.id judge_candidate_id,j.provider,j.model_name from private.tcj_admission_robustness_cases rc join private.tcj_admission_robustness_packs p on p.id=rc.pack_id join private.tcj_admission_campaign_candidates cc on cc.campaign_id=p.campaign_id join private.tcj_judge_candidates j on j.id=cc.judge_candidate_id left join private.tcj_admission_robustness_failures f on f.pack_id=p.id and f.case_id=rc.id and f.judge_candidate_id=j.id and f.protocol_version=${PROTOCOL} where p.id=${pack.id} and j.identity_state='sealed' and not exists(select 1 from private.tcj_admission_robustness_judgments x where x.pack_id=p.id and x.case_id=rc.id and x.judge_candidate_id=j.id and x.protocol_version=${PROTOCOL}) and not exists(select 1 from private.tcj_admission_robustness_failures t where t.pack_id=p.id and t.case_id=rc.id and t.judge_candidate_id=j.id and t.protocol_version=${PROTOCOL} and t.evidence_state='terminal') and (f.id is null or f.evidence_state='resolved' or (f.failure_class='transient_provider' and f.evidence_state='active' and f.next_retry_at<=pg_catalog.now())) order by case when rc.family='repeat_identical' then 0 else 1 end,rc.case_key,j.id limit 1`;
 if(!next.length){const now=await progress();if(now.blockers>0)return{status:'blocked',reason:'adapter_or_infrastructure_validity_failure',...now};if(now.pending<=0){await finalizePack(Number(pack.id),Number(pack.campaign_id));return{status:'complete',...(await progress())};}const w=await sql`select greatest(1,ceil(extract(epoch from (min(next_retry_at)-pg_catalog.now()))))::int seconds from private.tcj_admission_robustness_failures where pack_id=${pack.id} and protocol_version=${PROTOCOL} and evidence_state='active' and failure_class='transient_provider' and next_retry_at>pg_catalog.now()`;return{status:'waiting_retry',retry_after_seconds:Number(w[0]?.seconds||5),...now};}
 const x:any=next[0],care=detectCare(String(x.scenario_text));if(x.provider!=='groq'){await recordFailure(Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id),null,'unsupported_provider','infrastructure','active',{classification:'adapter_validity'},false);return{status:'blocked',reason:'unsupported_provider',...(await progress())};}
 const prior=await sql`select attempt_index,attempt_role,outcome_class,error_code,parsed_output,generation_settings,usage,latency_ms,finish_reason from private.tcj_admission_robustness_attempts where pack_id=${pack.id} and case_id=${x.case_id} and judge_candidate_id=${x.judge_candidate_id} and protocol_version=${PROTOCOL} and evidence_eligible=true order by attempt_index`;let firstError:string|null=null;
 const validPrior=prior.find((a:any)=>a.outcome_class==='valid');if(validPrior?.parsed_output){const raw=validPrior.parsed_output,diagnosis=validateDiagnosis(raw),gs=validPrior.generation_settings||{},repair=String(validPrior.attempt_role)==='repair';await persistJudgment({packId:Number(pack.id),caseId:Number(x.case_id),judgeId:Number(x.judge_candidate_id),diagnosis,raw,effort:String(gs.reasoning_effort||effortFor(String(x.model_name))),care:!!gs.care_mode,repairUsed:repair,firstError:repair?String(prior[0]?.error_code||prior[0]?.outcome_class||'invalid_schema'):null,family:String(x.family),usage:validPrior.usage||{},finishReason:validPrior.finish_reason||'recovered',latency:Number(validPrior.latency_ms||0),recovered:true});const after=await progress();if(after.pending<=0){await finalizePack(Number(pack.id),Number(pack.campaign_id));return{status:'complete',...(await progress())};}return{status:'ok',...after};}
 if(prior.length&&prior[0].outcome_class!=='valid')firstError=String(prior[0].error_code||prior[0].outcome_class);
 if(!prior.length){const call=await providerCall(String(x.model_name),String(x.scenario_text),String(x.candidate_text),care,false);if(!call.ok){const r=await providerFailure(call,Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id));return{...r,...(await progress())};}const cls:any=await classify(call,Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id),1,'primary',String(x.family));if(cls.kind==='valid'){await persistJudgment({packId:Number(pack.id),caseId:Number(x.case_id),judgeId:Number(x.judge_candidate_id),diagnosis:cls.diagnosis,raw:cls.raw,effort:call.effort,care,repairUsed:false,firstError:null,family:String(x.family),usage:call.payload?.usage||{},finishReason:call.payload?.choices?.[0]?.finish_reason||'',latency:call.latency,recovered:false});const after=await progress();if(after.pending<=0){await finalizePack(Number(pack.id),Number(pack.campaign_id));return{status:'complete',...(await progress())};}return{status:'ok',...after};}if(cls.kind==='terminal'){await recordFailure(Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id),200,cls.error,'generation_contract','terminal',{stage:'primary',care_mode:care,policy:'terminal_no_resample'},false);return{status:'cell_terminal',...(await progress())};}firstError=cls.error;}
 const repairPrior=prior.find((a:any)=>Number(a.attempt_index)===2);if(repairPrior){if(repairPrior.outcome_class==='valid'&&repairPrior.parsed_output){const raw=repairPrior.parsed_output,diagnosis=validateDiagnosis(raw),gs=repairPrior.generation_settings||{};await persistJudgment({packId:Number(pack.id),caseId:Number(x.case_id),judgeId:Number(x.judge_candidate_id),diagnosis,raw,effort:String(gs.reasoning_effort||effortFor(String(x.model_name))),care:!!gs.care_mode,repairUsed:true,firstError,family:String(x.family),usage:repairPrior.usage||{},finishReason:repairPrior.finish_reason||'recovered',latency:Number(repairPrior.latency_ms||0),recovered:true});return{status:'ok',...(await progress())};}await recordFailure(Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id),200,String(repairPrior.error_code||'repair_invalid'),'generation_contract','terminal',{stage:'repair',first_pass_error:firstError,policy:'one_repair_then_terminal'},false);return{status:'cell_terminal',...(await progress())};}
 const repair=await providerCall(String(x.model_name),String(x.scenario_text),String(x.candidate_text),care,true);if(!repair.ok){const r=await providerFailure(repair,Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id));return{...r,...(await progress())};}const rc:any=await classify(repair,Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id),2,'repair',String(x.family));if(rc.kind==='valid'){await persistJudgment({packId:Number(pack.id),caseId:Number(x.case_id),judgeId:Number(x.judge_candidate_id),diagnosis:rc.diagnosis,raw:rc.raw,effort:repair.effort,care,repairUsed:true,firstError,family:String(x.family),usage:repair.payload?.usage||{},finishReason:repair.payload?.choices?.[0]?.finish_reason||'',latency:repair.latency,recovered:false});const after=await progress();if(after.pending<=0){await finalizePack(Number(pack.id),Number(pack.campaign_id));return{status:'complete',...(await progress())};}return{status:'ok',...after};}await recordFailure(Number(pack.id),Number(x.case_id),Number(x.judge_candidate_id),200,rc.error,'generation_contract','terminal',{stage:'repair',first_pass_error:firstError,policy:'one_repair_then_terminal'},false);return{status:'cell_terminal',...(await progress())};}

Deno.serve(async(req:Request)=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return origin===ORIGIN?new Response(null,{status:204,headers:headers(origin)}):out(origin,{error:'forbidden'},403);if(origin!==ORIGIN)return out(origin,{error:'forbidden'},403);if(req.method!=='POST')return out(origin,{error:'method_not_allowed'},405);const c=claims(req);if(!c)return out(origin,{error:'unauthorized'},401);if(!(await admin(c)))return out(origin,{error:'forbidden'},403);let body:any={};try{body=await req.json();}catch{return out(origin,{error:'invalid_json'},400);}try{if(body?.action==='status')return out(origin,{status:'ok',...(await progress())});if(body?.action==='run_next')return out(origin,await runNext());return out(origin,{error:'invalid_action'},422);}catch(e){console.error('tcj-admission-robustness-v1',e);return out(origin,{error:e instanceof Error?e.message:'service_unavailable'},503);}});
