const MIN_POOL=2, MAX_BROAD_WIDEN=12;
const INTENTS=[
 {id:'choice',re:/(?:หรือ|อันไหน|ไหนดี|เลือกอะไร|เลือกอัน|which|which one|\bor\b)/i},
 {id:'should',re:/(?:ควร|ดีไหม|ดีมั้ย|ได้ไหม|ได้มั้ย|เอาไหม|เอามั้ย|ไหม\??$|มั้ย\??$|should|worth it|can i|do i)/i},
 {id:'desire',re:/(?:อยาก|want|feel like)/i},
 {id:'timing',re:/(?:เมื่อไหร่|ตอนไหน|ตอนนี้|วันนี้|พรุ่งนี้|คืนนี้|กี่โมง|วันธรรมดา|เช้า|บ่าย|when|now|today|tomorrow|tonight|later|weekday|morning|afternoon)/i},
 {id:'reaction',re:/(?:ทำไง|ทำยังไง|เอาไง|ตอบยังไง|ควรทำยังไง|what should i do|how should i|how do i)/i},
 {id:'feeling',re:/(?:รู้สึก|เครียด|เหนื่อย|เหงา|เบื่อ|เศร้า|เซ็ง|คิดมาก|feel|stressed|tired|lonely|bored|sad|overwhelmed)/i}
];
const CARE=[/(suicid|self[- ]?harm|want to die|ไม่อยากอยู่|ทำร้ายตัวเอง)/i,/(หมอ|โรงพยาบาล|ยาอะไร|กินยา|หยุดยา|เลือด|หายใจไม่ออก|ปวดหน้าอก|doctor|hospital|medicine|dose|chest pain)/i,/(โดนทำร้าย|ถูกทำร้าย|ไม่ปลอดภัย|ขู่|abuse|unsafe|violence|threat)/i];
function normalize(text:string){let s=String(text??'');try{s=s.normalize('NFKC')}catch{}return s.toLowerCase().replace(/[“”„‟«»]/g,'"').replace(/[‘’‚‛]/g,"'").replace(/[‐‑‒–—―]/g,'-').replace(/[\u200B-\u200D\uFEFF]/g,'').replace(/[!?！？,，;；:：()\[\]{}<>\/\\|*_~`]+/g,' ').replace(/\.{2,}/g,' ').replace(/\s+/g,' ').trim()}
function escRe(s:string){return String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function hasLatin(s:string){return /[a-z0-9]/i.test(s)}
function aliasSpans(text:string,alias:string){const out:any[]=[];let i=0;if(!alias)return out;if(hasLatin(alias)){const re=new RegExp('(^|[^a-z0-9])('+escRe(alias)+')(?=$|[^a-z0-9])','ig');let m;while((m=re.exec(text))){const start=m.index+m[1].length;out.push({start,end:start+m[2].length});if(re.lastIndex===m.index)re.lastIndex++}return out}while((i=text.indexOf(alias,i))>=0){out.push({start:i,end:i+alias.length});i+=Math.max(1,alias.length)}return out}
function uniq<T>(a:T[]){return [...new Set(a)]}
function buildAliasTable(dictionary:any){const out:any[]=[];(dictionary.concepts||[]).forEach((c:any)=>{(c.aliases||[]).forEach((a:string)=>out.push({alias:normalize(a),id:c.id,kind:c.kind,topics:c.topics||[],helpers:c.helpers||[]}));(c.typos||[]).forEach((a:string)=>out.push({alias:normalize(a),id:c.id,kind:c.kind,topics:c.topics||[],helpers:c.helpers||[]}))});out.sort((a,b)=>b.alias.length-a.alias.length||a.alias.localeCompare(b.alias));return out}
function parseQuestion(question:string,dictionary:any){const normalized=normalize(question),table=buildAliasTable(dictionary),candidates:any[]=[],hits:any[]=[];table.forEach(x=>aliasSpans(normalized,x.alias).forEach(sp=>candidates.push({...x,...sp,len:sp.end-sp.start})));candidates.sort((a,b)=>b.len-a.len||a.start-b.start||a.alias.localeCompare(b.alias));const occupied:any[]=[],supportOccupied:any[]=[];candidates.forEach(x=>{const lane=x.kind==='support'?supportOccupied:occupied;const overlap=lane.some(s=>x.start<s.end&&x.end>s.start);if(!overlap){hits.push(x);lane.push({start:x.start,end:x.end})}});hits.sort((a,b)=>a.start-b.start||b.len-a.len);let focus:string[]=[],slang:string[]=[],support:string[]=[],topics:string[]=[],topicExplicit:string[]=[],helpers:string[]=[];hits.forEach(h=>{if(h.kind==='focus')focus.push(h.id);else if(h.kind==='slang')slang.push(h.id);else if(h.kind==='support')support.push(h.id);else if(h.kind==='topic'){topics.push(h.id);topicExplicit.push(h.id)};(h.topics||[]).forEach((t:string)=>topics.push(t));(h.helpers||[]).forEach((x:string)=>helpers.push(x))});focus=uniq(focus);if(focus.includes('colleague')&&focus.includes('friend')){const p=normalized.replace(/เพื่อนร่วมงาน/g,'');if(!p.includes('เพื่อน')&&!/\b(?:friend|friends|bestie)\b/i.test(p))focus=focus.filter(x=>x!=='friend')}if(focus.includes('work')&&(focus.includes('colleague')||focus.includes('hobby'))){const p=normalized.replace(/เพื่อนร่วมงาน|งานอดิเรก|งานฝีมือ/g,'');if(!p.includes('งาน')&&!/\b(?:work|job)\b/i.test(p))focus=focus.filter(x=>x!=='work')}if(focus.includes('reply')&&normalized.includes('คำตอบ')){const p=normalized.replace(/คำตอบ/g,'');if(!p.includes('ตอบ')&&!/\brepl(?:y|ied|ying)\b/i.test(p))focus=focus.filter(x=>x!=='reply')}const intents:string[]=[];INTENTS.forEach(x=>{if(x.re.test(normalized))intents.push(x.id)});if(intents.some(x=>['choice','should','reaction'].includes(x)))helpers.push('decision');if(intents.includes('timing'))helpers.push('timing');return{normalized,focus,slang:uniq(slang),support:uniq(support),topics:uniq(topics),topicExplicit:uniq(topicExplicit),helpers:uniq(helpers),intents:uniq(intents)}}
function intersect(lists:number[][]){if(!lists.length)return[];const rest=lists.slice(1).map(a=>new Set(a));return (lists[0]||[]).filter(x=>rest.every(s=>s.has(x)))}
function union(lists:number[][]){return uniq(lists.flat()).sort((a,b)=>a-b)}
function idsFor(map:any,keys:string[]){return(keys||[]).map(k=>(map&&map[k])||[])}
function tier(name:string,ids:number[],meta:any={}){return{name,ids:uniq(ids).sort((a,b)=>a-b),meta}}
function buildTiers(p:any,index:any){const semantic=p.focus.length?p.focus:p.slang,excluded=new Set<number>(index.generic||[]);Object.values(index.support||{}).forEach((a:any)=>a.forEach((id:number)=>excluded.add(id)));const strip=(lists:number[][])=>lists.map(a=>(a||[]).filter(id=>!excluded.has(id)));const focusLists=strip(idsFor(index.focus,semantic)),topicLists=strip(idsFor(index.topics,p.topics)),helperLists=strip(idsFor(index.helpers,p.helpers)),tiers:any[]=[];if(semantic.length){tiers.push(tier('all-focus',intersect(focusLists)));if(semantic.length>=2){const counts:any={},threshold=Math.max(1,semantic.length-1),near:number[]=[];semantic.forEach((f:string)=>((index.focus||{})[f]||[]).forEach((id:number)=>{if(!excluded.has(id))counts[id]=(counts[id]||0)+1}));Object.keys(counts).forEach(id=>{if(counts[id]>=threshold)near.push(+id)});tiers.push(tier('near-focus',near))}tiers.push(tier('any-focus',union(focusLists)))}if(p.topics.length){tiers.push(tier('all-topics',intersect(topicLists)));tiers.push(tier('any-topic',union(topicLists)))}if(p.helpers.length){tiers.push(tier('all-helpers',intersect(helperLists)));tiers.push(tier('any-helper',union(helperLists)))}tiers.push(tier('generic',(index.generic||[]).slice()));const seen=new Set<string>();return tiers.filter(t=>{const k=t.name+'|'+t.ids.join(',');if(!t.ids.length||seen.has(k))return false;seen.add(k);return true})}
function selectTier(tiers:any[]){const isFocus=(n:string)=>['all-focus','near-focus','any-focus'].includes(n);const contains=(hay:number[],need:number[])=>{const s=new Set(hay);return need.every(x=>s.has(x))};let seed:number[]|null=null,seedIndex=-1;for(let z=0;z<tiers.length;z++)if(isFocus(tiers[z].name)&&tiers[z].ids.length){seed=tiers[z].ids;seedIndex=z;break}for(let i=0;i<tiers.length;i++){const t=tiers[i];if(t.name==='generic'||t.ids.length<MIN_POOL)continue;if(seed&&!contains(t.ids,seed))continue;if(isFocus(t.name)||t.ids.length<=MAX_BROAD_WIDEN)return{tier:t}}if(seed)return{tier:tiers[seedIndex]};for(const t of tiers)if(t.name!=='generic'&&t.ids.length)return{tier:t};return{tier:tiers[tiers.length-1]||tier('generic',[])}}
function resolve(question:string,dictionary:any,index:any){const p=parseQuestion(question,dictionary),tiers=buildTiers(p,index),chosen=selectTier(tiers);const supportKeys=uniq([...(p.focus||[]),...(p.slang||[]),...(p.support||[])]),supportPool=union(idsFor(index.support,supportKeys));const hasSubject=!!(p.focus.length||p.slang.length||p.topicExplicit.length);let chosenTier=chosen.tier;if(supportPool.length&&(chosenTier.name==='generic'||!hasSubject))chosenTier=tier('support',supportPool);const chosenSet=new Set<number>(chosenTier.ids||[]),supportAdds=supportPool.filter(id=>!chosenSet.has(id));const mixed=chosenTier.name==='generic'?(chosenTier.ids||[]).slice():uniq([...(chosenTier.ids||[]),...supportAdds]).sort((a,b)=>a-b);let eligible=mixed.slice();if(chosenTier.name!=='generic'){const baseSet=new Set(eligible),u=(index.generic||[]).filter((id:number)=>!baseSet.has(id)).slice(0,2);eligible=eligible.concat(u)}return{parsed:p,selectedTier:chosenTier.name,eligible}}
function careIntercept(q:string){return CARE.some(r=>r.test(q))}
function shaHex(text:string){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)).then(b=>Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join(''))}
function buildIndex(answers:any[]){const out:any={focus:{},support:{},topics:{},helpers:{},generic:[]};for(const a of answers){for(const k of a.focus||[])(out.focus[k]||(out.focus[k]=[])).push(a.answer_id);for(const k of a.support||[])(out.support[k]||(out.support[k]=[])).push(a.answer_id);for(const k of a.topics||[])(out.topics[k]||(out.topics[k]=[])).push(a.answer_id);for(const k of a.helpers||[])(out.helpers[k]||(out.helpers[k]=[])).push(a.answer_id);if(a.is_universal)out.generic.push(a.answer_id)}for(const lane of ['focus','support','topics','helpers'])for(const k of Object.keys(out[lane]))out[lane][k].sort((a:number,b:number)=>a-b);out.generic.sort((a:number,b:number)=>a-b);return out}
function mergeDictionary(base:any,stages:any[]){const d=structuredClone(base),by=new Map<string,any>((d.concepts||[]).map((c:any)=>[c.id,c]));const newConcepts:any[]=[];for(const st of stages){const delta=st.dictionary_delta||{};for(const c0 of delta.concepts||[]){const c=structuredClone(c0);if(by.has(c.id))throw new Error('new_concept_exists:'+c.id);c.aliases=uniq(c.aliases||[]);c.typos=uniq(c.typos||[]);c.topics=uniq(c.topics||[]);c.helpers=uniq(c.helpers||[]);if(!['focus','slang','bridge','support','topic'].includes(c.kind))throw new Error('bad_new_concept_kind:'+c.id);by.set(c.id,c);newConcepts.push(c)}for(const p of delta.aliases||[]){const c=by.get(p.concept_id);if(!c)throw new Error('alias_target_missing:'+p.concept_id);c.aliases=uniq([...(c.aliases||[]),...((p.values||[]).filter((x:any)=>typeof x==='string'&&x.trim()))])}for(const p of delta.typos||[]){const c=by.get(p.concept_id);if(!c)throw new Error('typo_target_missing:'+p.concept_id);c.typos=uniq([...(c.typos||[]),...((p.values||[]).filter((x:any)=>typeof x==='string'&&x.trim()))])}}
 newConcepts.sort((a,b)=>a.id.localeCompare(b.id));d.concepts=[...(base.concepts||[]).map((c:any)=>by.get(c.id)),...newConcepts];return d}
function surfaceMap(dictionary:any){const owners=new Map<string,Set<string>>(),bad:string[]=[];for(const c of dictionary.concepts||[]){for(const raw of [...(c.aliases||[]),...(c.typos||[])]){const n=normalize(raw);if(!n){bad.push(String(raw));continue}if(!owners.has(n))owners.set(n,new Set());owners.get(n)!.add(c.id)}}return{owners,bad}}
export {normalize,resolve,careIntercept,shaHex,buildIndex,mergeDictionary,surfaceMap,uniq};