create table if not exists private.tcj_qualification_protocols (
  id bigint generated by default as identity primary key,
  protocol_key text not null unique,
  evidence_set_id bigint not null unique references private.tcj_evidence_sets(id),
  profile_id text not null,
  protocol_version text not null,
  status text not null default 'draft_review' check (status in ('draft_review','bank_frozen','running','complete','retired','compromised')),
  item_target integer not null check (item_target>0),
  candidate_target integer not null check (candidate_target>0),
  threshold_spec jsonb not null,
  threshold_sha256 text not null check (length(threshold_sha256)=64),
  threshold_frozen_at timestamptz not null,
  human_manifest_sha256 text,
  human_review_frozen_at timestamptz,
  bank_frozen_at timestamptz,
  frozen_by uuid,
  run_started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default pg_catalog.now(),
  check (jsonb_typeof(threshold_spec)='object'),
  check (human_manifest_sha256 is null or length(human_manifest_sha256)=64)
);

create table if not exists private.tcj_qualification_case_designs (
  id bigint generated by default as identity primary key,
  protocol_id bigint not null references private.tcj_qualification_protocols(id),
  evidence_item_id bigint not null unique references private.tcj_evidence_items(id),
  opaque_review_id text not null unique,
  review_order integer not null,
  primary_dimension text not null check (primary_dimension in ('intent','thai_pragmatics','bff_voice','lexical_social_fit','stance','composition')),
  design_class text not null,
  construction_note text not null,
  draft_scenario_text text not null,
  draft_candidate_text text not null,
  draft_scenario_sha256 text not null check (length(draft_scenario_sha256)=64),
  draft_candidate_sha256 text not null check (length(draft_candidate_sha256)=64),
  construction_provenance text not null,
  created_at timestamptz not null default pg_catalog.now(),
  unique(protocol_id,review_order)
);

create table if not exists private.tcj_qualification_human_reviews (
  id bigint generated by default as identity primary key,
  protocol_id bigint not null references private.tcj_qualification_protocols(id),
  evidence_item_id bigint not null unique references private.tcj_evidence_items(id),
  reviewer_user_id uuid not null,
  review_state text not null default 'draft' check (review_state in ('draft','frozen','voided')),
  final_scenario_text text not null,
  final_candidate_text text not null,
  scenario_sha256 text not null check (length(scenario_sha256)=64),
  candidate_sha256 text not null check (length(candidate_sha256)=64),
  ratings jsonb not null,
  severity text not null check (severity in ('PASS','MINOR','MAJOR','CRITICAL')),
  flags text[] not null default '{}'::text[],
  confidence text not null check (confidence in ('high','medium','low')),
  human_ambiguous boolean not null default false,
  review_note text,
  revision_no integer not null default 1 check (revision_no>0),
  review_sha256 text not null check (length(review_sha256)=64),
  frozen_at timestamptz,
  created_at timestamptz not null default pg_catalog.now(),
  updated_at timestamptz not null default pg_catalog.now(),
  check (jsonb_typeof(ratings)='object')
);

alter table private.tcj_qualification_protocols enable row level security;
alter table private.tcj_qualification_case_designs enable row level security;
alter table private.tcj_qualification_human_reviews enable row level security;
revoke all on private.tcj_qualification_protocols from anon, authenticated;
revoke all on private.tcj_qualification_case_designs from anon, authenticated;
revoke all on private.tcj_qualification_human_reviews from anon, authenticated;
revoke all on sequence private.tcj_qualification_protocols_id_seq from anon, authenticated;
revoke all on sequence private.tcj_qualification_case_designs_id_seq from anon, authenticated;
revoke all on sequence private.tcj_qualification_human_reviews_id_seq from anon, authenticated;

create index if not exists tcj_qualification_design_protocol_order_idx on private.tcj_qualification_case_designs(protocol_id,review_order);
create index if not exists tcj_qualification_reviews_protocol_state_idx on private.tcj_qualification_human_reviews(protocol_id,review_state);

create or replace function private.tcj_qualification_ratings_valid(v jsonb)
returns boolean
language sql
immutable
set search_path=pg_catalog
as $$
  select jsonb_typeof(v)='object'
    and (select count(*) from jsonb_object_keys(v))=6
    and v ?& array['intent','thai_pragmatics','bff_voice','lexical_social_fit','stance','composition']
    and (v->>'intent') ~ '^[1-4]$'
    and (v->>'thai_pragmatics') ~ '^[1-4]$'
    and (v->>'bff_voice') ~ '^[1-4]$'
    and (v->>'lexical_social_fit') ~ '^[1-4]$'
    and (v->>'stance') ~ '^[1-4]$'
    and (v->>'composition') ~ '^[1-4]$';
$$;
revoke all on function private.tcj_qualification_ratings_valid(jsonb) from public,anon,authenticated;

alter table private.tcj_qualification_human_reviews
  drop constraint if exists tcj_qualification_human_reviews_ratings_valid_check;
alter table private.tcj_qualification_human_reviews
  add constraint tcj_qualification_human_reviews_ratings_valid_check check (private.tcj_qualification_ratings_valid(ratings));

create or replace function private.tcj_qualification_review_hash(
  p_scenario text,p_candidate text,p_ratings jsonb,p_severity text,p_flags text[],p_confidence text,p_ambiguous boolean,p_note text
) returns text
language sql
immutable
set search_path=pg_catalog,extensions
as $$
  select encode(extensions.digest(jsonb_build_object(
    'scenario',p_scenario,
    'candidate',p_candidate,
    'ratings',p_ratings,
    'severity',p_severity,
    'flags',to_jsonb(coalesce(p_flags,'{}'::text[])),
    'confidence',p_confidence,
    'human_ambiguous',p_ambiguous,
    'note',coalesce(p_note,'')
  )::text,'sha256'),'hex');
$$;
revoke all on function private.tcj_qualification_review_hash(text,text,jsonb,text,text[],text,boolean,text) from public,anon,authenticated;

create or replace function private.tcj_prevent_frozen_qualification_review_mutation()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,private
as $$
begin
  if old.review_state='frozen' or old.frozen_at is not null then
    raise exception 'frozen_qualification_review_immutable';
  end if;
  return case when tg_op='DELETE' then old else new end;
end;
$$;
revoke all on function private.tcj_prevent_frozen_qualification_review_mutation() from public,anon,authenticated;
drop trigger if exists tcj_qualification_review_immutable_trg on private.tcj_qualification_human_reviews;
create trigger tcj_qualification_review_immutable_trg
before update or delete on private.tcj_qualification_human_reviews
for each row execute function private.tcj_prevent_frozen_qualification_review_mutation();

create or replace function private.tcj_prevent_frozen_qualification_item_mutation()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,private
as $$
declare v_status text; v_key text;
begin
  select s.status,s.set_key into v_status,v_key from private.tcj_evidence_sets s where s.id=old.evidence_set_id;
  if v_key='TCJ-JUDGE-QUALIFICATION-v1' and v_status in ('frozen','active','retired','compromised') then
    raise exception 'frozen_qualification_item_immutable';
  end if;
  return case when tg_op='DELETE' then old else new end;
end;
$$;
revoke all on function private.tcj_prevent_frozen_qualification_item_mutation() from public,anon,authenticated;
drop trigger if exists tcj_qualification_item_immutable_trg on private.tcj_evidence_items;
create trigger tcj_qualification_item_immutable_trg
before update or delete on private.tcj_evidence_items
for each row execute function private.tcj_prevent_frozen_qualification_item_mutation();

create or replace function private.tcj_prevent_frozen_qualification_protocol_mutation()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,private
as $$
begin
  if old.threshold_frozen_at is not null and (
       new.threshold_spec is distinct from old.threshold_spec
    or new.threshold_sha256 is distinct from old.threshold_sha256
    or new.threshold_frozen_at is distinct from old.threshold_frozen_at
  ) then
    raise exception 'qualification_thresholds_immutable';
  end if;
  if old.status in ('bank_frozen','running','complete','retired','compromised') and (
       new.evidence_set_id is distinct from old.evidence_set_id
    or new.profile_id is distinct from old.profile_id
    or new.protocol_version is distinct from old.protocol_version
    or new.item_target is distinct from old.item_target
    or new.candidate_target is distinct from old.candidate_target
    or new.human_manifest_sha256 is distinct from old.human_manifest_sha256
    or new.bank_frozen_at is distinct from old.bank_frozen_at
  ) then
    raise exception 'frozen_qualification_protocol_immutable';
  end if;
  return new;
end;
$$;
revoke all on function private.tcj_prevent_frozen_qualification_protocol_mutation() from public,anon,authenticated;
drop trigger if exists tcj_qualification_protocol_immutable_trg on private.tcj_qualification_protocols;
create trigger tcj_qualification_protocol_immutable_trg
before update on private.tcj_qualification_protocols
for each row execute function private.tcj_prevent_frozen_qualification_protocol_mutation();

with s as (
  select id from private.tcj_evidence_sets where set_key='TCJ-JUDGE-QUALIFICATION-v1' and bank='qualification'
), t as (
  select jsonb_build_object(
    'threshold_version','TCJ-JUDGE-QUALIFICATION-THRESHOLDS-v1',
    'rating_scale',jsonb_build_object('min',1,'max',4,'material_error','absolute_error_greater_than_1'),
    'dimensions',jsonb_build_array('intent','thai_pragmatics','bff_voice','lexical_social_fit','stance','composition'),
    'qualified_dimension',jsonb_build_object(
      'min_valid_cells',47,
      'max_mae',0.50,
      'min_within_one_cells',45,
      'max_extreme_reversals',0,
      'primary_target_case_count',8,
      'min_primary_target_within_one_cells',7
    ),
    'partially_qualified_dimension',jsonb_build_object(
      'min_valid_cells',46,
      'max_mae',0.75,
      'min_within_one_cells',43,
      'max_extreme_reversals',1,
      'primary_target_case_count',8,
      'min_primary_target_within_one_cells',6
    ),
    'global_authority_gates',jsonb_build_object(
      'max_false_fluent_on_human_major_or_critical',0,
      'max_terminal_generation_contract_failures',0,
      'candidate_cells_expected',48
    ),
    'notes',jsonb_build_array(
      'Exact-match rate is reported but is not by itself a production-authority gate.',
      'A material rating error is more than one point on the 1-4 human scale.',
      'Extreme reversal means human<=2 and judge=4, or human=4 and judge<=2.',
      'Thresholds are frozen before any candidate judge sees qualification items.'
    )
  ) spec
)
insert into private.tcj_qualification_protocols(protocol_key,evidence_set_id,profile_id,protocol_version,status,item_target,candidate_target,threshold_spec,threshold_sha256,threshold_frozen_at)
select 'TCJ-JUDGE-QUALIFICATION-2026Q3-v1',s.id,'answers-bff-v2','TCJ-JUDGE-QUALIFICATION-v1','draft_review',48,3,t.spec,encode(extensions.digest(t.spec::text,'sha256'),'hex'),pg_catalog.now()
from s,t
on conflict(protocol_key) do nothing;

update private.tcj_evidence_sets
set provenance = provenance || jsonb_build_object(
  'qualification_protocol','TCJ-JUDGE-QUALIFICATION-2026Q3-v1',
  'item_target',48,
  'primary_target_cases_per_dimension',8,
  'construction_provenance','OpenAI GPT-5.6 Sol constructed draft; native editorial owner reviews/edits and labels every item before freeze; no candidate judge execution before bank freeze.',
  'human_first',true,
  'candidate_judge_exposure_before_freeze',false,
  'assurance_eligible',false
)
where set_key='TCJ-JUDGE-QUALIFICATION-v1' and status='draft';

with s as (select id from private.tcj_evidence_sets where set_key='TCJ-JUDGE-QUALIFICATION-v1')
insert into private.tcj_evidence_items(evidence_set_id,item_key,phenomenon,scenario_text,candidate_text,scenario_sha256,candidate_sha256,gold,provenance,source_table,source_id,exposure_state,exposure_note)
select s.id,v.item_key,v.phenomenon,v.scenario_text,v.candidate_text,
       encode(extensions.digest(v.scenario_text,'sha256'),'hex'),
       encode(extensions.digest(v.candidate_text,'sha256'),'hex'),
       '{}'::jsonb,'fresh qualification v1 constructed draft; native-human gold pending',null,null,'private','Never used for calibration, threshold fitting, judge selection, or Assurance.'
from s cross join (values
('QF-INT-01','intent_implied_contact','เพื่อนสนิทส่งรูปแชตมา เขาทักคนที่ชอบไปว่า “ถึงบ้านยัง” แล้วอีกฝ่ายอ่านแต่ไม่ตอบตั้งแต่เมื่อคืน เพื่อนถามว่า “ทักซ้ำดีไหม”','ยังค่ะ\nเมื่อคืนเขาเห็นแล้ว\nวันนี้ให้ความเงียบ\nทำงานบ้าง'),
('QF-INT-02','intent_semantic_drift','เพื่อนถามว่า “พรุ่งนี้ฝนตกไหม จะซักผ้า”','ถ้าเป็นเรา\nจะเลือกน้ำยาปรับผ้านุ่ม\nกลิ่นเบาๆ'),
('QF-INT-03','intent_relationship_status','เพื่อนบอกคนที่คุยด้วยพูดว่า “ช่วงนี้ยังไม่อยากผูกมัด” แต่ยังโทรหาทุกคืน แล้วถาม “สรุปเขาเอายังไง”','คำว่าไม่ผูกมัด\nก็คือไม่ผูกมัดค่ะ\nโทรทุกคืน\nไม่ได้แถมสถานะ'),
('QF-INT-04','intent_wrong_causal_focus','หัวหน้าตอบงานที่ส่งไปด้วย 👍 อย่างเดียว เพื่อนร่วมงานถามว่า “เขาโอเคกับงานใช่ไหม”','พรุ่งนี้ซื้อกาแฟให้หัวหน้าค่ะ\nบรรยากาศจะดีขึ้น'),
('QF-INT-05','intent_social_advice','เพื่อนถาม “แม่แฟนชวนไปกินข้าวครั้งแรก ควรไปมือเปล่าไหม”','เอาของเล็กๆ ไปค่ะ\nไม่ต้องเปิดห้าง\nแต่ไม่ต้องไปตัวเปล่า'),
('QF-INT-06','intent_proportional_advice','เพื่อนบ่นว่าเจอวันทำงานแย่มากวันเดียวแล้วถาม “ลาออกเลยดีไหม”','ชีวิตสั้นค่ะ\nทำตามหัวใจ\nจักรวาลจะจัดทางให้เอง'),
('QF-INT-07','intent_personification','เพื่อนถามเล่นๆ ว่า “เงินเดือนเข้ามาแล้วหายไปไหนทุกที”','มันไม่ได้หายค่ะ\nมันย้ายบ้าน\nไปอยู่กับค่าเช่าแล้ว'),
('QF-INT-08','intent_factual_vs_advice','เพื่อนส่งข้อความว่า “ร้านนั้นปิดกี่โมงนะ”','ถ้าอยากไป\nก็ไปเลยค่ะ\nอย่าคิดเยอะ'),
('QF-PRG-01','pragmatics_natural_omission','เพื่อนถามตอนห้าทุ่มว่า “ยังออกมาไหวไหม”','ไหว\nแต่ขอไม่เกินเที่ยงคืน'),
('QF-PRG-02','pragmatics_translation_shape','เพื่อนถาม “เย็นนี้ไปกินข้าวกันไหม”','ฉันคิดว่าการไปรับประทานอาหารร่วมกันในช่วงเย็นเป็นความคิดที่เหมาะสมค่ะ'),
('QF-PRG-03','pragmatics_pronoun_overuse','เพื่อนเล่าว่าแฟนงอน แล้วถาม “เราควรโทรหาเขาไหม”','ฉันคิดว่าคุณควรโทรหาเขา เพราะการที่คุณโทรหาเขาจะทำให้เขารู้ว่าคุณใส่ใจเขา'),
('QF-PRG-04','pragmatics_particle_fit','เพื่อนถามในไลน์ว่า “ส่งไฟล์ให้พี่เมย์แล้วใช่ไหม”','ส่งแล้วค่ะ\nเมื่อกี้เลย'),
('QF-PRG-05','pragmatics_overexplicit_connector','เพื่อนถาม “ทำไมแกไม่ไปปาร์ตี้เมื่อคืน”','เนื่องจากเรามีความรู้สึกเหนื่อยล้าจากการทำงาน จึงตัดสินใจไม่เข้าร่วมกิจกรรมดังกล่าว'),
('QF-PRG-06','pragmatics_fragment','เพื่อนถาม “พรุ่งนี้เจ็ดโมงเช้าไหวปะ”','ไหว\nแต่กาแฟต้องมาก่อน'),
('QF-PRG-07','pragmatics_hierarchy','รุ่นน้องต้องตอบหัวหน้าที่ถามว่า “เอกสารเสร็จหรือยัง”','เดี๋ยวส่งดิ\nอีกแป๊บ'),
('QF-PRG-08','pragmatics_ellipsis','เพื่อนถาม “จะทักเขาอีกรอบไหม” หลังส่งไปสองข้อความแล้วยังไม่ตอบ','สองรอบแล้วนะ'),
('QF-BFF-01','bff_deadpan','เพื่อนถาม “ซื้อรองเท้าคู่นี้อีกดีไหม ทั้งที่ตู้เต็มแล้ว”','ตู้รองเท้า\nขอทนายก่อนค่ะ'),
('QF-BFF-02','bff_assistant_voice','เพื่อนส่งแชตเรื่องคนคุยไม่ชัดเจนแล้วถาม “แกว่าไง”','จากข้อมูลที่ให้มา เราขอแนะนำให้คุณพิจารณาความต้องการของตนเองและสื่อสารอย่างตรงไปตรงมา'),
('QF-BFF-03','bff_forced_slang','เพื่อนถาม “คืนนี้ออกไหม”','ออกดิแม่ slay มากกก bestie ตัวมัม queen ต้องจึ้งต้องปังสุดๆ ไปเลยเว่อร์'),
('QF-BFF-04','bff_mock_politeness','เพื่อนถาม “กลับไปคุยกับแฟนเก่าดีไหม”','เรียนแจ้งว่า\nไม่อนุมัติค่ะ'),
('QF-BFF-05','bff_generic_support','เพื่อนบอก “พรีเซนต์พังมาก อยากมุดโต๊ะ” แล้วถาม “ปลอบเราหน่อย”','คุณทำดีที่สุดแล้วนะคะ ความผิดพลาดเกิดขึ้นได้เสมอ ขอให้คุณใจดีกับตัวเอง'),
('QF-BFF-06','bff_shade','เพื่อนบ่น “เขาตอบเราช้า แต่ลงสตอรี่ไวมาก”','เน็ตเขา\nเลือกคนค่ะ'),
('QF-BFF-07','bff_forced_camp','เพื่อนถาม “ชุดนี้โอเคไหม”','MOTHER เสิร์ฟมาก ชีเสิร์ฟ ชีจึ้ง ชีตัวแม่ ชีฆ่าทุกคนตายเรียบค่ะ'),
('QF-BFF-08','bff_restrained_friend','เพื่อนถาม “ควรคุยกับเพื่อนเรื่องที่ค้างใจกันไหม”','คุยค่ะ\nก่อนเรื่องเล็ก\nจะมีซีซันสอง'),
('QF-LEX-01','lexical_natural_borrowing','เพื่อนบอก “deadline เลื่อนอีกแล้ว” แล้วถาม “ดีไหม”','ดีค่ะ\ndeadline เลื่อน\nความรับผิดชอบเรา\nขอเลื่อนตามด้วยได้ไหม'),
('QF-LEX-02','lexical_awkward_code_mix','เพื่อนถาม “ควรตัดสินใจรับงานนี้ไหม”','เราซัพพอร์ตการ decision ของแกนะ\nถ้ามัน make sense กับ career path'),
('QF-LEX-03','lexical_register_mismatch','เพื่อนถามในกลุ่มว่า “คืนนี้กินอะไร”','ข้าพเจ้าขอเสนอให้พิจารณาร้านอาหารที่ทุกท่านมีความพึงพอใจร่วมกัน'),
('QF-LEX-04','lexical_cultural_fit','เพื่อนถามหลังเที่ยวดึกว่า “หาอะไรกินดี”','ข้าวต้มกุ๊ยค่ะ\nคืนนี้ชีวิต\nต้องการของเค็ม'),
('QF-LEX-05','lexical_overformal','เพื่อนถาม “ขอยืมเสื้อแกพรุ่งนี้ได้ไหม”','โปรดพิจารณาความเหมาะสมในการใช้ทรัพย์สินส่วนบุคคลของเรา'),
('QF-LEX-06','lexical_english_punchline','เพื่อนถาม “เขาหายไปสามวันแล้ว แบบนี้เรียก slow burn ปะ”','ไม่ใช่ slow burn\nนี่ offline'),
('QF-LEX-07','lexical_collocation','เพื่อนบอก “วันนี้เหนื่อยมาก”','งั้นดำเนินการนอนพักผ่อนโดยเร็วค่ะ'),
('QF-LEX-08','lexical_service_register','แขกถามพนักงานโรงแรมว่า “ช่วยเช็กได้ไหมว่าห้องพร้อมหรือยัง”','ได้ค่ะ\nเดี๋ยวเช็กให้เลยนะคะ'),
('QF-STA-01','stance_implied_no','เพื่อนถาม “คนเดิมหายไปแล้วกลับมาทักอีก ควรตอบไหม”','ถ้าต้องถามรอบสาม\nไม่ตอบค่ะ'),
('QF-STA-02','stance_empty_hedging','เพื่อนถาม “รับงานฟรีครั้งนี้ดีไหม เผื่อได้ connection”','ก็แล้วแต่แกเลย\nอะไรก็ได้หมด'),
('QF-STA-03','stance_overforceful','เพื่อนถาม “วันนี้โดนหัวหน้าติเรื่องเดียว ลาออกเลยไหม”','ลาออกเลยค่ะ\nเดี๋ยวนี้เลย\nไม่ต้องคิด'),
('QF-STA-04','stance_conditional_caution','เพื่อนชวนลงทุน แต่ยังไม่ส่งสัญญาหรือรายละเอียด แล้วถาม “โอนก่อนได้ไหม”','ยังไม่โอนค่ะ\nขอเอกสารก่อน'),
('QF-STA-05','stance_generic_depends','เพื่อนถาม “ควรซื้อประกันเดินทางทริปนี้ไหม”','ขึ้นอยู่กับหลายปัจจัยค่ะ\nลองพิจารณาตามความเหมาะสม'),
('QF-STA-06','stance_decisive_restraint','เพื่อนถาม “มือถือยังใช้ได้ดี แค่รุ่นใหม่ออก ควรเปลี่ยนไหม”','ยังค่ะ\nรอเครื่องงอแงก่อน'),
('QF-STA-07','stance_contradictory','เพื่อนถาม “ควรไปงานที่ไม่อยากไปไหม”','ไม่ควรไปค่ะ\nแต่ไปเลยก็ดีนะ\nสรุปไป'),
('QF-STA-08','stance_humorous_delay','คนที่คุยด้วยทัก “ทำไรอยู่” ตอนตีสอง เพื่อนถาม “ตอบตอนนี้ไหม”','พรุ่งนี้ค่ะ\nตีสองนี้\nให้เขาคุยกับความคิดถึงไปก่อน'),
('QF-CMP-01','composition_landing','เพื่อนถาม “พรุ่งนี้สัมภาษณ์งาน ใส่ชุดดำทั้งชุดดีไหม”','ได้ค่ะ\nแต่ให้ดูตั้งใจ\nไม่ใช่มางานไว้อาลัย'),
('QF-CMP-02','composition_overexplained','เพื่อนถาม “ควรสั่งของหวานเพิ่มไหม”','ถ้าพิจารณาจากสถานการณ์ตอนนี้ เราควรประเมินก่อนว่าเรายังรู้สึกหิวอยู่หรือไม่ รวมถึงพิจารณาปริมาณอาหารที่รับประทานไปแล้ว ราคา และความต้องการของตนเอง ก่อนจะตัดสินใจสั่งของหวานเพิ่มเติมค่ะ'),
('QF-CMP-03','composition_broken_lines','เพื่อนถาม “คืนนี้ดูหนังเรื่องเดิมอีกไหม”','ดู\nอีก\nก็\nได้\nถ้า\nแก\nอยาก\nดู'),
('QF-CMP-04','composition_redundant_landing','เพื่อนถาม “ตัดผมสั้นดีไหม”','ตัดค่ะ\nถ้าอยากตัด\nก็ตัด\nเพราะอยากตัดก็เลยควรตัด'),
('QF-CMP-05','composition_compressed','เพื่อนถาม “ฝนตกหนัก ยังจะออกไปซื้อชาไหม”','ไม่ค่ะ\nชาไม่หนี\nเราอาจไหล'),
('QF-CMP-06','composition_repetition','เพื่อนถาม “ส่งข้อความขอโทษไปแล้ว ต้องส่งเพิ่มไหม”','ส่งไปแล้วก็พอแล้วค่ะ เพราะเราได้ส่งคำขอโทษไปแล้ว และเมื่อส่งคำขอโทษไปแล้ว เราควรรอให้อีกฝ่ายตอบกลับก่อนที่จะส่งข้อความเพิ่มเติมอีกครั้ง'),
('QF-CMP-07','composition_hierarchy','เพื่อนถาม “พรุ่งนี้ต้องตื่นตีห้า คืนนี้ไปร้านต่อไหม”','ร้านมีทุกคืน\nตีห้ามีพรุ่งนี้\nกลับค่ะ'),
('QF-CMP-08','composition_random_fragmentation','เพื่อนถาม “กินอะไรดีตอนบ่าย”','เอา\nแบบ\nที่\nกิน\nแล้ว\nไม่\nหิว\nค่ะ')
) as v(item_key,phenomenon,scenario_text,candidate_text)
on conflict(evidence_set_id,item_key) do nothing;

with p as (
  select qp.id protocol_id,qp.protocol_key,qp.evidence_set_id from private.tcj_qualification_protocols qp where qp.protocol_key='TCJ-JUDGE-QUALIFICATION-2026Q3-v1'
), mapped as (
  select i.id evidence_item_id,i.item_key,i.scenario_text,i.candidate_text,p.protocol_id,
    case
      when i.item_key like 'QF-INT-%' then 'intent'
      when i.item_key like 'QF-PRG-%' then 'thai_pragmatics'
      when i.item_key like 'QF-BFF-%' then 'bff_voice'
      when i.item_key like 'QF-LEX-%' then 'lexical_social_fit'
      when i.item_key like 'QF-STA-%' then 'stance'
      when i.item_key like 'QF-CMP-%' then 'composition'
    end primary_dimension,
    case
      when i.item_key in ('QF-INT-01','QF-INT-03','QF-INT-05','QF-INT-07','QF-PRG-01','QF-PRG-04','QF-PRG-06','QF-PRG-08','QF-BFF-01','QF-BFF-04','QF-BFF-06','QF-BFF-08','QF-LEX-01','QF-LEX-04','QF-LEX-06','QF-LEX-08','QF-STA-01','QF-STA-04','QF-STA-06','QF-STA-08','QF-CMP-01','QF-CMP-05','QF-CMP-07') then 'constructed_likely_acceptable'
      else 'constructed_likely_problematic'
    end design_class,
    encode(extensions.digest(i.item_key||':TCJ-JUDGE-QUALIFICATION-2026Q3-v1:review-id','sha256'),'hex') review_hash,
    encode(extensions.digest(i.item_key||':TCJ-JUDGE-QUALIFICATION-2026Q3-v1:review-order','sha256'),'hex') order_hash
  from p join private.tcj_evidence_items i on i.evidence_set_id=p.evidence_set_id
  where i.item_key like 'QF-%'
), ranked as (
  select m.*,row_number() over(order by order_hash,item_key)::int review_order from mapped m
)
insert into private.tcj_qualification_case_designs(protocol_id,evidence_item_id,opaque_review_id,review_order,primary_dimension,design_class,construction_note,draft_scenario_text,draft_candidate_text,draft_scenario_sha256,draft_candidate_sha256,construction_provenance)
select protocol_id,evidence_item_id,'QH-'||upper(substr(review_hash,1,12)),review_order,primary_dimension,design_class,
       'Constructed to exercise the named primary dimension while all six dimensions remain human-rated. The target and design class are hidden from the human rating UI.',
       scenario_text,candidate_text,encode(extensions.digest(scenario_text,'sha256'),'hex'),encode(extensions.digest(candidate_text,'sha256'),'hex'),
       'OpenAI GPT-5.6 Sol draft; native editorial owner may edit scenario/candidate before human-label freeze.'
from ranked
on conflict(evidence_item_id) do nothing;

create or replace function private.tcj_freeze_qualification_bank(p_protocol_key text,p_actor_user_id uuid default null)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,private,extensions
as $$
declare
  p private.tcj_qualification_protocols%rowtype;
  s private.tcj_evidence_sets%rowtype;
  v_items integer;
  v_reviews integer;
  v_bad integer;
  v_evidence_manifest text;
  v_human_manifest text;
begin
  select * into p from private.tcj_qualification_protocols where protocol_key=p_protocol_key for update;
  if not found then raise exception 'qualification_protocol_missing'; end if;
  select * into s from private.tcj_evidence_sets where id=p.evidence_set_id for update;
  if p.status='bank_frozen' and s.status='frozen' then
    return jsonb_build_object('status','bank_frozen','items',p.item_target,'human_manifest_sha256',p.human_manifest_sha256,'evidence_manifest_sha256',s.manifest_sha256,'threshold_sha256',p.threshold_sha256);
  end if;
  if p.status<>'draft_review' or s.status<>'draft' then raise exception 'qualification_freeze_state_gate:%/%',p.status,s.status; end if;

  select count(*)::int into v_items from private.tcj_evidence_items i where i.evidence_set_id=p.evidence_set_id;
  if v_items<>p.item_target then raise exception 'qualification_item_count_gate:%',v_items; end if;
  select count(*)::int into v_reviews from private.tcj_qualification_human_reviews r where r.protocol_id=p.id and r.review_state='draft';
  if v_reviews<>p.item_target then raise exception 'qualification_human_review_count_gate:%',v_reviews; end if;

  select count(*)::int into v_bad
  from private.tcj_evidence_items i
  join private.tcj_qualification_human_reviews r on r.evidence_item_id=i.id and r.protocol_id=p.id
  where i.evidence_set_id=p.evidence_set_id and (
       i.exposure_state<>'private'
    or i.scenario_sha256<>encode(extensions.digest(i.scenario_text,'sha256'),'hex')
    or i.candidate_sha256<>encode(extensions.digest(i.candidate_text,'sha256'),'hex')
    or r.scenario_sha256<>i.scenario_sha256
    or r.candidate_sha256<>i.candidate_sha256
    or r.review_sha256<>private.tcj_qualification_review_hash(r.final_scenario_text,r.final_candidate_text,r.ratings,r.severity,r.flags,r.confidence,r.human_ambiguous,r.review_note)
    or i.gold<>jsonb_build_object(
      'intent',(r.ratings->>'intent')::int,
      'thai_pragmatics',(r.ratings->>'thai_pragmatics')::int,
      'bff_voice',(r.ratings->>'bff_voice')::int,
      'lexical_social_fit',(r.ratings->>'lexical_social_fit')::int,
      'stance',(r.ratings->>'stance')::int,
      'composition',(r.ratings->>'composition')::int,
      'severity',r.severity,
      'flags',to_jsonb(r.flags),
      'care_mode',false
    )
  );
  if v_bad<>0 then raise exception 'qualification_human_integrity_gate:%',v_bad; end if;

  select encode(extensions.digest(string_agg(
    i.item_key||':'||i.scenario_sha256||':'||i.candidate_sha256||':'||encode(extensions.digest(i.gold::text,'sha256'),'hex')||':'||r.review_sha256,
    '|' order by i.item_key
  ),'sha256'),'hex') into v_evidence_manifest
  from private.tcj_evidence_items i
  join private.tcj_qualification_human_reviews r on r.evidence_item_id=i.id and r.protocol_id=p.id
  where i.evidence_set_id=p.evidence_set_id;

  v_human_manifest:=encode(extensions.digest(v_evidence_manifest||':'||p.threshold_sha256,'sha256'),'hex');

  update private.tcj_qualification_human_reviews
     set review_state='frozen',frozen_at=pg_catalog.now(),updated_at=pg_catalog.now()
   where protocol_id=p.id and review_state='draft';
  update private.tcj_evidence_sets
     set status='frozen',manifest_sha256=v_evidence_manifest,frozen_at=pg_catalog.now()
   where id=p.evidence_set_id and status='draft';
  update private.tcj_qualification_protocols
     set status='bank_frozen',human_manifest_sha256=v_human_manifest,human_review_frozen_at=pg_catalog.now(),bank_frozen_at=pg_catalog.now(),frozen_by=p_actor_user_id
   where id=p.id and status='draft_review';

  return jsonb_build_object('status','bank_frozen','items',v_items,'human_manifest_sha256',v_human_manifest,'evidence_manifest_sha256',v_evidence_manifest,'threshold_sha256',p.threshold_sha256);
end;
$$;
revoke all on function private.tcj_freeze_qualification_bank(text,uuid) from public,anon,authenticated;
