alter table private.tcj_judge_passports
  add column if not exists passport_sha256 text,
  add column if not exists frozen_at timestamptz;

do $$ begin
  if not exists (
    select 1 from pg_constraint where conname='tcj_judge_passports_passport_sha256_check' and conrelid='private.tcj_judge_passports'::regclass
  ) then
    alter table private.tcj_judge_passports add constraint tcj_judge_passports_passport_sha256_check
      check (passport_sha256 is null or length(passport_sha256)=64);
  end if;
end $$;

create table if not exists private.tcj_admission_identity_reveal_events (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null unique references private.tcj_admission_campaigns(id),
  review_protocol_version text not null,
  dossier_version text not null,
  review_count integer not null check (review_count=6),
  reveal_evidence_sha256 text not null check (length(reveal_evidence_sha256)=64),
  identity_mapping_sha256 text not null check (length(identity_mapping_sha256)=64),
  actor_user_id uuid,
  revealed_at timestamptz not null default pg_catalog.now()
);

create table if not exists private.tcj_admission_passport_assignment_events (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null unique references private.tcj_admission_campaigns(id),
  passport_version text not null,
  passport_count integer not null check (passport_count=3),
  assignment_manifest_sha256 text not null check (length(assignment_manifest_sha256)=64),
  actor_user_id uuid,
  assigned_at timestamptz not null default pg_catalog.now()
);

alter table private.tcj_admission_identity_reveal_events enable row level security;
alter table private.tcj_admission_passport_assignment_events enable row level security;
revoke all on private.tcj_admission_identity_reveal_events from anon, authenticated;
revoke all on private.tcj_admission_passport_assignment_events from anon, authenticated;
revoke all on sequence private.tcj_admission_identity_reveal_events_id_seq from anon, authenticated;
revoke all on sequence private.tcj_admission_passport_assignment_events_id_seq from anon, authenticated;

create or replace function private.tcj_prevent_revealed_candidate_identity_mutation()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,private
as $$
begin
  if old.identity_state='revealed' and (
       new.opaque_candidate_id is distinct from old.opaque_candidate_id
    or new.provider is distinct from old.provider
    or new.model_name is distinct from old.model_name
    or new.model_family is distinct from old.model_family
    or new.model_snapshot is distinct from old.model_snapshot
    or new.identity_state is distinct from old.identity_state
  ) then
    raise exception 'revealed_candidate_identity_immutable';
  end if;
  return new;
end;
$$;
revoke all on function private.tcj_prevent_revealed_candidate_identity_mutation() from public,anon,authenticated;

drop trigger if exists tcj_revealed_candidate_identity_immutable_trg on private.tcj_judge_candidates;
create trigger tcj_revealed_candidate_identity_immutable_trg
before update on private.tcj_judge_candidates
for each row execute function private.tcj_prevent_revealed_candidate_identity_mutation();

create or replace function private.tcj_prevent_frozen_passport_mutation()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,private
as $$
begin
  if old.frozen_at is not null then
    raise exception 'frozen_judge_passport_immutable';
  end if;
  return case when tg_op='DELETE' then old else new end;
end;
$$;
revoke all on function private.tcj_prevent_frozen_passport_mutation() from public,anon,authenticated;

drop trigger if exists tcj_judge_passport_immutable_trg on private.tcj_judge_passports;
create trigger tcj_judge_passport_immutable_trg
before update or delete on private.tcj_judge_passports
for each row execute function private.tcj_prevent_frozen_passport_mutation();

create or replace function private.tcj_reveal_admission_identities(p_campaign_key text,p_actor_user_id uuid default null)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,private,extensions
as $$
declare
  v_campaign private.tcj_admission_campaigns%rowtype;
  v_reviews integer;
  v_pairs integer;
  v_dossiers integer;
  v_bad_review_hash integer;
  v_bad_dossier_hash integer;
  v_candidates integer;
  v_sealed integer;
  v_reveal_sha text;
  v_mapping_sha text;
  v_map jsonb;
begin
  select * into v_campaign from private.tcj_admission_campaigns where campaign_key=p_campaign_key for update;
  if not found then raise exception 'campaign_missing'; end if;
  if v_campaign.status not in ('meta_review_frozen','identity_revealed','complete') then raise exception 'identity_reveal_state_gate:%',v_campaign.status; end if;
  if v_campaign.meta_reviews_frozen_at is null then raise exception 'meta_review_not_frozen'; end if;

  select count(*)::int,
         count(distinct (m.dossier_id::text||':'||m.reviewer_slot))::int,
         count(distinct m.dossier_id)::int,
         count(*) filter(where
              m.review_state<>'valid'
           or m.frozen_at is null
           or m.raw_output_text is null
           or m.raw_output_sha256<>encode(extensions.digest(m.raw_output_text,'sha256'),'hex')
           or m.parsed_review is null
           or m.parsed_review_sha256<>encode(extensions.digest(m.parsed_review::text,'sha256'),'hex')
           or m.dossier_sha256<>d.dossier_sha256
         )::int
    into v_reviews,v_pairs,v_dossiers,v_bad_review_hash
  from private.tcj_admission_meta_reviews m
  join private.tcj_admission_passport_dossiers d on d.id=m.dossier_id
  where m.campaign_id=v_campaign.id and m.review_protocol_version='TCJ-JUDGE-META-REVIEW-v1';

  if v_reviews<>6 or v_pairs<>6 or v_dossiers<>3 or v_bad_review_hash<>0 then
    raise exception 'identity_reveal_review_gate:r%,p%,d%,bad%',v_reviews,v_pairs,v_dossiers,v_bad_review_hash;
  end if;

  select count(*) filter(where d.dossier_sha256<>encode(extensions.digest(d.dossier::text,'sha256'),'hex'))::int
    into v_bad_dossier_hash
  from private.tcj_admission_passport_dossiers d
  where d.campaign_id=v_campaign.id and d.dossier_version='TCJ-JUDGE-PASSPORT-DOSSIER-v1';
  if v_bad_dossier_hash<>0 then raise exception 'identity_reveal_dossier_hash_gate'; end if;

  select count(*)::int,count(*) filter(where j.identity_state='sealed')::int
    into v_candidates,v_sealed
  from private.tcj_admission_campaign_candidates cc
  join private.tcj_judge_candidates j on j.id=cc.judge_candidate_id
  where cc.campaign_id=v_campaign.id;
  if v_candidates<>3 then raise exception 'identity_reveal_candidate_count_gate:%',v_candidates; end if;

  select encode(extensions.digest(string_agg(
      d.opaque_dossier_id||':'||d.dossier_sha256||':'||m.reviewer_slot||':'||m.raw_output_sha256||':'||m.parsed_review_sha256,
      '|' order by d.opaque_dossier_id,m.reviewer_slot
    ),'sha256'),'hex')
    into v_reveal_sha
  from private.tcj_admission_meta_reviews m
  join private.tcj_admission_passport_dossiers d on d.id=m.dossier_id
  where m.campaign_id=v_campaign.id and m.review_protocol_version='TCJ-JUDGE-META-REVIEW-v1';

  select encode(extensions.digest(string_agg(
      j.opaque_candidate_id||':'||coalesce(j.provider,'')||':'||coalesce(j.model_name,'')||':'||coalesce(j.model_family,'')||':'||coalesce(j.model_snapshot,''),
      '|' order by j.opaque_candidate_id
    ),'sha256'),'hex')
    into v_mapping_sha
  from private.tcj_admission_campaign_candidates cc
  join private.tcj_judge_candidates j on j.id=cc.judge_candidate_id
  where cc.campaign_id=v_campaign.id;

  if v_campaign.identity_revealed_at is null then
    if v_sealed<>3 then raise exception 'identity_reveal_seal_gate:%',v_sealed; end if;
    update private.tcj_judge_candidates j
       set identity_state='revealed'
      from private.tcj_admission_campaign_candidates cc
     where cc.campaign_id=v_campaign.id and cc.judge_candidate_id=j.id and j.identity_state='sealed';
    update private.tcj_admission_campaigns
       set identity_revealed_at=pg_catalog.now(),status='identity_revealed'
     where id=v_campaign.id and identity_revealed_at is null and status='meta_review_frozen';
    insert into private.tcj_admission_identity_reveal_events(campaign_id,review_protocol_version,dossier_version,review_count,reveal_evidence_sha256,identity_mapping_sha256,actor_user_id)
    values(v_campaign.id,'TCJ-JUDGE-META-REVIEW-v1','TCJ-JUDGE-PASSPORT-DOSSIER-v1',6,v_reveal_sha,v_mapping_sha,p_actor_user_id)
    on conflict(campaign_id) do nothing;
  else
    if not exists(select 1 from private.tcj_admission_identity_reveal_events e where e.campaign_id=v_campaign.id and e.reveal_evidence_sha256=v_reveal_sha and e.identity_mapping_sha256=v_mapping_sha) then
      raise exception 'identity_reveal_event_mismatch';
    end if;
  end if;

  select jsonb_agg(jsonb_build_object(
    'opaque_candidate_id',j.opaque_candidate_id,
    'provider',j.provider,
    'model_name',j.model_name,
    'model_family',j.model_family,
    'model_snapshot',j.model_snapshot,
    'dossier_id',d.opaque_dossier_id,
    'meta_reviews',(
      select jsonb_object_agg(m.reviewer_slot,jsonb_build_object(
        'overall_recommendation',m.parsed_review->>'overall_recommendation',
        'overall_confidence',m.parsed_review->>'overall_confidence',
        'dimension_recommendations',m.parsed_review->'dimension_recommendations'
      )) from private.tcj_admission_meta_reviews m where m.dossier_id=d.id and m.review_protocol_version='TCJ-JUDGE-META-REVIEW-v1'
    )
  ) order by j.opaque_candidate_id)
  into v_map
  from private.tcj_admission_campaign_candidates cc
  join private.tcj_judge_candidates j on j.id=cc.judge_candidate_id
  join private.tcj_admission_passport_dossiers d on d.campaign_id=cc.campaign_id and d.judge_candidate_id=j.id and d.dossier_version='TCJ-JUDGE-PASSPORT-DOSSIER-v1'
  where cc.campaign_id=v_campaign.id;

  return jsonb_build_object('status','identity_revealed','reveal_evidence_sha256',v_reveal_sha,'identity_mapping_sha256',v_mapping_sha,'candidates',coalesce(v_map,'[]'::jsonb));
end;
$$;
revoke all on function private.tcj_reveal_admission_identities(text,uuid) from public,anon,authenticated;

create or replace function private.tcj_assign_preliminary_passports(p_campaign_key text,p_actor_user_id uuid default null)
returns jsonb
language plpgsql
security definer
set search_path=pg_catalog,private,extensions
as $$
declare
  v_campaign private.tcj_admission_campaigns%rowtype;
  v_count integer;
  v_evidence_count integer;
  v_assignment_sha text;
  v_rows jsonb;
begin
  select * into v_campaign from private.tcj_admission_campaigns where campaign_key=p_campaign_key for update;
  if not found then raise exception 'campaign_missing'; end if;
  if v_campaign.status not in ('identity_revealed','complete') or v_campaign.identity_revealed_at is null then raise exception 'passport_assignment_reveal_gate'; end if;
  if not exists(select 1 from private.tcj_admission_identity_reveal_events e where e.campaign_id=v_campaign.id) then raise exception 'passport_assignment_reveal_event_missing'; end if;

  if (select count(*) from private.tcj_admission_meta_reviews m where m.campaign_id=v_campaign.id and m.review_protocol_version='TCJ-JUDGE-META-REVIEW-v1' and m.review_state='valid' and m.frozen_at is not null)<>6 then
    raise exception 'passport_assignment_review_gate';
  end if;

  select
    coalesce((select max((d.dossier#>>'{production_evidence,reviewed_count}')::int) from private.tcj_admission_passport_dossiers d where d.campaign_id=v_campaign.id and d.dossier_version='TCJ-JUDGE-PASSPORT-DOSSIER-v1'),0)
    + coalesce((select max((d.dossier#>>'{judging_evidence,case_count}')::int) from private.tcj_admission_passport_dossiers d where d.campaign_id=v_campaign.id and d.dossier_version='TCJ-JUDGE-PASSPORT-DOSSIER-v1'),0)
    + coalesce((select count(*) from private.tcj_admission_robustness_cases c join private.tcj_admission_robustness_packs p on p.id=c.pack_id where p.campaign_id=v_campaign.id and p.pack_key='TCJ-JUDGE-ROBUSTNESS-2026Q3-v1'),0)
    + coalesce((select count(*) from private.tcj_admission_robustness_cases c join private.tcj_admission_robustness_packs p on p.id=c.pack_id where p.campaign_id=v_campaign.id and p.pack_key='TCJ-JUDGE-ROBUSTNESS-PERTURB-2026Q3-v1'),0)
  into v_evidence_count;

  with src as (
    select d.*,j.opaque_candidate_id,
      (select jsonb_object_agg(m.reviewer_slot,jsonb_build_object(
          'reviewer_provider',m.reviewer_provider,
          'reviewer_model',m.reviewer_model,
          'raw_output_sha256',m.raw_output_sha256,
          'parsed_review_sha256',m.parsed_review_sha256,
          'review',m.parsed_review
        )) from private.tcj_admission_meta_reviews m where m.dossier_id=d.id and m.review_protocol_version='TCJ-JUDGE-META-REVIEW-v1') meta_reviews,
      (select coalesce(jsonb_agg(distinct x.val),'[]'::jsonb)
         from private.tcj_admission_meta_reviews m
         cross join lateral jsonb_array_elements_text(m.parsed_review->'failure_clusters') x(val)
        where m.dossier_id=d.id and m.review_protocol_version='TCJ-JUDGE-META-REVIEW-v1') failure_clusters
    from private.tcj_admission_passport_dossiers d
    join private.tcj_judge_candidates j on j.id=d.judge_candidate_id
    where d.campaign_id=v_campaign.id and d.dossier_version='TCJ-JUDGE-PASSPORT-DOSSIER-v1'
  ), built as (
    select s.*,
      jsonb_build_object(
        'judge_candidate_id',s.judge_candidate_id,
        'passport_version','admission-preliminary-v1',
        'profile_id',s.profile_id,
        'admission_protocol_version',s.admission_protocol_version,
        'qualification_state','research_only',
        'evidence_item_count',v_evidence_count,
        'production_evidence',s.dossier->'production_evidence',
        'judging_evidence',(s.dossier->'judging_evidence')||jsonb_build_object('blind_meta_reviews',s.meta_reviews),
        'robustness_evidence',s.dossier->'robustness_evidence',
        'qualified_dimensions','[]'::jsonb,
        'excluded_dimensions',jsonb_build_array('intent','thai_pragmatics','bff_voice','lexical_social_fit','stance','composition'),
        'known_failure_clusters',s.failure_clusters,
        'uncertainty',jsonb_build_object(
          'evidence_class','preliminary_admission_mixed_exposure',
          'clean_holdout',false,
          'hidden_qualification_bank_completed',false,
          'assurance_eligible',false,
          'final_qualification_sufficient',false,
          'production_authority',false,
          'meta_review_consensus','research_only',
          'reviewer_recommendations',jsonb_build_object(
             'chatgpt',s.meta_reviews#>>'{chatgpt,review,overall_recommendation}',
             'grok',s.meta_reviews#>>'{grok,review,overall_recommendation}'
          ),
          'reviewer_dimension_recommendations',jsonb_build_object(
             'chatgpt',s.meta_reviews#>'{chatgpt,review,dimension_recommendations}',
             'grok',s.meta_reviews#>'{grok,review,dimension_recommendations}'
          )
        ),
        'requalification_condition','Complete a fresh hidden Qualification Bank under a versioned blind protocol before any production authority; Assurance remains separately required.'
      ) canonical
    from src s
  ), ins as (
    insert into private.tcj_judge_passports(
      judge_candidate_id,passport_version,profile_id,admission_protocol_version,qualification_state,evidence_set_id,evidence_item_count,
      production_evidence,judging_evidence,robustness_evidence,qualified_dimensions,excluded_dimensions,known_failure_clusters,uncertainty,
      qualified_at,expires_at,requalification_condition,passport_sha256,frozen_at
    )
    select judge_candidate_id,'admission-preliminary-v1',profile_id,admission_protocol_version,'research_only',null,v_evidence_count,
      canonical->'production_evidence',canonical->'judging_evidence',canonical->'robustness_evidence','{}'::text[],array['intent','thai_pragmatics','bff_voice','lexical_social_fit','stance','composition']::text[],
      canonical->'known_failure_clusters',canonical->'uncertainty',null,null,canonical->>'requalification_condition',
      encode(extensions.digest(canonical::text,'sha256'),'hex'),pg_catalog.now()
    from built
    on conflict(judge_candidate_id,passport_version,profile_id) do nothing
    returning id
  )
  select count(*) into v_count from private.tcj_judge_passports p
  join private.tcj_admission_campaign_candidates cc on cc.judge_candidate_id=p.judge_candidate_id
  where cc.campaign_id=v_campaign.id and p.passport_version='admission-preliminary-v1' and p.profile_id=v_campaign.profile_id and p.frozen_at is not null;

  if v_count<>3 then raise exception 'passport_assignment_count_gate:%',v_count; end if;

  select encode(extensions.digest(string_agg(j.opaque_candidate_id||':'||p.passport_sha256,'|' order by j.opaque_candidate_id),'sha256'),'hex')
    into v_assignment_sha
  from private.tcj_judge_passports p
  join private.tcj_judge_candidates j on j.id=p.judge_candidate_id
  join private.tcj_admission_campaign_candidates cc on cc.judge_candidate_id=j.id
  where cc.campaign_id=v_campaign.id and p.passport_version='admission-preliminary-v1' and p.profile_id=v_campaign.profile_id;

  insert into private.tcj_admission_passport_assignment_events(campaign_id,passport_version,passport_count,assignment_manifest_sha256,actor_user_id)
  values(v_campaign.id,'admission-preliminary-v1',3,v_assignment_sha,p_actor_user_id)
  on conflict(campaign_id) do nothing;

  if exists(select 1 from private.tcj_admission_passport_assignment_events e where e.campaign_id=v_campaign.id and e.assignment_manifest_sha256<>v_assignment_sha) then
    raise exception 'passport_assignment_manifest_mismatch';
  end if;

  update private.tcj_admission_campaigns set status='complete' where id=v_campaign.id and status='identity_revealed';

  select jsonb_agg(jsonb_build_object(
    'opaque_candidate_id',j.opaque_candidate_id,
    'provider',j.provider,
    'model_name',j.model_name,
    'model_family',j.model_family,
    'model_snapshot',j.model_snapshot,
    'qualification_state',p.qualification_state,
    'passport_version',p.passport_version,
    'passport_sha256',p.passport_sha256,
    'qualified_dimensions',to_jsonb(p.qualified_dimensions),
    'excluded_dimensions',to_jsonb(p.excluded_dimensions),
    'uncertainty',p.uncertainty
  ) order by j.opaque_candidate_id)
  into v_rows
  from private.tcj_judge_passports p
  join private.tcj_judge_candidates j on j.id=p.judge_candidate_id
  join private.tcj_admission_campaign_candidates cc on cc.judge_candidate_id=j.id
  where cc.campaign_id=v_campaign.id and p.passport_version='admission-preliminary-v1' and p.profile_id=v_campaign.profile_id;

  return jsonb_build_object('status','complete','passport_version','admission-preliminary-v1','passport_count',3,'assignment_manifest_sha256',v_assignment_sha,'passports',coalesce(v_rows,'[]'::jsonb));
end;
$$;
revoke all on function private.tcj_assign_preliminary_passports(text,uuid) from public,anon,authenticated;
