alter table private.tcj_admission_stage_b_failures
  add column if not exists protocol_version text,
  add column if not exists prompt_version text,
  add column if not exists methodology_sha256 text,
  add column if not exists evidence_state text not null default 'active',
  add column if not exists invalidated_at timestamptz,
  add column if not exists invalidation_reason text;

alter table private.tcj_admission_stage_b_failures
  drop constraint if exists tcj_admission_stage_b_failures_evidence_state_check;
alter table private.tcj_admission_stage_b_failures
  add constraint tcj_admission_stage_b_failures_evidence_state_check
  check (evidence_state in ('active','terminal','resolved','invalidated'));

create table if not exists private.tcj_admission_stage_b_attempts (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references private.tcj_admission_campaigns(id),
  evidence_item_id bigint not null references private.tcj_evidence_items(id),
  judge_candidate_id bigint not null references private.tcj_judge_candidates(id),
  protocol_version text not null,
  prompt_version text not null,
  attempt_index integer not null check (attempt_index >= 1),
  attempt_role text not null check (attempt_role in ('primary','repair')),
  http_status integer,
  finish_reason text,
  outcome_class text not null,
  error_code text,
  raw_output_text text,
  raw_output_sha256 text,
  parsed_output jsonb,
  generation_settings jsonb not null default '{}'::jsonb,
  usage jsonb,
  latency_ms integer,
  evidence_eligible boolean not null default true,
  invalidation_reason text,
  created_at timestamptz not null default now(),
  unique (campaign_id,evidence_item_id,judge_candidate_id,protocol_version,attempt_index)
);

alter table private.tcj_admission_stage_b_attempts enable row level security;
revoke all on private.tcj_admission_stage_b_attempts from anon, authenticated;

create index if not exists tcj_stage_b_attempts_campaign_idx
  on private.tcj_admission_stage_b_attempts(campaign_id);
create index if not exists tcj_stage_b_attempts_item_idx
  on private.tcj_admission_stage_b_attempts(evidence_item_id);
create index if not exists tcj_stage_b_attempts_judge_idx
  on private.tcj_admission_stage_b_attempts(judge_candidate_id);

with target as (
  select f.id
  from private.tcj_admission_stage_b_failures f
  join private.tcj_admission_campaigns c on c.id=f.campaign_id
  where c.campaign_key='TCJ-JUDGE-ADMISSION-2026Q3-v1.2'
    and f.last_error_code='bad_intent'
    and f.failure_class='generation_contract'
    and f.resolved_at is null
)
update private.tcj_admission_stage_b_failures f
set protocol_version='TCJ-JUDGE-ADMISSION-STAGE-B-v1',
    prompt_version='TCJ-STAGE-B-JUDGE-v1',
    evidence_state='invalidated',
    invalidated_at=now(),
    invalidation_reason='Stage B v1 used a simplified prompt that diverged from the canonical TCJ answers-bff-v2 judging contract; no valid Stage B judgments existed. Preserve as implementation-validity provenance and exclude from candidate evidence.'
where f.id in (select id from target);

insert into private.tcj_admission_stage_b_attempts(
  campaign_id,evidence_item_id,judge_candidate_id,protocol_version,prompt_version,
  attempt_index,attempt_role,http_status,finish_reason,outcome_class,error_code,
  raw_output_text,evidence_eligible,invalidation_reason,created_at
)
select f.campaign_id,f.evidence_item_id,f.judge_candidate_id,
       'TCJ-JUDGE-ADMISSION-STAGE-B-v1','TCJ-STAGE-B-JUDGE-v1',
       1,'primary',f.last_http_status,f.error_meta->>'finish_reason',
       'implementation_invalid_prompt_contract',f.last_error_code,
       f.error_meta->>'content_preview',false,
       f.invalidation_reason,f.first_failed_at
from private.tcj_admission_stage_b_failures f
join private.tcj_admission_campaigns c on c.id=f.campaign_id
where c.campaign_key='TCJ-JUDGE-ADMISSION-2026Q3-v1.2'
  and f.evidence_state='invalidated'
  and f.protocol_version='TCJ-JUDGE-ADMISSION-STAGE-B-v1'
on conflict do nothing;

update private.tcj_admission_campaigns c
set status='human_review_frozen'
where c.campaign_key='TCJ-JUDGE-ADMISSION-2026Q3-v1.2'
  and c.status='stage_b'
  and c.stage_b_frozen_at is null
  and c.identity_revealed_at is null
  and not exists (
    select 1 from private.tcj_admission_stage_b_judgments j where j.campaign_id=c.id
  );
