create table if not exists private.tcj_admission_passport_dossiers (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references private.tcj_admission_campaigns(id),
  judge_candidate_id bigint not null references private.tcj_judge_candidates(id),
  opaque_dossier_id text not null unique,
  dossier_version text not null,
  profile_id text not null,
  admission_protocol_version text not null,
  evidence_class text not null,
  dossier jsonb not null,
  dossier_sha256 text not null,
  stage_a_manifest_sha256 text not null,
  stage_b_manifest_sha256 text not null,
  robustness_manifest_sha256 text not null,
  perturbation_manifest_sha256 text not null,
  frozen_at timestamptz not null default pg_catalog.now(),
  created_at timestamptz not null default pg_catalog.now(),
  unique(campaign_id,judge_candidate_id,dossier_version),
  check (jsonb_typeof(dossier)='object'),
  check (length(dossier_sha256)=64),
  check (length(stage_a_manifest_sha256)=64),
  check (length(stage_b_manifest_sha256)=64),
  check (length(robustness_manifest_sha256)=64),
  check (length(perturbation_manifest_sha256)=64)
);

create table if not exists private.tcj_admission_meta_reviews (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references private.tcj_admission_campaigns(id),
  dossier_id bigint not null references private.tcj_admission_passport_dossiers(id),
  reviewer_slot text not null check (reviewer_slot in ('chatgpt','grok')),
  review_protocol_version text not null,
  dossier_sha256 text not null,
  reviewer_provider text,
  reviewer_model text,
  review_state text not null default 'pending' check (review_state in ('pending','valid','contract_failure','infrastructure_failure','invalidated')),
  raw_output_text text,
  raw_output_sha256 text,
  parsed_review jsonb,
  parsed_review_sha256 text,
  failure_code text,
  failure_meta jsonb not null default '{}'::jsonb,
  frozen_at timestamptz,
  created_at timestamptz not null default pg_catalog.now(),
  unique(dossier_id,reviewer_slot,review_protocol_version),
  check (jsonb_typeof(failure_meta)='object'),
  check (parsed_review is null or jsonb_typeof(parsed_review)='object'),
  check (raw_output_sha256 is null or length(raw_output_sha256)=64),
  check (parsed_review_sha256 is null or length(parsed_review_sha256)=64),
  check (length(dossier_sha256)=64)
);

alter table private.tcj_admission_passport_dossiers enable row level security;
alter table private.tcj_admission_meta_reviews enable row level security;
revoke all on private.tcj_admission_passport_dossiers from anon, authenticated;
revoke all on private.tcj_admission_meta_reviews from anon, authenticated;
revoke all on sequence private.tcj_admission_passport_dossiers_id_seq from anon, authenticated;
revoke all on sequence private.tcj_admission_meta_reviews_id_seq from anon, authenticated;

create or replace function private.tcj_prevent_frozen_dossier_mutation()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,private,extensions
as $$
begin
  if old.frozen_at is not null then
    raise exception 'frozen_passport_dossier_immutable';
  end if;
  return case when tg_op='DELETE' then old else new end;
end;
$$;
revoke all on function private.tcj_prevent_frozen_dossier_mutation() from public, anon, authenticated;

drop trigger if exists tcj_passport_dossier_immutable_trg on private.tcj_admission_passport_dossiers;
create trigger tcj_passport_dossier_immutable_trg
before update or delete on private.tcj_admission_passport_dossiers
for each row execute function private.tcj_prevent_frozen_dossier_mutation();

create or replace function private.tcj_prevent_frozen_meta_review_mutation()
returns trigger
language plpgsql
security definer
set search_path=pg_catalog,private
as $$
begin
  if old.frozen_at is not null then
    raise exception 'frozen_meta_review_immutable';
  end if;
  return case when tg_op='DELETE' then old else new end;
end;
$$;
revoke all on function private.tcj_prevent_frozen_meta_review_mutation() from public, anon, authenticated;

drop trigger if exists tcj_meta_review_immutable_trg on private.tcj_admission_meta_reviews;
create trigger tcj_meta_review_immutable_trg
before update or delete on private.tcj_admission_meta_reviews
for each row execute function private.tcj_prevent_frozen_meta_review_mutation();

with campaign as (
  select id,profile_id,protocol_version,identity_revealed_at
  from private.tcj_admission_campaigns
  where campaign_key='TCJ-JUDGE-ADMISSION-2026Q3-v1.2'
), rv1_pack as (
  select p.id,p.campaign_id,p.manifest_sha256
  from private.tcj_admission_robustness_packs p,campaign c
  where p.campaign_id=c.id and p.pack_key='TCJ-JUDGE-ROBUSTNESS-2026Q3-v1' and p.status='complete'
), pert_pack as (
  select p.id,p.campaign_id,p.manifest_sha256
  from private.tcj_admission_robustness_packs p,campaign c
  where p.campaign_id=c.id and p.pack_key='TCJ-JUDGE-ROBUSTNESS-PERTURB-2026Q3-v1' and p.status='complete'
), evidence as (
  select c.id campaign_id,c.profile_id,c.protocol_version,
         a.judge_candidate_id,a.opaque_candidate_id,
         a.reviewed_count,a.accept_count,a.edit_count,a.rewrite_count,a.changed_count,a.summary stage_a_summary,a.evidence_manifest_sha256 stage_a_manifest,
         b.case_count stage_b_case_count,b.valid_count stage_b_valid_count,b.dimension_metrics,b.error_metrics,b.evidence_manifest_sha256 stage_b_manifest,
         r.repeat_metrics,r.self_preference_metrics,r.reliability_metrics robustness_reliability,r.evidence_manifest_sha256 robustness_manifest,
         pr.perturbation_metrics,pr.reliability_metrics perturbation_reliability,pr.evidence_manifest_sha256 perturbation_manifest
  from campaign c
  join private.tcj_admission_stage_a_summaries a on a.campaign_id=c.id
  join private.tcj_admission_stage_b_summaries b on b.campaign_id=c.id and b.judge_candidate_id=a.judge_candidate_id
  join rv1_pack rp on rp.campaign_id=c.id
  join private.tcj_admission_robustness_summaries r on r.pack_id=rp.id and r.judge_candidate_id=a.judge_candidate_id and r.summary_version='TCJ-ROBUSTNESS-SUMMARY-v1'
  join pert_pack pp on pp.campaign_id=c.id
  join private.tcj_admission_robustness_summaries pr on pr.pack_id=pp.id and pr.judge_candidate_id=a.judge_candidate_id and pr.summary_version='TCJ-ROBUSTNESS-PERTURB-SUMMARY-v1'
  where c.identity_revealed_at is null
), built as (
  select e.*,
    jsonb_build_object(
      'dossier_version','TCJ-JUDGE-PASSPORT-DOSSIER-v1',
      'anonymous_candidate_id',e.opaque_candidate_id,
      'profile_id',e.profile_id,
      'admission_protocol_version',e.protocol_version,
      'evidence_class','preliminary_admission_mixed_exposure',
      'dimensions',jsonb_build_array('intent','thai_pragmatics','bff_voice','lexical_social_fit','stance','composition'),
      'production_evidence',jsonb_build_object(
        'stage','blind_native_human_stage_a',
        'reviewed_count',e.reviewed_count,'accept_count',e.accept_count,'edit_count',e.edit_count,'rewrite_count',e.rewrite_count,'changed_count',e.changed_count,
        'summary',e.stage_a_summary,'evidence_manifest_sha256',e.stage_a_manifest
      ),
      'judging_evidence',jsonb_build_object(
        'stage','stage_b_judging_competence','case_count',e.stage_b_case_count,'valid_count',e.stage_b_valid_count,
        'dimension_metrics',e.dimension_metrics,'error_metrics',e.error_metrics,'evidence_manifest_sha256',e.stage_b_manifest,
        'evidence_boundary','legacy_exposed_calibration_preliminary'
      ),
      'robustness_evidence',jsonb_build_object(
        'frozen_input_v1',jsonb_build_object('repeat_metrics',e.repeat_metrics,'self_preference_metrics',e.self_preference_metrics,'reliability_metrics',e.robustness_reliability,'evidence_manifest_sha256',e.robustness_manifest,'evidence_boundary','preliminary_calibration_derived'),
        'constructed_perturbation_v1',jsonb_build_object('perturbation_metrics',e.perturbation_metrics,'reliability_metrics',e.perturbation_reliability,'evidence_manifest_sha256',e.perturbation_manifest,'evidence_boundary','preliminary_constructed_calibration_derived')
      ),
      'limitations',jsonb_build_array(
        'The 36-case Stage B bank is methodology-exposed Calibration evidence and cannot establish clean final qualification.',
        'The constructed perturbation pack is robustness evidence derived from exposed Calibration sources and is not Assurance evidence.',
        'No hidden Qualification Bank has yet been completed for this admission campaign.',
        'No Assurance bank evidence is included.',
        'Meta-review recommendations are preliminary admission recommendations, not production authority.'
      ),
      'review_task',jsonb_build_object(
        'protocol','TCJ-JUDGE-META-REVIEW-v1',
        'required_dimension_states',jsonb_build_array('qualified','partially_qualified','research_only','rejected'),
        'instruction','Assess each dimension independently from the supplied evidence and limitations. Do not infer model or provider identity. Do not upgrade exposed Calibration evidence into clean Qualification or Assurance evidence.'
      )
    ) dossier
  from evidence e
), finalized as (
  select b.*,
         ('PD-'||upper(substr(encode(extensions.digest(b.opaque_candidate_id||':TCJ-JUDGE-PASSPORT-DOSSIER-v1','sha256'),'hex'),1,16))) opaque_dossier_id,
         encode(extensions.digest(b.dossier::text,'sha256'),'hex') dossier_sha256
  from built b
)
insert into private.tcj_admission_passport_dossiers(
  campaign_id,judge_candidate_id,opaque_dossier_id,dossier_version,profile_id,admission_protocol_version,evidence_class,dossier,dossier_sha256,
  stage_a_manifest_sha256,stage_b_manifest_sha256,robustness_manifest_sha256,perturbation_manifest_sha256,frozen_at
)
select campaign_id,judge_candidate_id,opaque_dossier_id,'TCJ-JUDGE-PASSPORT-DOSSIER-v1',profile_id,protocol_version,'preliminary_admission_mixed_exposure',dossier,dossier_sha256,
       stage_a_manifest,stage_b_manifest,robustness_manifest,perturbation_manifest,pg_catalog.now()
from finalized
on conflict(campaign_id,judge_candidate_id,dossier_version) do nothing;

insert into private.tcj_admission_meta_reviews(campaign_id,dossier_id,reviewer_slot,review_protocol_version,dossier_sha256,review_state)
select d.campaign_id,d.id,s.slot,'TCJ-JUDGE-META-REVIEW-v1',d.dossier_sha256,'pending'
from private.tcj_admission_passport_dossiers d
cross join (values('chatgpt'),('grok')) s(slot)
join private.tcj_admission_campaigns c on c.id=d.campaign_id
where c.campaign_key='TCJ-JUDGE-ADMISSION-2026Q3-v1.2' and d.dossier_version='TCJ-JUDGE-PASSPORT-DOSSIER-v1'
on conflict(dossier_id,reviewer_slot,review_protocol_version) do nothing;
