create table if not exists private.tcj_admission_meta_review_attempts (
  id bigint generated by default as identity primary key,
  meta_review_id bigint not null references private.tcj_admission_meta_reviews(id),
  attempt_index integer not null check (attempt_index in (1,2)),
  attempt_role text not null check (attempt_role in ('primary','repair')),
  reviewer_slot text not null check (reviewer_slot in ('chatgpt','grok')),
  reviewer_provider text not null,
  reviewer_model text not null,
  http_status integer,
  outcome_class text not null check (outcome_class in ('valid','invalid_json','invalid_schema','provider_error','length','empty','infrastructure')),
  error_code text,
  raw_output_text text,
  raw_output_sha256 text,
  parsed_output jsonb,
  usage jsonb not null default '{}'::jsonb,
  latency_ms integer,
  created_at timestamptz not null default pg_catalog.now(),
  unique(meta_review_id,attempt_index),
  check (raw_output_sha256 is null or length(raw_output_sha256)=64),
  check (parsed_output is null or jsonb_typeof(parsed_output)='object'),
  check (jsonb_typeof(usage)='object')
);

alter table private.tcj_admission_meta_review_attempts enable row level security;
revoke all on private.tcj_admission_meta_review_attempts from anon, authenticated;
revoke all on sequence private.tcj_admission_meta_review_attempts_id_seq from anon, authenticated;

create index if not exists tcj_meta_review_attempts_review_idx on private.tcj_admission_meta_review_attempts(meta_review_id);
create index if not exists tcj_meta_reviews_campaign_state_idx on private.tcj_admission_meta_reviews(campaign_id,review_state,frozen_at);
create index if not exists tcj_meta_reviews_dossier_idx on private.tcj_admission_meta_reviews(dossier_id,reviewer_slot);

create or replace function private.tcj_try_freeze_meta_reviews(p_campaign_id bigint,p_protocol text)
returns boolean
language plpgsql
security definer
set search_path=pg_catalog,private,extensions
as $$
declare
  v_campaign private.tcj_admission_campaigns%rowtype;
  v_dossiers integer;
  v_reviews integer;
  v_slots integer;
  v_bad_hash integer;
  v_sealed integer;
begin
  select * into v_campaign from private.tcj_admission_campaigns where id=p_campaign_id for update;
  if not found then raise exception 'campaign_missing'; end if;
  if v_campaign.identity_revealed_at is not null then raise exception 'identity_already_revealed'; end if;
  if v_campaign.meta_reviews_frozen_at is not null then return true; end if;

  select count(*) into v_sealed
  from private.tcj_admission_campaign_candidates cc
  join private.tcj_judge_candidates j on j.id=cc.judge_candidate_id
  where cc.campaign_id=p_campaign_id and j.identity_state='sealed';
  if v_sealed<>3 then raise exception 'identity_seal_gate'; end if;

  select count(*) into v_dossiers
  from private.tcj_admission_passport_dossiers d
  where d.campaign_id=p_campaign_id and d.dossier_version='TCJ-JUDGE-PASSPORT-DOSSIER-v1' and d.frozen_at is not null;
  if v_dossiers<>3 then return false; end if;

  select count(*),count(distinct (dossier_id::text||':'||reviewer_slot))
  into v_reviews,v_slots
  from private.tcj_admission_meta_reviews m
  where m.campaign_id=p_campaign_id and m.review_protocol_version=p_protocol
    and m.review_state='valid' and m.frozen_at is not null
    and m.reviewer_slot in ('chatgpt','grok');
  if v_reviews<>6 or v_slots<>6 then return false; end if;

  select count(*) into v_bad_hash
  from private.tcj_admission_meta_reviews m
  join private.tcj_admission_passport_dossiers d on d.id=m.dossier_id
  where m.campaign_id=p_campaign_id and m.review_protocol_version=p_protocol
    and m.review_state='valid' and m.frozen_at is not null
    and (
      m.dossier_sha256<>d.dossier_sha256
      or m.raw_output_text is null
      or m.raw_output_sha256<>encode(extensions.digest(m.raw_output_text,'sha256'),'hex')
      or m.parsed_review is null
      or m.parsed_review_sha256<>encode(extensions.digest(m.parsed_review::text,'sha256'),'hex')
    );
  if v_bad_hash<>0 then raise exception 'meta_review_hash_gate'; end if;

  update private.tcj_admission_campaigns
  set meta_reviews_frozen_at=pg_catalog.now(),status='meta_review_frozen'
  where id=p_campaign_id and meta_reviews_frozen_at is null and status='stage_b_frozen';

  return true;
end;
$$;
revoke all on function private.tcj_try_freeze_meta_reviews(bigint,text) from public,anon,authenticated;
