create table private.tcj_admission_robustness_packs (
  id bigint generated by default as identity primary key,
  campaign_id bigint not null references private.tcj_admission_campaigns(id),
  pack_key text not null unique,
  pack_version text not null,
  status text not null check(status in ('draft','frozen','running','complete','aborted')),
  evidence_class text not null,
  description text not null default '',
  case_count integer not null default 0 check(case_count>=0),
  total_cells integer not null default 0 check(total_cells>=0),
  manifest_sha256 text,
  frozen_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create table private.tcj_admission_robustness_cases (
  id bigint generated by default as identity primary key,
  pack_id bigint not null references private.tcj_admission_robustness_packs(id),
  case_key text not null,
  family text not null check(family in ('repeat_identical','self_preference')),
  scenario_text text not null,
  candidate_text text not null,
  scenario_sha256 text not null,
  candidate_sha256 text not null,
  source_evidence_item_id bigint references private.tcj_evidence_items(id),
  source_generation_id bigint references private.tcj_admission_generations(id),
  source_generator_judge_id bigint references private.tcj_judge_candidates(id),
  source_meta jsonb not null default '{}'::jsonb check(jsonb_typeof(source_meta)='object'),
  frozen_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique(pack_id,case_key),
  check ((family='repeat_identical' and source_evidence_item_id is not null and source_generation_id is null)
      or (family='self_preference' and source_generation_id is not null and source_generator_judge_id is not null))
);

create table private.tcj_admission_robustness_attempts (
  id bigint generated by default as identity primary key,
  pack_id bigint not null references private.tcj_admission_robustness_packs(id),
  case_id bigint not null references private.tcj_admission_robustness_cases(id),
  judge_candidate_id bigint not null references private.tcj_judge_candidates(id),
  protocol_version text not null,
  prompt_version text not null,
  attempt_index integer not null check(attempt_index>0),
  attempt_role text not null check(attempt_role in ('primary','repair')),
  http_status integer,
  finish_reason text,
  outcome_class text not null check(outcome_class in ('valid','invalid_schema','length','empty','provider_error','infrastructure')),
  error_code text,
  raw_output_text text,
  raw_output_sha256 text,
  parsed_output jsonb,
  generation_settings jsonb not null default '{}'::jsonb,
  usage jsonb not null default '{}'::jsonb,
  latency_ms integer,
  evidence_eligible boolean not null default true,
  created_at timestamptz not null default now(),
  unique(pack_id,case_id,judge_candidate_id,protocol_version,attempt_index),
  check(parsed_output is null or jsonb_typeof(parsed_output)='object'),
  check(jsonb_typeof(generation_settings)='object'),
  check(jsonb_typeof(usage)='object')
);

create table private.tcj_admission_robustness_judgments (
  id bigint generated by default as identity primary key,
  pack_id bigint not null references private.tcj_admission_robustness_packs(id),
  case_id bigint not null references private.tcj_admission_robustness_cases(id),
  judge_candidate_id bigint not null references private.tcj_judge_candidates(id),
  opaque_judgment_id text not null unique,
  protocol_version text not null,
  prompt_version text not null,
  methodology_sha256 text not null,
  diagnosis jsonb not null check(jsonb_typeof(diagnosis)='object'),
  diagnosis_sha256 text not null,
  raw_output jsonb not null check(jsonb_typeof(raw_output)='object'),
  predicted_verdict text not null,
  generation_settings jsonb not null default '{}'::jsonb check(jsonb_typeof(generation_settings)='object'),
  usage jsonb not null default '{}'::jsonb check(jsonb_typeof(usage)='object'),
  latency_ms integer,
  created_at timestamptz not null default now(),
  unique(pack_id,case_id,judge_candidate_id)
);

create table private.tcj_admission_robustness_failures (
  id bigint generated by default as identity primary key,
  pack_id bigint not null references private.tcj_admission_robustness_packs(id),
  case_id bigint not null references private.tcj_admission_robustness_cases(id),
  judge_candidate_id bigint not null references private.tcj_judge_candidates(id),
  protocol_version text not null,
  prompt_version text not null,
  attempt_count integer not null default 1 check(attempt_count>0),
  last_http_status integer,
  last_error_code text not null,
  failure_class text not null check(failure_class in ('transient_provider','generation_contract','infrastructure')),
  evidence_state text not null default 'active' check(evidence_state in ('active','terminal','resolved','invalidated')),
  first_failed_at timestamptz not null default now(),
  last_failed_at timestamptz not null default now(),
  next_retry_at timestamptz,
  resolved_at timestamptz,
  error_meta jsonb not null default '{}'::jsonb check(jsonb_typeof(error_meta)='object'),
  created_at timestamptz not null default now(),
  unique(pack_id,case_id,judge_candidate_id,protocol_version)
);

create table private.tcj_admission_robustness_summaries (
  id bigint generated by default as identity primary key,
  pack_id bigint not null references private.tcj_admission_robustness_packs(id),
  judge_candidate_id bigint not null references private.tcj_judge_candidates(id),
  summary_version text not null,
  repeat_metrics jsonb not null default '{}'::jsonb check(jsonb_typeof(repeat_metrics)='object'),
  self_preference_metrics jsonb not null default '{}'::jsonb check(jsonb_typeof(self_preference_metrics)='object'),
  reliability_metrics jsonb not null default '{}'::jsonb check(jsonb_typeof(reliability_metrics)='object'),
  evidence_manifest_sha256 text not null,
  frozen_at timestamptz not null,
  created_at timestamptz not null default now(),
  unique(pack_id,judge_candidate_id)
);

alter table private.tcj_admission_robustness_packs enable row level security;
alter table private.tcj_admission_robustness_cases enable row level security;
alter table private.tcj_admission_robustness_attempts enable row level security;
alter table private.tcj_admission_robustness_judgments enable row level security;
alter table private.tcj_admission_robustness_failures enable row level security;
alter table private.tcj_admission_robustness_summaries enable row level security;

revoke all on private.tcj_admission_robustness_packs from anon, authenticated;
revoke all on private.tcj_admission_robustness_cases from anon, authenticated;
revoke all on private.tcj_admission_robustness_attempts from anon, authenticated;
revoke all on private.tcj_admission_robustness_judgments from anon, authenticated;
revoke all on private.tcj_admission_robustness_failures from anon, authenticated;
revoke all on private.tcj_admission_robustness_summaries from anon, authenticated;

create index tcj_robustness_packs_campaign_idx on private.tcj_admission_robustness_packs(campaign_id);
create index tcj_robustness_cases_pack_family_idx on private.tcj_admission_robustness_cases(pack_id,family);
create index tcj_robustness_cases_source_evidence_idx on private.tcj_admission_robustness_cases(source_evidence_item_id) where source_evidence_item_id is not null;
create index tcj_robustness_cases_source_generation_idx on private.tcj_admission_robustness_cases(source_generation_id) where source_generation_id is not null;
create index tcj_robustness_cases_source_generator_idx on private.tcj_admission_robustness_cases(source_generator_judge_id) where source_generator_judge_id is not null;
create index tcj_robustness_attempts_lookup_idx on private.tcj_admission_robustness_attempts(pack_id,case_id,judge_candidate_id);
create index tcj_robustness_attempts_judge_idx on private.tcj_admission_robustness_attempts(judge_candidate_id);
create index tcj_robustness_judgments_lookup_idx on private.tcj_admission_robustness_judgments(pack_id,case_id,judge_candidate_id);
create index tcj_robustness_judgments_judge_idx on private.tcj_admission_robustness_judgments(judge_candidate_id);
create index tcj_robustness_failures_lookup_idx on private.tcj_admission_robustness_failures(pack_id,case_id,judge_candidate_id);
create index tcj_robustness_failures_judge_idx on private.tcj_admission_robustness_failures(judge_candidate_id);
create index tcj_robustness_summaries_judge_idx on private.tcj_admission_robustness_summaries(judge_candidate_id);

do $$
declare
  v_campaign_id bigint; v_pack_id bigint; v_stage_b_frozen timestamptz; v_revealed timestamptz;
  v_unsealed integer; v_repeat integer; v_self integer; v_candidates integer; v_manifest text;
begin
  select id,stage_b_frozen_at,identity_revealed_at into v_campaign_id,v_stage_b_frozen,v_revealed
  from private.tcj_admission_campaigns where campaign_key='TCJ-JUDGE-ADMISSION-2026Q3-v1.2';
  if v_campaign_id is null or v_stage_b_frozen is null or v_revealed is not null then raise exception 'robustness_freeze_gate_campaign_state'; end if;
  select count(*) filter(where j.identity_state<>'sealed'),count(*) into v_unsealed,v_candidates
  from private.tcj_admission_campaign_candidates cc join private.tcj_judge_candidates j on j.id=cc.judge_candidate_id
  where cc.campaign_id=v_campaign_id;
  if v_candidates<>3 or v_unsealed<>0 then raise exception 'robustness_freeze_gate_identity'; end if;

  insert into private.tcj_admission_robustness_packs(campaign_id,pack_key,pack_version,status,evidence_class,description)
  values(v_campaign_id,'TCJ-JUDGE-ROBUSTNESS-2026Q3-v1','v1','draft','preliminary_calibration_derived',
    'Frozen-input robustness stratum: exact repeat stability across the exposed 36-case Stage B screen plus self/same-family preference testing across all 30 frozen Stage A outputs. Not Qualification or Assurance evidence.')
  returning id into v_pack_id;

  insert into private.tcj_admission_robustness_cases(pack_id,case_key,family,scenario_text,candidate_text,scenario_sha256,candidate_sha256,source_evidence_item_id,source_meta,frozen_at)
  select v_pack_id,'RPT-'||i.item_key,'repeat_identical',i.scenario_text,i.candidate_text,
         coalesce(i.scenario_sha256,encode(digest(i.scenario_text,'sha256'),'hex')),
         coalesce(i.candidate_sha256,encode(digest(i.candidate_text,'sha256'),'hex')),
         i.id,jsonb_build_object('source_set','TCJ-LEGACY-CALIBRATION-36-v1','source_exposure',i.exposure_state,'source_hashes_recomputed',i.scenario_sha256 is null or i.candidate_sha256 is null,'expected_use','repeat_stability_only'),now()
  from private.tcj_evidence_items i join private.tcj_evidence_sets s on s.id=i.evidence_set_id
  where s.set_key='TCJ-LEGACY-CALIBRATION-36-v1';

  insert into private.tcj_admission_robustness_cases(pack_id,case_key,family,scenario_text,candidate_text,scenario_sha256,candidate_sha256,source_generation_id,source_generator_judge_id,source_meta,frozen_at)
  select v_pack_id,'SELF-'||g.opaque_response_id,'self_preference',sc.scenario_text,g.response_text,
         coalesce(sc.scenario_sha256,encode(digest(sc.scenario_text,'sha256'),'hex')),
         coalesce(g.response_sha256,encode(digest(g.response_text,'sha256'),'hex')),
         g.id,g.judge_candidate_id,
         jsonb_build_object('human_decision',r.decision,'human_final_sha256',r.human_final_sha256,'review_order',g.review_order,'blind_human_review',r.blind_review,'expected_use','self_preference_analysis_only'),now()
  from private.tcj_admission_generations g join private.tcj_admission_scenarios sc on sc.id=g.scenario_id
  join private.tcj_admission_human_reviews r on r.generation_id=g.id and r.voided_at is null
  where g.campaign_id=v_campaign_id and r.frozen_at is not null and r.human_final_text is not null;

  select count(*) filter(where family='repeat_identical'),count(*) filter(where family='self_preference') into v_repeat,v_self
  from private.tcj_admission_robustness_cases where pack_id=v_pack_id;
  if v_repeat<>36 or v_self<>30 then raise exception 'robustness_freeze_gate_case_counts repeat=% self=%',v_repeat,v_self; end if;

  select encode(digest(string_agg(case_key||':'||scenario_sha256||':'||candidate_sha256||':'||family,'|' order by case_key),'sha256'),'hex') into v_manifest
  from private.tcj_admission_robustness_cases where pack_id=v_pack_id;

  update private.tcj_admission_robustness_packs set status='frozen',case_count=66,total_cells=66*v_candidates,manifest_sha256=v_manifest,frozen_at=now() where id=v_pack_id;
end $$;