import postgres from 'npm:postgres@3.4.7';
import {buildSystemPrompt,validateDiagnosis,detectCare,DIMS,TCJ_CORE_VERSION,TCJ_CORE_BLOB_SHA,type Diagnosis} from './canonical-contract.ts';

const DB=Deno.env.get('SUPABASE_DB_URL');
const GROQ=Deno.env.get('GROQ_API_KEY');
if(!DB) throw new Error('SUPABASE_DB_URL required');
const sql=postgres(DB,{prepare:false,max:2,idle_timeout:20,connect_timeout:10});
const ORIGIN='https://flipgazine.pages.dev';
const RUN_KEY='TCJ-JUDGE-QUALIFICATION-RUN-2026Q3-v1';
const RUN_PROTOCOL='TCJ-JUDGE-QUALIFICATION-RUN-v1';
const PROMPT_VERSION='TCJ-ANSWERS-BFF-v2@TCJ-CORE-v1';
const TEMP=0,MAX_TOKENS=500;
const REPAIR_SUFFIX='\nYour previous output failed the required JSON contract. Return only one valid JSON object with the required keys and allowed values. Do not add rewrite or suggestion content.';

type Claims={sub:string;session_id:string};
function dec(s:string){return atob(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4));}
function claims(req:Request):Claims|null{const m=(req.headers.get('authorization')||'').match(/^Bearer\s+([^\s]+)$/i);if(!m)return null;try{const p=m[1].split('.');if(p.length!==3)return null;const c=JSON.parse(dec(p[1]));return typeof c?.sub==='string'&&typeof c?.session_id==='string'?{sub:c.sub,session_id:c.session_id}:null;}catch{return null;}}
function headers(origin:string|null){const h=new Headers({'content-type':'application/json; charset=utf-8','cache-control':'no-store, private, max-age=0','pragma':'no-cache','x-content-type-options':'nosniff','referrer-policy':'no-referrer'});if(origin===ORIGIN){h.set('access-control-allow-origin',ORIGIN);h.set('vary','Origin');h.set('access-control-allow-methods','POST, OPTIONS');h.set('access-control-allow-headers','content-type, authorization');h.set('access-control-max-age','600');}return h;}
function out(origin:string|null,body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:headers(origin)});}
async function admin(c:Claims){return sql.begin(async tx=>{const a=await tx`select exists(select 1 from auth.users u join auth.sessions s on s.user_id=u.id where u.id=${c.sub}::uuid and s.id=${c.session_id}::uuid and u.deleted_at is null and (u.banned_until is null or u.banned_until<=pg_catalog.now()) and (s.not_after is null or s.not_after>pg_catalog.now())) ok`;if(!a?.[0]?.ok)return false;await tx`select pg_catalog.set_config('request.jwt.claim.sub',${c.sub}::text,true)`;const r=await tx`select public.is_fg_admin() ok`;return !!r?.[0]?.ok;});}
async function hash(s:string){const b=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));return Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');}
function effortFor(model:string){if(model==='qwen/qwen3.6-27b')return'none';if(model==='openai/gpt-oss-20b'||model==='openai/gpt-oss-120b')return'low';throw new Error('unsupported_model_adapter');}
function verdict(d:any){const r=d.ratings||d;if(String(d.severity||'').toUpperCase()==='CRITICAL'||Number(r.intent)===1||(Array.isArray(d.flags)&&d.flags.includes('semantic_drift')))return'not_acceptable';const v=DIMS.map(k=>Number(r[k]));if(String(d.severity||'').toUpperCase()==='MAJOR'||v.some(x=>x<=2))return'major_problem';if(String(d.severity||'').toUpperCase()==='MINOR'||v.some(x=>x===3))return'minor_problem';return'fluent';}
async function methodologyHash(repair:boolean,effort:string,care:boolean){const system=buildSystemPrompt(care)+(repair?REPAIR_SUFFIX:'');return hash(JSON.stringify({protocol:RUN_PROTOCOL,prompt_version:PROMPT_VERSION,canonical_core_version:TCJ_CORE_VERSION,canonical_core_blob_sha:TCJ_CORE_BLOB_SHA,care_mode:care,system_prompt:system,temperature:TEMP,max_completion_tokens:MAX_TOKENS,reasoning_effort:effort,response_format:'json_object',user_payload_keys:['question_or_scenario','candidate_response'],repair_policy:'one_schema_repair_then_terminal_no_semantic_resample'}));}

async function progress(){const q=await sql`select r.id run_id,r.status run_state,r.expected_cells,r.started_at,r.completed_at,r.run_manifest_sha256,p.id protocol_id,p.status protocol_state,p.evidence_set_id,r.campaign_id,(select count(*)::int from private.tcj_admission_campaign_candidates cc where cc.campaign_id=r.campaign_id) candidate_count,(select count(*)::int from private.tcj_evidence_items i where i.evidence_set_id=p.evidence_set_id) item_count,(select count(*)::int from private.tcj_qualification_attempts a where a.run_id=r.id) attempts,(select count(*)::int from private.tcj_qualification_judgments j where j.run_id=r.id) valid,(select count(*)::int from private.tcj_qualification_failures f where f.run_id=r.id and f.evidence_state='terminal' and f.failure_class='generation_contract') terminal_contract,(select count(*)::int from private.tcj_qualification_failures f where f.run_id=r.id and f.evidence_state='active' and f.failure_class='transient_provider') transient_failures,(select count(*)::int from private.tcj_qualification_failures f where f.run_id=r.id and f.evidence_state='active' and f.failure_class in ('generation_contract','infrastructure')) blockers from private.tcj_qualification_runs r join private.tcj_qualification_protocols p on p.id=r.protocol_id where r.run_key=${RUN_KEY}::text limit 1`;const r=q[0];if(!r)throw new Error('qualification_run_missing');const valid=Number(r.valid||0),terminal=Number(r.terminal_contract||0),expected=Number(r.expected_cells||0),done=valid+terminal;return{run_id:Number(r.run_id),protocol_id:Number(r.protocol_id),campaign_id:Number(r.campaign_id),evidence_set_id:Number(r.evidence_set_id),run_key:RUN_KEY,run_state:String(r.run_state),protocol_state:String(r.protocol_state),expected_cells:expected,candidate_count:Number(r.candidate_count||0),item_count:Number(r.item_count||0),attempts:Number(r.attempts||0),valid,terminal_contract:terminal,done,pending:Math.max(0,expected-done),transient_failures:Number(r.transient_failures||0),blockers:Number(r.blockers||0),started:!!r.started_at,completed:!!r.completed_at,run_manifest_sha256:r.run_manifest_sha256||null};}

async function sourceGate(expectPrivate:boolean){const q=await sql`select r.id run_id,r.protocol_id,r.campaign_id,r.status run_state,r.config_sha256,r.threshold_sha256 run_threshold,r.human_manifest_sha256 run_human,r.evidence_manifest_sha256 run_evidence,r.expected_cells,p.status protocol_state,p.evidence_set_id,p.threshold_sha256,p.human_manifest_sha256,s.status set_state,s.manifest_sha256 evidence_manifest,(r.config_sha256=encode(extensions.digest(r.config::text,'sha256'),'hex')) config_match,(select count(*)::int from private.tcj_qualification_human_reviews hr where hr.protocol_id=p.id and hr.review_state='frozen') frozen_reviews,(select count(*)::int from private.tcj_evidence_items i where i.evidence_set_id=p.evidence_set_id) items,(select count(*)::int from private.tcj_evidence_items i where i.evidence_set_id=p.evidence_set_id and i.exposure_state='private') private_items,(select count(*)::int from private.tcj_evidence_items i where i.evidence_set_id=p.evidence_set_id and i.exposure_state='qualification_exposed') exposed_items from private.tcj_qualification_runs r join private.tcj_qualification_protocols p on p.id=r.protocol_id join private.tcj_evidence_sets s on s.id=p.evidence_set_id where r.run_key=${RUN_KEY}::text limit 1`;const x=q[0];if(!x)throw new Error('qualification_run_missing');if(!x.config_match)throw new Error('qualification_config_hash_gate');if(String(x.set_state)!=='frozen')throw new Error('qualification_evidence_set_state_gate');if(String(x.run_threshold)!==String(x.threshold_sha256)||String(x.run_human)!==String(x.human_manifest_sha256)||String(x.run_evidence)!==String(x.evidence_manifest))throw new Error('qualification_source_manifest_gate');if(Number(x.frozen_reviews)!==48||Number(x.items)!==48||Number(x.expected_cells)!==144)throw new Error('qualification_source_count_gate');if(expectPrivate&&Number(x.private_items)!==48)throw new Error('qualification_pre_exposure_gate');if(!expectPrivate&&Number(x.exposed_items)!==48)throw new Error('qualification_exposure_state_gate');return x;}

async function startRun(){const x=await sourceGate(true);await sql.begin(async tx=>{const rows=await tx`select i.id,i.exposure_state from private.tcj_evidence_items i where i.evidence_set_id=${Number(x.evidence_set_id)}::bigint order by i.id for update`;if(rows.length!==48||rows.some((r:any)=>r.exposure_state!=='private'))throw new Error('qualification_pre_exposure_gate');await tx`update private.tcj_evidence_items set exposure_state='qualification_exposed' where evidence_set_id=${Number(x.evidence_set_id)}::bigint and exposure_state='private'`;await tx`update private.tcj_qualification_runs set status='running',started_at=coalesce(started_at,pg_catalog.now()) where id=${Number(x.run_id)}::bigint and status='frozen'`;await tx`update private.tcj_qualification_protocols set status='running',run_started_at=coalesce(run_started_at,pg_catalog.now()) where id=${Number(x.protocol_id)}::bigint and status='bank_frozen'`;});return sourceGate(false);}

async function recordFailure(runId:number,itemId:number,judgeId:number,httpStatus:number|null,errorCode:string,failureClass:'transient_provider'|'generation_contract'|'infrastructure',state:'active'|'terminal',meta:any,retryable:boolean){const old=await sql`select attempt_count from private.tcj_qualification_failures where run_id=${runId}::bigint and evidence_item_id=${itemId}::bigint and judge_candidate_id=${judgeId}::bigint limit 1`;const n=Number(old[0]?.attempt_count||0)+1,delay=Math.min(120,5*Math.pow(2,Math.min(n-1,5))),retryIso=retryable?new Date(Date.now()+delay*1000).toISOString():null;await sql`insert into private.tcj_qualification_failures(run_id,evidence_item_id,judge_candidate_id,attempt_count,last_http_status,last_error_code,failure_class,evidence_state,first_failed_at,last_failed_at,next_retry_at,resolved_at,error_meta) values(${runId}::bigint,${itemId}::bigint,${judgeId}::bigint,${n}::int,${httpStatus}::int,${errorCode}::text,${failureClass}::text,${state}::text,pg_catalog.now(),pg_catalog.now(),${retryIso}::timestamptz,null,${JSON.stringify(meta||{})}::jsonb) on conflict(run_id,evidence_item_id,judge_candidate_id) do update set attempt_count=${n}::int,last_http_status=${httpStatus}::int,last_error_code=${errorCode}::text,failure_class=${failureClass}::text,evidence_state=${state}::text,last_failed_at=pg_catalog.now(),next_retry_at=${retryIso}::timestamptz,resolved_at=null,error_meta=${JSON.stringify(meta||{})}::jsonb`;return delay;}
async function markResolved(runId:number,itemId:number,judgeId:number){await sql`update private.tcj_qualification_failures set resolved_at=pg_catalog.now(),next_retry_at=null,evidence_state='resolved' where run_id=${runId}::bigint and evidence_item_id=${itemId}::bigint and judge_candidate_id=${judgeId}::bigint and evidence_state<>'terminal'`;}
async function nextAttemptIndex(runId:number,itemId:number,judgeId:number){const r=await sql`select coalesce(max(attempt_index),0)::int n from private.tcj_qualification_attempts where run_id=${runId}::bigint and evidence_item_id=${itemId}::bigint and judge_candidate_id=${judgeId}::bigint`;return Number(r[0]?.n||0)+1;}

async function providerCall(model:string,scenario:string,candidate:string,care:boolean,repair:boolean){if(!GROQ)throw new Error('groq_secret_missing');const effort=effortFor(model),system=buildSystemPrompt(care)+(repair?REPAIR_SUFFIX:''),userPayload={question_or_scenario:scenario,candidate_response:candidate};const requestBody={model,temperature:TEMP,max_completion_tokens:MAX_TOKENS,reasoning_effort:effort,response_format:{type:'json_object'},stream:false,messages:[{role:'system',content:system},{role:'user',content:JSON.stringify(userPayload)}]};const requestJson=JSON.stringify(requestBody),started=performance.now();const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{authorization:`Bearer ${GROQ}`,'content-type':'application/json'},body:requestJson});const latency=Math.round(performance.now()-started),providerText=await r.text();let payload:any=null;try{payload=providerText?JSON.parse(providerText):null;}catch{}return{ok:r.ok,status:r.status,payload,providerText,latency,effort,repair,care,system,userPayload,requestBody,requestJson};}

async function insertAttempt(runId:number,itemId:number,judgeId:number,attemptIndex:number,role:'primary'|'repair',call:any,outcome:string,errorCode:string|null){const choice=call.payload?.choices?.[0]||{},finish=String(choice?.finish_reason||'')||null,content=String(choice?.message?.content||'').trim(),rawSha=content?await hash(content):null,providerSha=call.providerText?await hash(call.providerText):null,requestSha=await hash(call.requestJson),systemSha=await hash(call.system),userSha=await hash(JSON.stringify(call.userPayload));let parsed:any=null;try{parsed=content?JSON.parse(content):null;}catch{}const usage=call.payload?.usage||{},settings={temperature:TEMP,max_completion_tokens:MAX_TOKENS,reasoning_effort:call.effort,response_format:'json_object',care_mode:call.care,repair:role==='repair',canonical_core_version:TCJ_CORE_VERSION,canonical_core_blob_sha:TCJ_CORE_BLOB_SHA};const rows=await sql`insert into private.tcj_qualification_attempts(run_id,evidence_item_id,judge_candidate_id,attempt_index,attempt_role,protocol_version,prompt_version,request_payload,request_sha256,system_prompt_sha256,user_payload_sha256,http_status,finish_reason,outcome_class,error_code,provider_response_text,provider_response_sha256,raw_output_text,raw_output_sha256,parsed_output,generation_settings,usage,latency_ms,evidence_eligible) values(${runId}::bigint,${itemId}::bigint,${judgeId}::bigint,${attemptIndex}::int,${role}::text,${RUN_PROTOCOL}::text,${PROMPT_VERSION}::text,${JSON.stringify(call.requestBody)}::jsonb,${requestSha}::text,${systemSha}::text,${userSha}::text,${Number(call.status||0)}::int,${finish}::text,${outcome}::text,${errorCode}::text,${call.providerText||null}::text,${providerSha}::text,${content||null}::text,${rawSha}::text,${parsed?JSON.stringify(parsed):null}::jsonb,${JSON.stringify(settings)}::jsonb,${JSON.stringify(usage)}::jsonb,${Number(call.latency||0)}::int,true) returning id,request_sha256,parsed_output,generation_settings,usage,latency_ms`;return rows[0];}

async function persistJudgment(runId:number,itemId:number,judgeId:number,attempt:any,diagnosis:Diagnosis,repair:boolean,care:boolean){const effort=String(attempt.generation_settings?.reasoning_effort||'none'),msha=await methodologyHash(repair,effort,care),ds=await sql`select encode(extensions.digest(${JSON.stringify(diagnosis)}::jsonb::text,'sha256'),'hex') sha`,dsha=String(ds[0].sha),opaque='QJ-'+crypto.randomUUID().replaceAll('-','').slice(0,14).toUpperCase();await sql`insert into private.tcj_qualification_judgments(run_id,evidence_item_id,judge_candidate_id,source_attempt_id,opaque_judgment_id,protocol_version,prompt_version,methodology_sha256,request_sha256,diagnosis,diagnosis_sha256,predicted_verdict,generation_settings,usage,latency_ms) values(${runId}::bigint,${itemId}::bigint,${judgeId}::bigint,${Number(attempt.id)}::bigint,${opaque}::text,${RUN_PROTOCOL}::text,${PROMPT_VERSION}::text,${msha}::text,${String(attempt.request_sha256)}::text,${JSON.stringify(diagnosis)}::jsonb,${dsha}::text,${verdict(diagnosis)}::text,${JSON.stringify(attempt.generation_settings||{})}::jsonb,${JSON.stringify(attempt.usage||{})}::jsonb,${Number(attempt.latency_ms||0)}::int) on conflict(run_id,evidence_item_id,judge_candidate_id) do nothing`;await markResolved(runId,itemId,judgeId);}

async function executeCall(runId:number,itemId:number,judgeId:number,model:string,scenario:string,candidate:string,care:boolean,role:'primary'|'repair'){const idx=await nextAttemptIndex(runId,itemId,judgeId),call=await providerCall(model,scenario,candidate,care,role==='repair');if(!call.ok){const at=await insertAttempt(runId,itemId,judgeId,idx,role,call,'provider_failure',`groq_${call.status||'error'}`),retryable=Number(call.status)===429||Number(call.status)>=500;if(retryable){const delay=await recordFailure(runId,itemId,judgeId,Number(call.status||0),`groq_${call.status||'error'}`,'transient_provider','active',{attempt_id:at.id,provider_error_type:call.payload?.error?.type||null,provider_error_message:String(call.payload?.error?.message||'').slice(0,500)},true);return{kind:'deferred',retry_after_seconds:delay};}await recordFailure(runId,itemId,judgeId,Number(call.status||0),`groq_${call.status||'error'}`,'infrastructure','active',{attempt_id:at.id,provider_error_type:call.payload?.error?.type||null,provider_error_message:String(call.payload?.error?.message||'').slice(0,500)},false);return{kind:'blocked'};}
const choice=call.payload?.choices?.[0]||{},finish=String(choice?.finish_reason||''),content=String(choice?.message?.content||'').trim();if(finish==='length'){const at=await insertAttempt(runId,itemId,judgeId,idx,role,call,'length','generation_length_limit');return{kind:'terminal',error:'generation_length_limit',attempt:at};}if(!content){const at=await insertAttempt(runId,itemId,judgeId,idx,role,call,'empty','empty_generation');return{kind:'terminal',error:'empty_generation',attempt:at};}try{const raw=JSON.parse(content),diagnosis=validateDiagnosis(raw),at=await insertAttempt(runId,itemId,judgeId,idx,role,call,'valid',null);return{kind:'valid',diagnosis,attempt:at};}catch(e){const code=e instanceof Error?e.message:'invalid_json',at=await insertAttempt(runId,itemId,judgeId,idx,role,call,'invalid_schema',code);return{kind:'invalid',error:code,attempt:at};}}

async function runNext(){let p=await progress();if(p.run_state==='complete')return{status:'complete',...p};if(p.blockers>0)return{status:'blocked',reason:'adapter_or_infrastructure_validity_failure',...p};if(p.run_state==='frozen')await startRun();else await sourceGate(false);p=await progress();if(p.pending<=0)return{status:'ready_to_finalize',...p};
const next=await sql`select i.id evidence_item_id,i.item_key,i.scenario_text,i.candidate_text,j.id judge_candidate_id,j.provider,j.model_name from private.tcj_evidence_items i join private.tcj_qualification_protocols p on p.evidence_set_id=i.evidence_set_id join private.tcj_qualification_runs r on r.protocol_id=p.id join private.tcj_admission_campaign_candidates cc on cc.campaign_id=r.campaign_id join private.tcj_judge_candidates j on j.id=cc.judge_candidate_id left join private.tcj_qualification_failures f on f.run_id=r.id and f.evidence_item_id=i.id and f.judge_candidate_id=j.id where r.id=${p.run_id}::bigint and i.evidence_set_id=${p.evidence_set_id}::bigint and not exists(select 1 from private.tcj_qualification_judgments x where x.run_id=r.id and x.evidence_item_id=i.id and x.judge_candidate_id=j.id) and not exists(select 1 from private.tcj_qualification_failures t where t.run_id=r.id and t.evidence_item_id=i.id and t.judge_candidate_id=j.id and t.evidence_state='terminal') and (f.id is null or f.evidence_state='resolved' or (f.failure_class='transient_provider' and f.evidence_state='active' and f.next_retry_at<=pg_catalog.now())) order by i.item_key,j.id limit 1`;
if(!next.length){p=await progress();if(p.blockers>0)return{status:'blocked',reason:'adapter_or_infrastructure_validity_failure',...p};if(p.pending<=0)return{status:'ready_to_finalize',...p};const w=await sql`select greatest(1,ceil(extract(epoch from (min(next_retry_at)-pg_catalog.now()))))::int seconds from private.tcj_qualification_failures where run_id=${p.run_id}::bigint and evidence_state='active' and failure_class='transient_provider' and next_retry_at>pg_catalog.now()`;return{status:'waiting_retry',retry_after_seconds:Number(w[0]?.seconds||5),...p};}
const x:any=next[0],runId=p.run_id,itemId=Number(x.evidence_item_id),judgeId=Number(x.judge_candidate_id);if(x.provider!=='groq'){await recordFailure(runId,itemId,judgeId,null,'unsupported_provider','infrastructure','active',{classification:'adapter_validity'},false);return{status:'blocked',reason:'unsupported_provider',...(await progress())};}const care=detectCare(String(x.scenario_text)),prior=await sql`select id,attempt_index,attempt_role,outcome_class,error_code,parsed_output,request_sha256,generation_settings,usage,latency_ms from private.tcj_qualification_attempts where run_id=${runId}::bigint and evidence_item_id=${itemId}::bigint and judge_candidate_id=${judgeId}::bigint order by attempt_index`;
const validPrior=prior.find((a:any)=>a.outcome_class==='valid');if(validPrior?.parsed_output){const diagnosis=validateDiagnosis(validPrior.parsed_output);await persistJudgment(runId,itemId,judgeId,validPrior,diagnosis,String(validPrior.attempt_role)==='repair',care);return{status:'ok',...(await progress())};}
const semantic=prior.filter((a:any)=>a.outcome_class!=='provider_failure'),primary=semantic.find((a:any)=>a.attempt_role==='primary'),repair=semantic.find((a:any)=>a.attempt_role==='repair');if(primary&&['length','empty'].includes(primary.outcome_class)){await recordFailure(runId,itemId,judgeId,200,String(primary.error_code||primary.outcome_class),'generation_contract','terminal',{source_attempt_id:primary.id,stage:'primary',policy:'terminal_no_resample'},false);return{status:'cell_terminal',...(await progress())};}if(repair&&repair.outcome_class!=='valid'){await recordFailure(runId,itemId,judgeId,200,String(repair.error_code||repair.outcome_class),'generation_contract','terminal',{source_attempt_id:repair.id,stage:'repair',policy:'one_repair_then_terminal'},false);return{status:'cell_terminal',...(await progress())};}
const role:'primary'|'repair'=primary&&primary.outcome_class==='invalid_schema'?'repair':'primary',res:any=await executeCall(runId,itemId,judgeId,String(x.model_name),String(x.scenario_text),String(x.candidate_text),care,role);if(res.kind==='deferred')return{status:'waiting_retry',retry_after_seconds:res.retry_after_seconds,...(await progress())};if(res.kind==='blocked')return{status:'blocked',reason:'provider_or_adapter_contract_failure',...(await progress())};if(res.kind==='valid'){await persistJudgment(runId,itemId,judgeId,res.attempt,res.diagnosis,role==='repair',care);p=await progress();return{status:p.pending<=0?'ready_to_finalize':'ok',...p};}if(res.kind==='terminal'){await recordFailure(runId,itemId,judgeId,200,res.error,'generation_contract','terminal',{source_attempt_id:res.attempt?.id,stage:role,policy:role==='repair'?'one_repair_then_terminal':'terminal_no_resample'},false);return{status:'cell_terminal',...(await progress())};}if(res.kind==='invalid'){if(role==='repair'){await recordFailure(runId,itemId,judgeId,200,res.error,'generation_contract','terminal',{source_attempt_id:res.attempt?.id,stage:'repair',policy:'one_repair_then_terminal'},false);return{status:'cell_terminal',...(await progress())};}return{status:'needs_repair',...(await progress())};}throw new Error('qualification_runner_unreachable');}

Deno.serve(async(req:Request)=>{const origin=req.headers.get('origin');if(req.method==='OPTIONS')return origin===ORIGIN?new Response(null,{status:204,headers:headers(origin)}):out(origin,{error:'forbidden'},403);if(origin!==ORIGIN)return out(origin,{error:'forbidden'},403);if(req.method!=='POST')return out(origin,{error:'method_not_allowed'},405);const c=claims(req);if(!c)return out(origin,{error:'unauthorized'},401);if(!(await admin(c)))return out(origin,{error:'forbidden'},403);let body:any={};try{body=await req.json();}catch{return out(origin,{error:'invalid_json'},400);}try{if(body?.action==='status')return out(origin,{status:'ok',...(await progress())});if(body?.action==='run_next')return out(origin,await runNext());return out(origin,{error:'invalid_action'},422);}catch(e){console.error('tcj-qualification-runner-v1',e);return out(origin,{error:e instanceof Error?e.message:'service_unavailable'},503);}});
